### ISSUE TITLE
Public publisher pages

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/snapcraft.io#1006]
Currently, if a publisher wants to say to users “Here are all our snaps” — or even if we want to say “This company has published a bunch of snaps” — there isn’t a reliable place to link to. Linking to search results, for the name of the publisher, currently works only if the publisher name is repeated in the title or description (#328). And even when that’s fixed, search results would include _any_ snap mentioning that name, [whether it’s from that publisher or not](https://snapcraft.io/search?category=&q=microsoft).

Separately, if you really like a particular app, and you wonder if the same publisher has any other apps, there’s no easy way to find them.

Both problems could be solved with a publisher page, that gives the name of the publisher and a complete list of their snaps.

Possible extra elements for the page:
- company logo
- company header artwork
- brief publisher description
- filter field, if the publisher has many snaps (#950).

Comparison: Google Play publisher pages for [Microsoft](https://play.google.com/store/apps/dev?id=6720847872553662727), [Google](https://play.google.com/store/apps/dev?id=5700313618786177705), [Rovio](https://play.google.com/store/apps/dev?id=9133452689932095671).

[This idea has previously been discussed, but doesn’t seem to be recorded.]

**Comment by therealjuan** [comment]
[Closing as this will be done as part of this piece of work](https://github.com/CanonicalLtd/snap-squad/issues/990)

**Comment by therealjuan** [comment]
Please comment before opening new issues as this requires extra work for the reporter and whomever is managing the backlog
