### ISSUE TITLE
Search for “snapcrafters” returns many incorrect results

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/snapcraft.io#1007]
1\. [Search the directory for “snapcrafters”](https://snapcraft.io/search?category=&q=snapcrafters).
2\. Open the page for each result.

What you see: None of the results mention “snapcrafters” anywhere.

For example, [Snap Store Proxy](https://snapcraft.io/snap-store-proxy), [stonscipap-snap](https://snapcraft.io/stonscipap-snap), and [uboot-tools](https://snapcraft.io/uboot-tools) are all returned as results but do not mention snapcrafters.

What you should see: If a snap doesn’t mention the search term, it isn’t returned as a search result.

**Comment by matthewpaulthomas** [comment]
I didn’t know that search bugs are store bugs. Re-reported as [LP#1786929](https://bugs.launchpad.net/snapstore/+bug/1786929).

**Comment by therealjuan** [comment]
This problem is part of the store not the website so closing.

**Comment by matthewpaulthomas** [comment]
The store bug was marked as “Won’t Fix”, but the problem still exists. At standup we agreed that the next step is for us to more precisely specify expected behavior so that the store team has something to implement.

**Comment by therealjuan** [comment]
Let's create a new task for next iteration where we can collate all documentation and issues related to search improvements, so we can discuss in Brussels with the Store team to start speccing out implementation details.

That way we can close this one

**Comment by solazio** [comment]
@matthewpaulthomas  this seems to work fine now. Can you please confirm.

**Comment by matthewpaulthomas** [comment]
Two of the three examples I gave are still returned when they shouldn’t be:
- Snap Store Proxy is on [page 2](https://snapcraft.io/search?q=snapcrafters&page=2)
- uboot-tools is on [page 4](https://snapcraft.io/search?q=snapcrafters&page=4)

One thing those two have in common, which stonscipap-snap doesn’t (any longer?), is that they mention “snapcraft” — not “snapcrafters”, but “snapcraft” — in their description. So, maybe the cause is overzealous stemming of search terms. It _might_ be reasonable to stem other words, but not “snapcraft” in particular.

**Comment by danielmutis** [comment]
I don't think the real issue is that we are returning snaps that contain the word "snapcraft". If you try to search for "snapcraftpotato" it doesn't return any results. I think the issue here must have to do with how we group different publishers under the label "Snapcrafters" and some of their snaps aren't included under this pseudonym. 

In any case, if you search for this word, all the top results are relevant to the search, so I don't think this impedes the user from finding what they are searching for.
