### ISSUE TITLE
Revisions in closed channels are incorrectly marked as available to install

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/snapcraft.io#1020]
### Expected behaviour
Revisions in closed channels should not be shown as available to install

### Steps to reproduce the problem
 
1. Given a snap with a release in e.g. beta, close that channel
2. Verify channel map in `snapcraft status` e.g.
```
$ snapcraft status snap-store-proxy
Track    Arch    Channel    Version    Revision
latest   amd64   stable     1.0        8
                 candidate  ^          ^
                 beta       ^          ^
                 edge       1.1        10
```
3. Visit the Releases and revision history page e.g. https://snapcraft.io/account/snaps/snap-store-proxy/release
4. Note that the release for the closed channel is shown as available, in contrast to the channel map shown in `snapcraft`

### Specs

- _URL:_ https://snapcraft.io/account/snaps/snap-store-proxy/release
- _Operating system:_ Ubuntu 18.04 LTS
- _Browser:_ Firefox 61.0.2

**Comment by cprov** [comment]
FWIW,  for the mentioned snap (no tracks or branches):
```
$ surl -a prod 'https://dashboard.snapcraft.io/api/v2/snaps/snap-store-proxy/releases' | jq '.revisions as $revs | .releases | group_by(.risk)[][0] | "\(.risk) => \(.revision)"' -r
beta => null
candidate => null
edge => 10
stable => 8
```
To obtain the `version` and other details look the revision up in `.revisions`.

**Comment by solazio** [comment]
@sparkiegeek I was not able o replicate this. Considering it was reported a while ago, I assume it is fixed. Please reopen if needed.
