### ISSUE TITLE
AWS Greengrass snap

### ISSUE THREAD

**Issue by vivekd-see** [canonical-web-and-design/snapcraft.io#1035]
### Have seen many articles saying AWS greengrass is available as a snap. Can't find it in store.

https://blog.ubuntu.com/2017/06/13/amazon-greengrass-launches-as-a-snap-on-ubuntu

**Comment by therealjuan** [comment]
Hello and thanks for bringing this to our attention.

Here you can find a link to the AWS greengrass snap: https://snapcraft.io/aws-iot-greengrass
