### ISSUE TITLE
Some snaps 'hidden' on mobile Store page

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/snapcraft.io#1055]
Snapcraft Store page on mobile doesn't show any indication that snap lists are scrollable:
<img width="378" alt="screen shot 2018-09-03 at 14 05 27" src="https://user-images.githubusercontent.com/83575/44986011-a560e480-af82-11e8-86b7-9ba290f825d4.png">

Only 2 snaps per category are visible and only when user discovers they can scroll horizontally more snaps can be found.

It would be good to show all snaps on mobile (without unnecessary horizontal scroll) or give some visual indication that some content is hidden.

**Comment by therealjuan** [comment]
Not happening anymore :tada:
