### ISSUE TITLE
infinite redirect trying to sign a dev agreement

### ISSUE THREAD

**Issue by imajes** [canonical-web-and-design/snapcraft.io#1159]
### Expected behaviour
be able to sign a dev agreement so i can actually create a snap

### Steps to reproduce the problem
login to snapcraft > click account details > observe infinite redirect loop

### Specs

- _URL:_

https://dashboard.snapcraft.io/dev/account/?next=%2Fdev%2Fagreements%2Fnew%2F%3Fnext%3D%252Fdev%252Faccount%252F

redirects to 

https://dashboard.snapcraft.io/dev/agreements/new/?next=%2Fdev%2Faccount%2F

etc.

- _Operating system:_ The Internet

- _Browser:_ Chrome, Safari...

**Comment by tbille** [comment]
Followed the steps with a new account.
This seems to be fixed now.
