### ISSUE TITLE
Consider using webpack's hot module replacement

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/snapcraft.io#1244]
Now that we migrate our build to webpack we could try using the benefits of hot module replacement.
https://webpack.js.org/guides/hot-module-replacement/

This allows reloading only the changed JS modules automatically in the browser in development.

It involves some changes to how we build the project and didn't fit in scope of initial webpack migration.

For that to work we would need to set up webpack dev server to serve built assets. This means we would need to run in it paralel to our flask server and make it aware that JS assets in dev mode are served from different host.

**Comment by solazio** [comment]
Long story short, this is a very good tool/concept with great benefits, however given our current stack it doesn't really make sense to use it.
