### ISSUE TITLE
Webpack warns about publisher.js bundle being big

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/snapcraft.io#1246]
Webpack build (production) show a warning about publisher.js bundle being too big.
We should try to make it smaller (remove some stuff?) or break it into smaller pieces (separate bundle for each of the pages?).
<img width="1430" alt="screen shot 2018-10-26 at 14 57 14" src="https://user-images.githubusercontent.com/83575/47567672-7e45e400-d92f-11e8-9941-4599e1f494df.png">

**Comment by solazio** [comment]
We don't get this warning anymore, closing.

![image](https://user-images.githubusercontent.com/40214246/81162652-7257cb00-8f85-11ea-915c-f9e2774d3357.png)
