### ISSUE TITLE
Make greyed out future steps clickable, so you can jump ahead

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/snapcraft.io#1298]
From @mariadeanton. While you can't skip everything (OS selection, in particular), there are steps you could skip, like packaging and testing (when on a Mac). We should let the user jump past these, as they may be trying to find their way back to a point in the first snap flow.

![screenshot 2018-11-12 at 17 52 10](https://user-images.githubusercontent.com/1523179/48365817-e0c71000-e6a3-11e8-88b0-8ef05c9b89ae.png)

**Comment by Lukewh** [comment]
This will only be possible once a user is on the "package" page - as the steps define the URL.
