### ISSUE TITLE
Running snapcraft assumes lxd/multipass is setup

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#1305]
### Expected behaviour

Run snapcraft and produce a snap

### Steps to reproduce the problem

Follow the python tutorial. When you get to the build step it fails because snapcraft doesn't natively work on Mint and requires lxd/multipass to work properly.

```
snapcraft
Native builds aren't supported on Linux Mint. You can however use 'snapcraft cleanbuild' with a container.
```

Follow those instructions and it also fails...

```
snapcraft cleanbuild
Failed to initialize container: LXD could not be found.
You must have LXD installed in order to use cleanbuild. Reefer to the documentation at https://linuxcontainers.org/lxd/getting-started-cli
```

### Specs

- _URL:_ https://snapcraft.io/first-snap/python/linux/build
- _Operating system:_ Linux Mint 19
- _Browser:_

**Comment by tbille** [comment]
This issue is not relevant anymore.
