### ISSUE TITLE
Duplicate, invalid GPL license options in the drop down list

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [canonical-web-and-design/snapcraft.io#1329]
### Expected behaviour
Only unique license items in the list 

### Steps to reproduce the problem
![default](https://user-images.githubusercontent.com/13408130/48663791-20d92900-ead0-11e8-8fca-91c55d06a3e7.png)

Only the latter option work, if the former option is selected it will return the following error:

```
 Invalid symbols sequence such as (A B) for token: "-only" at position: 18 
```

### Specs

- _URL:_ https://snapcraft.io/_snap_name_/listing
- _Operating system:_ Ubuntu 18.10 AMD64
- _Browser:_ Mozilla Firefox 63.0

**Comment by jdahlin** [comment]
This is happening because snapcraft.io downloads a new license.json as part of the build process. It contains newer licenses that the dashboard does not understand.

The solution is to not download a new version but keep a static copy and make sure it's synchronized with the dashboard.

**Comment by Roadmaster** [comment]
Relevant bugs about the issues with moving to newer SPDX versions while other components in the snap ecosystem (store, snapd, snapcraft) haven't done so:

https://bugs.launchpad.net/snapstore/+bug/1781013
https://forum.snapcraft.io/t/keeping-up-with-spdx-license-identifier-updates/7095/
https://bugs.launchpad.net/snapd/+bug/1781267
https://github.com/snapcore/snapd/pull/6152
