### ISSUE TITLE
Developer pages are not mobile friendly 

### ISSUE THREAD

**Issue by apolitech** [canonical-web-and-design/snapcraft.io#1352]
### Expected behaviour
The site to be mobile compatible.
### Steps to reproduce the problem
Use a phone
### Specs
Iphone 6s
- _URL:_-
- _Operating system:_ios 12.x
- _Browser:_safari

**Comment by apolitech** [comment]
![a7b2aca9-9ad9-4474-9c36-cda71271051e](https://user-images.githubusercontent.com/14872517/48941345-e9c9a400-ef23-11e8-9925-19f2a74c346d.png)

**Comment by solazio** [comment]
This issue has been fixed [here](https://github.com/canonical-web-and-design/snapcraft.io/pull/2459). Closing...
