### ISSUE TITLE
"Show revisions released in" incorrectly ordered

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/snapcraft.io#1411]
Have a look at the release UI for the go snap:
![screenshot 2018-12-06 at 19 12 12](https://user-images.githubusercontent.com/1523179/49606318-f372f300-f98a-11e8-99bb-11557666ba82.png)

This should probably order as:
```
latest
1.11
1.10
1.9
1.8
1.7
1.6
```

**Comment by bartaz** [comment]
I believe we have correct ordering on snap details page channel map:
<img width="153" alt="screen shot 2018-12-07 at 08 43 29" src="https://user-images.githubusercontent.com/83575/49634220-56e93900-f9fc-11e8-9751-aca7db5bff49.png">


We should use the same on Releases page.
