### ISSUE TITLE
Metrics graphs: tooltip z-index lower than nav

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/snapcraft.io#1429]
### Expected behaviour
Tooltip should have z-index higher than nav.
### Steps to reproduce the problem
Hover on OS graph:
![image](https://user-images.githubusercontent.com/2741678/49800421-583d9d00-fd3f-11e8-945d-796480555dfa.png)

### Specs

- _URL:_
- _Operating system:_
- _Browser:_

**Comment by matthewpaulthomas** [comment]
[practices#144](https://github.com/canonical-webteam/practices/issues/144) is discussing standardizing on `z-index` values.

In the meantime, I’m not aware of any case where a Web page would want to layer anything on top of a tooltip. So a simple fix would be to set this one’s z-index to `5000` or something.

**Comment by therealjuan** [comment]
![image](https://user-images.githubusercontent.com/8167677/56210772-71888a00-604e-11e9-8889-0dec01dbbe6e.png)

As of Today, this is not happening anymore. Closing
