### ISSUE TITLE
Improve fsf warnings in lists

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#1439]
See https://github.com/canonical-websites/snapcraft.io/pull/1415#discussion_r241481426

There was logic in the template to hack styling - this should be improved in a more sensible way

**Comment by solazio** [comment]
@Lukewh how can this be improved? https://github.com/canonical-web-and-design/snapcraft.io/blob/master/templates/first-snap/build-and-test.html#L43
