### ISSUE TITLE
Store page suggestion: Auto show category contents on category switch

### ISSUE THREAD

**Issue by igorljubuncic** [canonical-web-and-design/snapcraft.io#1446]
When users switch category to search only in the category, only the category is changed in the drop down, but no search is done. The user then needs to type and click search.

Recommended/expected behavior:

Switching categories would automatically load the (top) content of that specific category and show below the search box.

![store-category-no-auto-switch](https://user-images.githubusercontent.com/43789966/49997949-e6f22a00-ff8a-11e8-9bcf-ac2a235de7cf.png)

**Comment by therealjuan** [comment]
Not relevant anymore
