### ISSUE TITLE
Revisions an promotion dropdown not closing when click on it 

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/snapcraft.io#1531]
# How to reproduce

- Click on the button for Revisions or promote:

![dropdown](https://user-images.githubusercontent.com/2707508/51684402-dd290100-1fe3-11e9-8954-be9f5c414e2a.png)

- Click again
- The dropdown is still there

# Excpected behaviour

It should close

**Comment by bartaz** [comment]
This dropdown is no more
