### ISSUE TITLE
More prominent "additional comments" on NPS landing page

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/snapcraft.io#1635]
The NPS emails have a low percentage of additional comments out of the 40 submissions so far. Can we either make the additional comments box visible by default, or explore other ways to increase written feedback paired with the NPS submission?

**Comment by Lukewh** [comment]
@evandandrea perhaps we should have a dedicated "thank you page" at this point, so we're not trying to cram a lot in a small notification?

**Comment by jkfran** [comment]
We are not sure if this is still relevant, please reopen if this is still an issue.
