### ISSUE TITLE
.svg icon rejected because it's recognized as text/plain instead of image/svg+xml

### ISSUE THREAD

**Issue by jbicha** [canonical-web-and-design/snapcraft.io#1643]
### Steps to reproduce the problem
0. Download https://gitlab.gnome.org/GNOME/hitori/blob/master/data/icons/scalable/org.gnome.Hitori.svg
1. On the snap listing page, click the icon in the top left.
2. Select the .svg icon you downloaded
3. Click Save on the listing page.

### What happens

A banner displays with:

```
The icon "org.gnome.Hitori.svg" to be of type "text/plain".
 Only "image/jpeg, image/png, image/svg+xml" are allowed.
```

The icon is left unchanged.

### Other Info
I was trying to update https://snapcraft.io/gnome-hitori/listing but the test case should work with any snap.

**Comment by danielmutis** [comment]
@solazio fixed this issue.
