### ISSUE TITLE
Snap names in dispute showing as owned names

### ISSUE THREAD

**Issue by jpmartinspt** [canonical-web-and-design/snapcraft.io#1652]
## Issue
When you register a name dispute, the name shows under owned names in your published snaps page while the dispute is still pending.

### Expected behaviour
In your published snaps page, when you register a name dispute you should be able to see it is pending, or not see anything at all and get e-mail feedback. Your owned snaps list should show only snaps you actually own.

### Steps to reproduce the problem
- Register a new dispute for a name you don't own
- Go to your published snaps page and it now shows you own the name, when it is actually a pending dispute.

See the screenshot bellow just after i submitted a dispute for the `cassandra` name
![dispute](https://user-images.githubusercontent.com/8145209/53806228-4c2f3900-3f44-11e9-9578-95855417e23c.png)

**Comment by cristinadresch** [comment]
Fixed
