### ISSUE TITLE
Landing page shows publisher username but snap pages show publisher display name

### ISSUE THREAD

**Issue by robert-ancell** [canonical-web-and-design/snapcraft.io#1656]
Both the landing page (https://snapcraft.io/store) and the snap pages (e.g. https://snapcraft.io/kcalc) show publisher information inconsistently. Currently the landing page uses the publisher username "kde" and the snap pages use the publisher display name "KDE". I would expect both pages to show the display name.

**Comment by Lukewh** [comment]
We should definitely use the full name for this. An example on the store currently is blender.
Store = blenderfoundation
Page = Blender Foundation (blenderfoundation)

Store should be "Blender Foundation"
