### ISSUE TITLE
Snap banner and banner icon upload no longer possible

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [canonical-web-and-design/snapcraft.io#1668]
The banner and banner icon upload functionality documented in [Getting ready for stable - doc - snapcraft.io](https://forum.snapcraft.io/t/getting-ready-for-stable/4305) no longer work due to the recently implemented screenshot restrictions.

### Steps to reproduce the problem
1. Create a 240x240px PNG image, name it as banner-icon.png
1. Upload it in the listing page via the screenshot upload form:

   > The screenshot "banner-icon.png" has dimensions "240x240". It needs to be at least "480x480" and at most "3840x2160". 

1. Create a 1218x240px PNG image, name it as banner.png
1. Upload it in the listing page via the screenshot upload form:

   > The screenshot "banner.png" has an aspect ratio of "203:40". It needs to be at least "1:2" and at most "2:1". 

The images used for issue reproduction are uploaded below:

![banner](https://user-images.githubusercontent.com/13408130/54099601-129f7780-43f5-11e9-91b4-0940224d4f94.png)
![banner-icon](https://user-images.githubusercontent.com/13408130/54099603-129f7780-43f5-11e9-9988-d799f200af51.png)

### Specs

- _URL:_ https://snapcraft.io/_snap_identifier_/listing
- _Operating system:_ Ubuntu 18.04 AMD64
- _Browser:_ Mozilla Firefox 65.0.1 from Ubuntu

**Comment by Lukewh** [comment]
While waiting for the store to allow these images again, I'll be working on the front-end.
It will be based on Jordan's initial design for banners [1] but with different messaging and slightly different UX to accommodate the banner-icon.

Once done we should have another epic for when we're ready to implement the new banner spec, that includes adding messaging to say the requirements will change.

[1] ![Screenshot_2019-03-14 Zeplin - Project.png](https://images.zenhubusercontent.com/59316f3551aa2c3057803f4b/65a9efb1-4309-45ac-ae0b-0d080732f063)

**Comment by Lukewh** [comment]
The store has re-enabled uploading. This has thrown up some edge cases the new front-end doesn't deal with so well. 

I'm going to keep this issue open to track that work but @Lin-Buo-Ren you should now be able to upload banners via the "media" section as before.
