### ISSUE TITLE
Add view by architecture in metrics

### ISSUE THREAD

**Issue by bekalshenoy** [canonical-web-and-design/snapcraft.io#1680]
Add a option to view or sort weakly active devices by architecture (32bit, 64bit) in metrics of snap application

**Comment by WebDrake** [comment]
This would be extremely useful to have.  I'm currently maintaining both i386 and amd64 versions of packages, and I have a strong suspicion that no one is using the i386 releases.  But without proof, it's difficult to justify dropping support ... ;-)

**Comment by Lukewh** [comment]
@WebDrake thanks for bumping this issue.
@bekalshenoy @WebDrake I've created an issue for the API to supply this information, I'll update this issue as things progress.

**Comment by WebDrake** [comment]
Thanks @Lukewh1  Any chance of an issue cross-ref?

**Comment by bartaz** [comment]
That's gonna be this one I think: 
https://bugs.launchpad.net/software-center-agent/+bug/1846689

**Comment by WebDrake** [comment]
Thanks @tbille for raising the priority of this issue again :-)  Quick question: is there any way for now to query the underlying API directly (as a workaround for package maintainers who want to check architecture usage)?

**Comment by tbille** [comment]
hey, you can now go on you metrics page and should have the selection for architectures too now. :smile: 

@WebDrake There is an API docs for the publisher section but it seems it is not documented: https://dashboard.snapcraft.io/docs/api/snap.html#fetch-metrics-for-snaps

In case you try to use it the metric is `weekly_installed_base_by_architecture`

I'll make sure to pass the message to the team that works on delivering this doc :)

**Comment by WebDrake** [comment]
@tbille that's great, thank you so much for implementing this!
