### ISSUE TITLE
No distinction between featured and not within categories

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/snapcraft.io#1719]
Pop quiz: which of these snaps are featured within the Development category?

![Screenshot_2019-03-20  Development — Linux software in the Snap Store ](https://user-images.githubusercontent.com/1523179/54673357-005ac300-4af2-11e9-8905-4e293e911189.png)

I believe it's been discussed before, but I cannot find an existing issue for it. We should visually highlight featured applications within a category, of which there are 20. Bonus points for styling the featured snap in position 1 differently.

**Comment by kwm14** [comment]
@evandandrea love a pop quiz 🤔 

I'll take a look at this 👍

**Comment by kwm14** [comment]
## Initial exploration
The first pass at exploring layouts/styles for the no.1 snap, featured snaps and all snaps inside a category.

### 001
![s io-featured-category-001](https://user-images.githubusercontent.com/17748020/55090674-6e315c80-50a7-11e9-8b95-a5a5450f861c.png)

### 002
![s io-featured-category-002](https://user-images.githubusercontent.com/17748020/55090676-6e315c80-50a7-11e9-806e-5a02f3c66320.png)

### 003
![s io-featured-category-005](https://user-images.githubusercontent.com/17748020/55090715-7be6e200-50a7-11e9-89a2-4b957d38b35f.png)

### 004
![s io-featured-category-006](https://user-images.githubusercontent.com/17748020/55090716-7c7f7880-50a7-11e9-82e5-19baada7c101.png)

### 005
![s io-featured-category-007](https://user-images.githubusercontent.com/17748020/55090717-7c7f7880-50a7-11e9-870f-ac0eb85e4277.png)

### 006
![s io-featured-category-008](https://user-images.githubusercontent.com/17748020/55090718-7c7f7880-50a7-11e9-91e2-e6cbc7c19212.png)

### 007
![s io-featured-category-009](https://user-images.githubusercontent.com/17748020/55090719-7c7f7880-50a7-11e9-8993-2d6f315b7f10.png)

**Comment by kwm14** [comment]
## Design review
_with @spencerbygraves_ 

- 004, 005 & 006 preferred
- Horiztontal layout looks good
- How can we avoid widow snaps based on uneven numbers?

**Comment by kwm14** [comment]
## Wall review
_with @evandandrea_ 

- 003 preferred design concept
- The added description gives it a different feel rather than looking the same as other snaps (icon, name, author)
- Can we add 5 snaps in a row for 'All snaps'
- Full-width No.1 snap looks good
- To avoid widow snaps/odd numbers in a row we can change Top 20 snaps to a different number to cater 👍

**Comment by kwm14** [comment]
## Wall review
_with @therealjuan_ 

- 003 preferred design concept too 👍 
- No.1 snap: Increase height to give a better hierarchy of content as you scroll down the page
- No.1 snap: Can we have a custom featured image for users to upload, if they don't have an image we can use your design as a template
- Would be good to see a 3-col layout rather than 4-col
- New layout could be 1, 3, 5
- Remove title and paragraph we don't need it
- How would this look here https://snapcraft.io/store where we surface all the categories?

**Comment by kwm14** [comment]
## Further exploration
- Taking all feedback into consideration
- Updated template below

### 008
![s io-featured-category-009](https://user-images.githubusercontent.com/17748020/55418681-0e392b00-556b-11e9-9fac-fce10bfdf169.png)

**Comment by kwm14** [comment]
## No1 featured snap
- In regards to the no1 featured snap, I explored a few layout options
- The idea being our default feature banner would pick a color from the user's icon and update the background
- Alternatively, users can upload a custom background image as suggested by @therealjuan 

### 001 Default
![s io-featured-snap-v1](https://user-images.githubusercontent.com/17748020/55419009-cb2b8780-556b-11e9-87b5-e0b82539c7f1.png)

### 002 Default
![s io-featured-snap-v2](https://user-images.githubusercontent.com/17748020/55419010-cb2b8780-556b-11e9-8ab8-3d8f4800ae2d.png)

### 003 Default
![s io-featured-snap-v3-default](https://user-images.githubusercontent.com/17748020/55419011-cb2b8780-556b-11e9-8d72-dfba92f10800.png)

### 003 Custom
![s io-featured-snap-v3](https://user-images.githubusercontent.com/17748020/55419283-50af3780-556c-11e9-9187-0d3952f39849.png)

### 004 Default
![s io-featured-snap-v5](https://user-images.githubusercontent.com/17748020/55419048-e1394800-556b-11e9-94fb-948a77de735b.png)

### 004 Custom
![s io-featured-snap-v5-custom](https://user-images.githubusercontent.com/17748020/55419167-15ad0400-556c-11e9-89fb-dda1def802f3.png)

**Comment by kwm14** [comment]
## Design review
_with @spencerbygraves_ 

- 001 & 003 preferred design concepts
- I like how they are different from the featured snap listings
- I wonder how we control custom images being uploaded and the legibility of text
- Might be worth testing on snaps without great imagery to see if the solution works

**Comment by kwm14** [comment]
> @therealjuan comment:
> How would this look here https://snapcraft.io/store where we surface all the categories?

In reference to the @therealjuan comment above on how the design may look on the storefront 😉 

![s io-store-home-001](https://user-images.githubusercontent.com/17748020/55492013-6be27b80-562e-11e9-8801-b1a03eff0856.png)

**Comment by therealjuan** [comment]
It might be good to have a discussion as we are going to allow publishers to upload featured banners but obviously, we have control over the platform but all these elements take for granted that there is going to be no banners from publishers on the snaps.

**Comment by kwm14** [comment]
## Desk discussion
with @therealjuan 
- +1 updated **008** layout
- We should let the publisher create their own artwork for 'Featured snap' banner
- Mock-up 3 examples and place into a new template
   - Spotify
   - Slack
  - Visual Studio Code
- Going forward it will be good to have a Snapcraft banner template, for publishers that may not have design resource
  - Supply SVG downloadable templates (GitHub)
  - Various screen sizes
  - Guidance of use and assets needed
  - Promote this on snap listing page

**Comment by kwm14** [comment]
## Publisher feature banner
- Custom featured banners of what publishers could upload
- I've mocked up 3 examples for 3 categories
- @therealjuan @evandandrea 

![s io-featured-development-001](https://user-images.githubusercontent.com/17748020/55628253-23e76400-57a8-11e9-80fb-35655add7fcd.png)

![s io-featured-social-002](https://user-images.githubusercontent.com/17748020/55628262-277aeb00-57a8-11e9-8324-4880da090c3f.png)

![s io-featured-music video-003](https://user-images.githubusercontent.com/17748020/55628279-382b6100-57a8-11e9-98f0-ce55e58e7018.png)

**Comment by therealjuan** [comment]
## Desk design ping pong @kwm14 and @therealjuan 

We discussed the idea to have featured snaps and then highlight some of the featured snaps in the homepage with banners, if there are no featured banners we can fallback to a 3 column option

![Store homepage](https://user-images.githubusercontent.com/8167677/55633593-a24a0300-57b4-11e9-9b08-6e10e305e5a4.png)

On the category page, we can display the featured snaps with their banners and then the rest of snaps in a grid of 3 columns:

![Category page](https://user-images.githubusercontent.com/8167677/55633594-a24a0300-57b4-11e9-9e55-5629d9484a25.png)

**Comment by Lukewh** [comment]
@therealjuan @kwm14 what's the status of this issue - what's the outcome? Is anything ready to implement?

**Comment by kwm14** [comment]
@Lukewh we plan to review designs today and move the desried design to a build issue, for yourself or @bartaz to implement 👍 💯

**Comment by kwm14** [comment]
## Review
_with @therealjuan_ 

Quick updates to store and categories pages.

### Store
- Use existing header seen on https://snapcraft.io/store
- Keep featured banners (1 or 3)
- List top 9 snaps below it
- Add 'See more' link or button

### Categories
- Keep existing design
- Add top 9 snaps below featured snaps
- New design under 'All snaps' horizontal list of the snaps

**Comment by kwm14** [comment]
## Final version
Updated both pages based on feedback and further reviews at the design wall.

### /store
- The first phase to keep current hero banner
- 19.10 implement new features hero slider 💯 

![s io-store-homepage](https://user-images.githubusercontent.com/17748020/56196165-37a78b80-602e-11e9-8e53-60bf7e4d69b9.png)

### /category
- Pull in Top10 or Top12 snaps from store homepage template
- Infinite scroll all other snaps under category

![s io-featured-category](https://user-images.githubusercontent.com/17748020/56196284-76d5dc80-602e-11e9-894b-0beb135b07bd.png)

**Comment by kwm14** [comment]
## Review
with @evandandrea @therealjuan @Lukewh 

- Bring back titles as it will be more clear that curation is a thing
  - Featured 'social' snaps
  - All 'social' snaps
- Remove 'by' from snap author line
- The first phase auto-generate banners for snaps based on a previous design
  - Snap icon, snap description and color pick icon to generate a background color
  - @Lukewh to build a demo for @kwm14 @therealjuan to review and test which color setting works best across a range of selected snaps

**Comment by kwm14** [comment]
## Final final version
Updated based on feedback from review meeting earlier.

### /category with banner
![s io-featured-011](https://user-images.githubusercontent.com/17748020/56216063-a39ee980-6058-11e9-9f88-ce362b5aacfb.png)

### /category with generated banner
![s io-featured-011a](https://user-images.githubusercontent.com/17748020/56216079-abf72480-6058-11e9-9847-d94c1ec36112.png)

**Comment by therealjuan** [comment]
Now is too late, you invoked `the ghost of the never ending design version`
