### ISSUE TITLE
Bitwarden does not run!

### ISSUE THREAD

**Issue by dlalinsp** [canonical-web-and-design/snapcraft.io#1759]
#### My Experience
I get this message when I try to install Bitwarden (GUI). It runs perfectly in the same session I install it in. However, when the computer is restarted, Bitwarden doesn't run after I execute it by clicking. My DE is **Mate 1.20.4**.

_Warning: /snap/bin was not found in your $PATH. If you've not restarted your
         session since you installed snapd, try doing that. Please see
         https://forum.snapcraft.io/t/9469 for more details._

#### **Snap Version Output**
~ $ snap version
snap    2.38
snapd   2.38
series  16
solus   4.0
kernel  4.20.16-112.current
#### **Os-Release Contents**
NAME="Solus"
VERSION="4.0"
ID="solus"
VERSION_CODENAME=fortitude
VERSION_ID="4.0"
PRETTY_NAME="Solus 4.0 Fortitude"
ANSI_COLOR="1;34"
HOME_URL="https://getsol.us"
SUPPORT_URL="https://getsol.us/articles/contributing/getting-involved/en/"
BUG_REPORT_URL="https://dev.getsol.us/"
#### **Shell Version**
~ $ bash --version
GNU bash, version 4.4.19(1)-release (x86_64-solus-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
####

**Comment by Lin-Buo-Ren** [comment]
This site only deals with problems regarding the <https://snapcraft.io> website, for support of each snap please refer the contacts link under each snap's listing page:

<https://snapcraft.io/bitwarden>
