### ISSUE TITLE
FSF improvements - create snapcraft.yaml interactive viewer

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/snapcraft.io#1785]
<img width="616" alt="Screenshot 2019-04-05 at 08 39 11" src="https://user-images.githubusercontent.com/83575/55608232-52e8e000-577e-11e9-86f3-281b880536b6.png">

**Comment by hughesjordan** [comment]
Should be something like this:
https://hvkxwi.axshare.com/#g=1&p=home
