### ISSUE TITLE
Default youtube video quality is poor

### ISSUE THREAD

**Issue by thomasnordquist** [canonical-web-and-design/snapcraft.io#1810]
Default video quality is 480p, even though the youtube videos support better quality.
The presentation of an app is really impaired when the presentation media looks horrible.

With the current video quality, apps only displaying screenshots instead of a video look/feel way better.

### Expected behavior
Good video quality should be selected when playing youtube videos.

#### Visit:
- https://snapcraft.io/code
- https://snapcraft.io/mqtt-explorer

#### Videos with no text / do not suffer as much from the bad quality
- https://snapcraft.io/postman

### Specs

- _URL:_ https://snapcraft.io/code
- _Operating system:_ OSX
- _Browser:_ Chrome
- _Screen_: 15" (WQHD) / 24" (1080p) (doesn't really matter with a 480p video)

**Comment by bartaz** [comment]
I'm not sure if we have much control over embedded YouTube quality.
I believe YouTube adjusts it automatically based on network speed it detects.

For me (landline broadband network) I get HD (1080p) automatically when I load pages you mentioned.

<img width="1071" alt="Screenshot 2019-04-12 at 12 05 59" src="https://user-images.githubusercontent.com/83575/56029819-96fa5880-5d1b-11e9-9df2-f56ef204a05e.png">

**Comment by thomasnordquist** [comment]
Internet connection speed is not the issue....
<img width="558" alt="Bildschirmfoto 2019-04-12 um 14 06 58" src="https://user-images.githubusercontent.com/7721625/56036093-42130e00-5d2c-11e9-8634-57bb8f3d8df3.png">

**Comment by bartaz** [comment]
> Internet connection speed is not the issue....
@thomasnordquist Now I'm jealous. ;)

I gave it a quick look and it seems there is no parameter in the API we can use to enforce the quality.
It's youtube that decides that on factors only they know about.

Could it be that you changed the quality on youtube earlier, so they may store your account settings for lower quality? If you set quality to 'Auto' (in the embedded video or anywhere in youtube) does it solve the issue after reloading the page or do videos still play in low quality?

**Comment by thomasnordquist** [comment]
If there is no official API then there seems nothing left to do.
In incognito mode, I currently get 720p for the MQTT Explorer and 1080p for VSCode in auto mode.

In the past 480p was very very repeatable.
I'd guess we should close the issue.

There seem to be [undocumented](https://communities.bmc.com/docs/DOC-21972) quality settings, but enforcing those could also reduce the user experience.

I also might have confused 480p with 1080p because youtube seems to have a "soft-start", they start streaming in a lower quality and then upgrade the stream. If you see the VSCode app-page, it'll start with almost unreadable text, and then become very clear.

**Comment by bartaz** [comment]
Closing this for now as it doesn't seem like we have much control over youtube quality.

Thanks for taking time to report this.
