### ISSUE TITLE
snapcraft.io/account on mobile

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/snapcraft.io#1820]
### Expected behaviour

snapcraft.io/account renders cleanly when opened on a mobile device (Chrome, iOS).

### Steps to reproduce the problem

Visit snapcraft.io/account in Chrome on iOS.

![BB4607B4-D309-4D21-9E7F-9C4E9C1D6306](https://user-images.githubusercontent.com/1523179/56124273-32830780-5f6e-11e9-9759-9cb79a9815ab.png)

**Comment by matthewpaulthomas** [comment]
This issue is half of #1352, which also covers the Listing page.

It might save time to fix #1865 at the same time, since they both involve smooshed tables.

**Comment by solazio** [comment]
This is now fixed, closing.

![image.png](https://images.zenhubusercontent.com/5cb4608f97df763a9090bdec/8f18e5ef-0445-47ca-a07d-48c615e912eb)
