### ISSUE TITLE
Time to load blog is unacceptable

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/snapcraft.io#1822]
### Expected behaviour
https://snapcraft.io/blog loads before [an average human blinks ](https://brightside.me/wonder-curiosities/unbelievable-things-that-happen-in-the-world-every-5-seconds-175555/)

### Steps to reproduce the problem
* Load https://snapcraft.io/blog
* Observe how long it takes to load
* Note that it's > 5s

### Specs

- _URL:_ https://snapcraft.io/blog
- _Operating system:_ Ubuntu 19.04 Disco Dingo
- _Browser:_ Firefox 66.0.3

Similar to #1067

**Comment by matthewpaulthomas** [comment]
Now that #1067 is much improved (total size is down to 1.08 MB), by far the most time (80~90%) is just waiting for the HTML to be returned:

![snapcraft io#1022-performance](https://user-images.githubusercontent.com/19801137/56191763-e5ae3800-6024-11e9-8c58-59b25972e622.png)

**Comment by bartaz** [comment]
As far as I remember that's a "known" issue with blog API being very slow.
But it's true that such load times are unacceptable.

**Comment by sparkiegeek** [comment]
Right, blog API can be slow, but the content is hardly fast changing. I would think it could easily be cached, a static page rendered and served very quickly (even if it caches it for an hour, a new blog post going out it's not the end of the world if it doesn't show up for 1h on `/blog`)

**Comment by cristinadresch** [comment]
Thiswork has been done thanks @jpmartinspt
