### ISSUE TITLE
Show all channels for node's embeddable card doesn't

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/snapcraft.io#1825]
### Expected behaviour

All of node's channels are shown in the card

### Steps to reproduce the problem

Create an embeddable card for node, and turn on channels (or visit
https://snapcraft.io/node/embedded?button=black&channels=true )

### Specs

- _URL:_ https://snapcraft.io/node/embedded?button=black&channels=true
- _Operating system:_ Ubuntu 19.04 Disco Dingo
- _Browser:_ Firefox 66.0.3

**Comment by bartaz** [comment]
Node in its default track (10) is released only to stable, all other channels in this track are empty:

<img width="1086" alt="Screenshot 2019-04-16 at 10 23 48" src="https://user-images.githubusercontent.com/83575/56193817-d1bd0300-6031-11e9-8aed-115d04ceeb1c.png">

What is the expected result? Would you like to see all the channels of all tracks?

**Comment by sparkiegeek** [comment]
> What is the expected result? Would you like to see all the channels of all tracks?

There's no such thing as "all the channels of all tracks", all channels means all risk levels in all tracks. Tracks don't have channels, they have risk levels, and each channel is in a track and has a risk level.
