### ISSUE TITLE
Featured posts

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/snapcraft.io#1832]
## Current featured posts
Reference when designing: https://github.com/canonical-web-and-design/meeting-notes/issues/384

<img width="1439" alt="Screenshot 2019-04-24 at 15 23 42" src="https://user-images.githubusercontent.com/17748020/56667086-0faace80-66a5-11e9-9148-328f050b6798.png">

**Comment by kwm14** [comment]
## First exploration
- Add slanted header for consistency
- Alternate featured posts layouts
- @therealjuan @evandandrea let me know your thoughts 😉 

### 001
![001-featured-posts](https://user-images.githubusercontent.com/17748020/56667178-408b0380-66a5-11e9-82f7-c0206a3b10eb.png)

### 002
![002-featured-posts](https://user-images.githubusercontent.com/17748020/56667179-408b0380-66a5-11e9-8c0c-492cf495c55a.png)

### 003
![003-featured-posts](https://user-images.githubusercontent.com/17748020/56667180-408b0380-66a5-11e9-8cc7-506a0b7d7ef1.png)

### 004
![004-featured-posts](https://user-images.githubusercontent.com/17748020/56667181-408b0380-66a5-11e9-81e5-c284c2907d60.png)

**Comment by therealjuan** [comment]
My vote goes to 003 with 2 featured posts but the single item per row of 004 has some appeal 👍

**Comment by kwm14** [comment]
## Design review
Full meeting notes can be found here: https://github.com/canonical-web-and-design/meeting-notes/issues/386

High-level takeaways below:

- Keep blog title and introduction on featured
- Make the author visible
- Add date to featured
- 001 and 003 design preferred
- Do we need a page title? Can we just start with the featured blog posts...
- Try the lighter green in the Suru fold, so we have a primary and secondary Suru fold for pages
- Flip images and text
- Not sure on the 'Read more' button
- Blue links seem better to use other than buttons

**Comment by kwm14** [comment]
## Updated explorations
Taking feedback into consideration I've focused on the 2 explorations preferred.

- Explored using `#e5eeee` as the Suru accent background color, it didn't work well with blue links for the blog post titles so reverted back
- Moved images to the right to convey a stronger keyline for the blog post copy
- Once we add our new 'Topics' section below the featured posts it will provide a better divide 😉 
- @therealjuan @spencerbygraves ready for re-review

### 005
![006-featured-posts](https://user-images.githubusercontent.com/17748020/56749930-9aa9c880-677a-11e9-898c-d67e232327ac.png)

### 006
![007-featured-posts](https://user-images.githubusercontent.com/17748020/56750034-ccbb2a80-677a-11e9-8b7e-7088ba3f36a1.png)

**Comment by therealjuan** [comment]
LGTM!

**Comment by spencerbygraves** [comment]
@kwm14 I prefer 006 if pushed. A smaller Featured posts title might be better than repeating Blog, as on blog.ubuntu.com.

**Comment by kwm14** [comment]
@spencerbygraves great thanks. The title is currently a placeholder until decided by the team 😄

**Comment by kwm14** [comment]
## Design to be built
006 was the design chosen to be built. Ready to go 👍 

![007-featured-posts](https://user-images.githubusercontent.com/17748020/56750034-ccbb2a80-677a-11e9-8b7e-7088ba3f36a1.png)
