### ISSUE TITLE
Topics section

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/snapcraft.io#1833]
## Example
Heroku have used their topic section well 👍  

<img width="1438" alt="Screenshot 2019-04-25 at 15 28 22" src="https://user-images.githubusercontent.com/17748020/56743628-d50d6880-676e-11e9-9905-2c2287b50cad.png">

**Comment by kwm14** [comment]
_@therealjuan @evandandrea @Lukewh_ 
Do you know what topics we will be surfacing for https://snapcraft.io/blog?

**Comment by kwm14** [comment]
> _@therealjuan @evandandrea @Lukewh_
> 
> Do you know what topics we will be surfacing for https://snapcraft.io/blog?

Any initial thoughts/buzz words on my comment above?

If they're still undecided, for now, I can just add placeholder headings in `Topic 1`, `Topic 2` etc..

**Comment by therealjuan** [comment]
We don't have as of yet as we might need to agree but we can go with these as samples:

`Latest news | Articles | Snaps collections | Guides`

**Comment by kwm14** [comment]
## First exploration
- Various styles using existing components
- Taking influence from Ubuntu and Juju

### 001
![001-topics-section](https://user-images.githubusercontent.com/17748020/57014616-df18e680-6c08-11e9-8d92-4c1779700234.png)

### 002
![002-topics-section](https://user-images.githubusercontent.com/17748020/57014618-df18e680-6c08-11e9-98f4-62aa3b5959c7.png)

### 003
![003-topics-section](https://user-images.githubusercontent.com/17748020/57014619-df18e680-6c08-11e9-9c85-6932d7a381d5.png)

### 004
![004-topics-section](https://user-images.githubusercontent.com/17748020/57014620-dfb17d00-6c08-11e9-82e6-560c3a75d4f3.png)

### 005
![005-topics-section](https://user-images.githubusercontent.com/17748020/57014623-dfb17d00-6c08-11e9-8c08-e324ab707680.png)

**Comment by spencerbygraves** [comment]
@kwm14 002 looks good, thanks. You might want the selected colour to be orange.

**Comment by kwm14** [comment]
Spoke with @therealjuan yesterday and he was happy with either **001** or **002**, future request to have icons alongside the topics 👍 

Will update design based on @spencerbygraves feedback.

**Comment by kwm14** [comment]
## Design to be built
Ready to go 👍 

![006-topics-section](https://user-images.githubusercontent.com/17748020/57128624-f3392100-6d8b-11e9-9a1f-78fc20baa0a3.png)
