### ISSUE TITLE
Related posts

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/snapcraft.io#1834]
Reference when designing: https://github.com/canonical-web-and-design/meeting-notes/issues/384

Current styling on snap details page.

<img width="1016" alt="Screenshot 2019-04-29 at 14 58 38" src="https://user-images.githubusercontent.com/17748020/56901148-5d517d80-6a8f-11e9-9009-364118eed5d8.png">

Currently, we don't have related posts on posts on our blog. We use this pattern on https://blog.ubuntu.com/

<img width="1440" alt="Screenshot 2019-04-29 at 11 46 46" src="https://user-images.githubusercontent.com/17748020/56891506-9c260a00-6a74-11e9-8579-b919afffa43d.png">

**Comment by kwm14** [comment]
## First exploration
- Couple of variations to display related posts at the bottom of a blog post
- @therealjuan @spencerbygraves ready for the first review 😉 

### 001
- An existing pattern we use on blog.ubuntu.com

![001-related-posts](https://user-images.githubusercontent.com/17748020/56905602-6abf3580-6a98-11e9-93cc-e683843443b2.png)

### 002
- No dividing lines
- With author and date

![002-related-posts](https://user-images.githubusercontent.com/17748020/56905927-24b6a180-6a99-11e9-9110-e64cc480acb0.png)

### 003
- Card layout to make them stand out more when you've read the post

![003-related-posts](https://user-images.githubusercontent.com/17748020/56905605-6b57cc00-6a98-11e9-9f26-77ce785004a3.png)

### 004
- Image and blog title

![004-related-posts](https://user-images.githubusercontent.com/17748020/56905606-6b57cc00-6a98-11e9-98d3-5939c7bf2bc0.png)

**Comment by evandandrea** [comment]
I very much prefer 004, as the images form a nice break after reading paragraphs of text.

**Comment by therealjuan** [comment]
**zero zero four** looks great!

**Comment by spencerbygraves** [comment]
Looks like 004 if favourite, would they need author and date?

**Comment by therealjuan** [comment]
It will be good to include profile_pic, author name and date in a one-liner:
`[ PIC ] Someone Surname – 18 Nov 2018`

**Comment by kwm14** [comment]
The votes are in 👍 thanks all.

@spencerbygraves yeah sure I can try that. We've used the title and author on the [new layout](https://github.com/canonical-web-and-design/snapcraft.io/issues/1832#issuecomment-487506329) for featured and all posts, for consisntecy, it would be good to add that back 😄

**Comment by kwm14** [comment]
## Updated exploration
- Adding author and date to design _004_
- Reduce spacing

![005-related-posts ](https://user-images.githubusercontent.com/17748020/56951165-056a5380-6b2f-11e9-8b24-5e9b340e94e5.png)

**Comment by spencerbygraves** [comment]
@kwm14 looks good, thanks.

**Comment by kwm14** [comment]
## Design to be built
_004_ was the design chosen to be built. Ready to go 👍

![005-related-posts ](https://user-images.githubusercontent.com/17748020/56951165-056a5380-6b2f-11e9-8b24-5e9b340e94e5.png)
