### ISSUE TITLE
Subscribe newsletter

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/snapcraft.io#1835]
## Current signup
Reference when designing: https://github.com/canonical-web-and-design/meeting-notes/issues/384

<img width="1439" alt="Screenshot 2019-04-24 at 15 23 42" src="https://user-images.githubusercontent.com/17748020/56667086-0faace80-66a5-11e9-9148-328f050b6798.png">

**Comment by kwm14** [comment]
## First exploration
- Add newsletter to footer so it's visible across all site pages rather than just being displayed on our blog page [here](https://snapcraft.io/blog)
- @therealjuan @evandandrea let me know your thoughts 😉 

### 001
![001-subscribe-newsletter](https://user-images.githubusercontent.com/17748020/56725139-3409b800-6744-11e9-89d2-8ff033322770.png)

### 002
![002-subscribe-newsletter](https://user-images.githubusercontent.com/17748020/56725140-3409b800-6744-11e9-9a84-916000c7245e.png)

### 003
![003-subscribe-newsletter](https://user-images.githubusercontent.com/17748020/56725141-3409b800-6744-11e9-8135-cdd044e427ea.png)

### 004
![004-subscribe-newsletter](https://user-images.githubusercontent.com/17748020/56725143-3409b800-6744-11e9-9731-6a8abb649ec9.png)

**Comment by kwm14** [comment]
## Design review
Full meeting notes can be found here: https://github.com/canonical-web-and-design/meeting-notes/issues/386

- Can we hide the subscribe form? Keep it simple with a button or link that opens the form
- Links should live together, Legal should live together, Sign-up should live together, Social should live together
- 'We're hiring!' should be 'Careers' so it's consistent with the rest of our suite of sites
- 001 layout preferred 
- Good use of white space
- Keep Vanilla 'Back to top' link

**Comment by kwm14** [comment]
## Updated exploration
Taking feedback above into consideration for a design update.
- @therealjuan @spencerbygraves ready for review

### 005
![005-subscribe-newsletter](https://user-images.githubusercontent.com/17748020/56750772-66370c00-677c-11e9-9a8b-d349a61a1b85.png)

**Comment by therealjuan** [comment]
We can probably get away with no check-box and privacy notice message and...

Instead of `Newsletter signup / Email *` in two lines use a single field `Get new articles on your inbox`

**Comment by spencerbygraves** [comment]
@kwm14 looks good, thanks.

**Comment by kwm14** [comment]
## Updated exploration
- @therealjuan I've updated based on your comments above
- Moved social to the right so that the footer is more balanced
- Ready for re-review 😉 

### 006
![006-subscribe-newsletter](https://user-images.githubusercontent.com/17748020/56815058-52e97680-6838-11e9-9757-24121f5639ee.png)

**Comment by therealjuan** [comment]
LGTM

**Comment by evandandrea** [comment]
👍 on 006, particularly now that it's slimmed down to just "get new articles on your inbox." However, shouldn't that be _in_ your inbox?

**Comment by kwm14** [comment]
@evandandrea good spot. I will update 😉

**Comment by kwm14** [comment]
## Design to be built
_006_ was the design chosen to be built. Ready to go 👍

![006-subscribe-newsletter](https://user-images.githubusercontent.com/17748020/56889804-5f0b4900-6a6f-11e9-8ca9-5a7ad182e605.png)
