### ISSUE TITLE
Post series

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/snapcraft.io#1836]
## Current series
Reference when designing: https://github.com/canonical-web-and-design/meeting-notes/issues/384

<img width="1436" alt="Screenshot 2019-04-24 at 15 32 14" src="https://user-images.githubusercontent.com/17748020/56667697-361d3980-66a6-11e9-9b24-0a5795f6f2a8.png">

**Comment by kwm14** [comment]
## First exploration
- The goal of the update to just improve visual styling
- Using existing components and influence from https://tutorials.ubuntu.com/tutorial/wayland-kiosk#0
- @spencerbygraves ready for the first review

### 001
![001-post-series](https://user-images.githubusercontent.com/17748020/57138907-c6950180-6dab-11e9-8617-2a1ad2ea4d52.png)

### 002
![002-post-series](https://user-images.githubusercontent.com/17748020/57138908-c6950180-6dab-11e9-9909-f976703a27d3.png)

### 003
![003-post-series](https://user-images.githubusercontent.com/17748020/57139052-1f649a00-6dac-11e9-988a-2aba65dfb065.png)

### 004
![004-post-series](https://user-images.githubusercontent.com/17748020/57138910-c72d9800-6dab-11e9-8a7a-0ad3070a0a34.png)

**Comment by spencerbygraves** [comment]
@kwm14 001 looks like a good update, with the addition of numbers and better spacing.

**Comment by kwm14** [comment]
## Design to be built
_001_ was the design chosen to be built. Ready to go 👍

![001-post-series](https://user-images.githubusercontent.com/17748020/57138907-c6950180-6dab-11e9-8617-2a1ad2ea4d52.png)
