### ISSUE TITLE
'Contact Canonical' button provides an invalid email address

### ISSUE THREAD

**Issue by kurtwheeler** [canonical-web-and-design/snapcraft.io#1846]
I wanted to report an issue with https://snapcraft.io/docker but it did not fit into either of the categories that the 'Report this app' button offered, so I decided to use the 'Contact Canonical' button. It was an email link which opened up my email client, I wrote an email, and then sent it.

### Expected behaviour

The expected behavior is that my email would go to someone. Instead I received a response to it:
```
[snapcraft.io] Email issue -- Unknown To: Address

We’re sorry, but your email message to [“snappy-devel@lists.ubuntu.com”] (titled Docker via snap install) didn’t work.

None of the destination email addresses are recognized, or the Message-ID header in the email has been modified. Please make sure that you are sending to the correct email address provided by staff.
```

### Steps to reproduce the problem

Go to https://snapcraft.io/docker, click 'Contact Canonical', and then write an email.

### Specs

- _URL:_ https://snapcraft.io/docker
- _Operating system:_ Ubuntu
- _Browser:_ Chrome

**Comment by tbille** [comment]
This snap is not the only one that is impacted by this wrong contact.
We are investigating which one are linking to this email adress and updating it.
Thanks for opening this issue (a while ago now :) )

**Comment by tbille** [comment]
Took a while but this is fixed now.
Thanks for reporting this issue :smile:
