### ISSUE TITLE
Display full channel name for "by channel" metrics

### ISSUE THREAD

**Issue by fossfreedom** [canonical-web-and-design/snapcraft.io#1848]
### Expected behaviour

By channel metric should be able to distinguish what each colour represents through the popup on hover

### Steps to reproduce the problem

Use any seeded Snap (gnome-calculator etc) that has the convention "stable/ubuntu-version" - on hover you cannot distinguish the name due to the ellipsis.

Raised from https://forum.snapcraft.io/t/by-channel-metrics-popup-left-ellipsize-not-right/11065

### Specs

- Windows 7
- Firefox

![image](https://user-images.githubusercontent.com/996240/56584744-4f55b580-65d4-11e9-90bd-7d17ef4b3c78.png)

**Comment by RCMainak** [comment]
I would like to start working on this issue.
