### ISSUE TITLE
HTML entities are wrongly escaped when wrapped in backtick <code> markup

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [canonical-web-and-design/snapcraft.io#1853]
### Steps to reproduce the problem
1. Add the following content to the snap description:
  
    ```
    `<text>`
    ```

1. Check out the updated snap listing page

### Expected behaviour
`<text>` is appeared in the description

### Current behaviour
`&lt;text&gt;` is appeared in the description

### Specs
- _URL:_ https://snapcraft.io/_snap_identifier_/listing
- _Operating system:_ Ubuntu 18.04 AMD64
- _Browser:_ Mozilla Firefox 66.0.3 from Ubuntu archive

**Comment by tbille** [comment]
It seems to be fixed now.
