### ISSUE TITLE
The docs site's search result page returns 500: Server error

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [canonical-web-and-design/snapcraft.io#1858]
### Steps to reproduce the problem
1. Browse <https://docs.snapcraft.io/search?q=test>

### Expected behaviour
Search working

### Current behaviour
The page returns `500: Server error: Something's gone wrong, try reloading.`

### Specs

- _URL:_ <https://docs.snapcraft.io/search?q=test>
- _Operating system:_ Ubuntu 18.04
- _Browser:_ Mozilla Firefox 66.0.3

**Comment by cristinadresch** [comment]
this was fixed, thanks for the report.
