### ISSUE TITLE
Invisibly inconsistent vendor logo behaviour on front page

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/snapcraft.io#1860]
On the snapcraft.io front page, “Official snaps from major publishers” has six vendor logos. Without trying each one in turn, there is no way to tell that two of the six are clickable, KDE and Jetbrains.
![screenshot-snapcraft io-2019 04 25-16-55-34](https://user-images.githubusercontent.com/19801137/56750166-173ca700-677b-11e9-9e94-b0529d61cbd6.png)

Further down the same page, the testimonials section has three vendor logos. Without trying each one in turn, there is no way to tell that one of the three is clickable, Jetbrains.
![Screenshot from 2019-04-25 16:56:51](https://user-images.githubusercontent.com/19801137/56750272-4b17cc80-677b-11e9-9f28-b9b2e28f4e9c.png)

As a final bizarre twist, the two Jetbrains logos, differing only in size, link to different places.

The first-snap flow “What operating system” step gets this right: two of the three options are clickable, but the option you can’t choose has multiple signs of this: (a) a grey icon, (b) a grey label, and (c) the text “Coming soon”.
![screenshot-snapcraft io-2019 04 25-16-53-27](https://user-images.githubusercontent.com/19801137/56750079-eeb4ad00-677a-11e9-96fa-a091da022a47.png)

What should happen:
- none of the vendor logos should be clickable, or
- all of the vendor logos should be clickable and have consistent destinations, or
- the clickable ones should be visibly different and have consistent destinations.

**Comment by therealjuan** [comment]
Here is a proposal fix for the time being: https://github.com/canonical-web-and-design/snapcraft.io/pull/1862

Ideally, we would like to have a link to all publisher pages but in the meantime redirecting users from the homepage to relevant snaps seems like a quick fix for now until we are able to gather all content and have the right conversations with publishers.
