### ISSUE TITLE
Channel doesn't look great on small screens

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/snapcraft.io#1865]
On small screens when creating an embeddable with channel enables it doesn't look great.

**Comment by anthonydillon** [comment]
![Screenshot_20190428-104553__01](https://user-images.githubusercontent.com/1413534/56862467-23a34880-69a3-11e9-87fc-f23d595d1ae8.jpg)

**Comment by Lukewh** [comment]
Semi-related to https://github.com/canonical-web-and-design/snapcraft.io/issues/1865 - long strings in tables

**Comment by solazio** [comment]
This has been fixed in a previous PR. Closing
![image](https://user-images.githubusercontent.com/40214246/72796429-35b2ce80-3c37-11ea-9667-3ab3b8bd7137.png)
