### ISSUE TITLE
Error rendering releases page for some snaps

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/snapcraft.io#1879]
TypeError: "e is undefined"
    Ze releasesState.js:19
    t releasesController.js:38
    React 15
    qt release.js:16
    <anonymous> (index):321
raven.min.js:2:1243
    b raven.min.js:2
    React 17
    qt release.js:16
    <anonymous> (index):321
TypeError: e is undefined[Learn More] releasesState.js:19:2
    Ze releasesState.js:19
    t releasesController.js:38
    React 15
    qt release.js:16
    <anonymous> (index):321

### Expected behaviour
A releases page

### Steps to reproduce the problem
https://snapcraft.io/charm/releases

### Specs

- _URL:_ https://snapcraft.io/charm/releases
- _Operating system:_ Ubuntu 19.04 Disco Dingo
- _Browser:_ Firefox 66.0.3

**Comment by bartaz** [comment]
Got to underlying error (possibly coming from API?):
`"RelatedObjectDoesNotExist: ClickPackageUpload has no extra_fields."`

**Comment by Lukewh** [comment]
Store team are working on a fix... I'm going to add a notification if this happens in future though

**Comment by Lukewh** [comment]
The fix has been applied to the store and we now display an error message when there is an error.
