### ISSUE TITLE
Youtube video url validation fails

### ISSUE THREAD

**Issue by thomasnordquist** [canonical-web-and-design/snapcraft.io#1884]
### Steps to reproduce the problem
While editing app listings one cannot add a valid youtube URL if it contains a dash ("-"), because the URL validation fails.

Screenshot:
<img width="740" alt="Bildschirmfoto 2019-05-02 um 13 45 47" src="https://user-images.githubusercontent.com/7721625/57073431-5b7ef880-6ce1-11e9-8986-4d98b15b0bbd.png">

**Workaround:** Re-upload and hope for a youtube link without a dash.

**Comment by therealjuan** [comment]
As part of this, we could also improve the type of URLs we support: https://github.com/canonical-web-and-design/snapcraft.io/issues/1994

**Comment by bartaz** [comment]
It's the store API that doesn't allow these URLs. So we need to request the change on the store side.

**Comment by thomasnordquist** [comment]
@bartaz How/Where to report/request this change?

**Comment by therealjuan** [comment]
I have already reported this on its relevant repo: https://bugs.launchpad.net/snapstore/+bug/1832633

Stay tuned for updates!

**Comment by therealjuan** [comment]
This has already been fixed. Please re-open if you still find issues. Thanks for reporting.
