### ISSUE TITLE
Not possible to file dispute for reserved name

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/snapcraft.io#1885]
### Expected behaviour

You are able to file a dispute for a reserved name at https://snapcraft.io/register-snap.

### Steps to reproduce the problem

* Go to https://snapcraft.io/register-snap, type bitcoin-test, hit register.
* Go to https://dashboard.snapcraft.io/register-snap/, type bitcoin-test, hit register.

**Comment by der-eismann** [comment]
Same here... it's a bit dumb to be on the page `Request reserved name <name> in the Global store` and then getting the message `Error: The snap name "aws-nuke" is reserved`. 
*That's why I am here*

**Comment by Lukewh** [comment]
@der-eismann you can file a bug for https://dashboard.snapcraft.io at https://bugs.launchpad.net/snapstore/+filebug
@evandandrea :+1: It's possible to do this with the API so will add to the backlog, thanks :)

**Comment by Lukewh** [comment]
Turns out this is not possible with the current API, so is blocked :(!

**Comment by cprov** [comment]
@Lukewh are you already switching to the [register-dispute API](https://dashboard.snapcraft.io/docs/api/snap.html#post--dev-api-register-name-dispute-
) when you get a reserved-name or already-owned name error from the register-name API ?

See an example usage below:

```
$ surl -a prod-reg https://dashboard.snapcraft.io/dev/api/register-name-dispute/ \
    -d '{"snap_name": "bitcoin", "comment": "Testing API for https://github.com/canonical-web-and-design/snapcraft.io/issues/1885"}'
...
{"status_url": "https://dashboard.snapcraft.io/register-snap-feedback/bitcoin/", "snap_name": "bitcoin"}
```

**Comment by therealjuan** [comment]
We found this on the snapcraft summit in a few occassions:

### Steps to reproduce
1. Log in into your account
2. Go to [Register a snap name ](https://snapcraft.io/register-snap)
3. Enter a reserved name like `cmake`

### What is happening?
You get the message: `The snap name "cmake" is reserved.` with no option to file a dispute. Please note that we currently offer the option to file a dispute if the name already exists on the store so we should give an option to the publisher to use the `file a dispute` interface.

### What should happen?
The publisher should be able to make a claim on the reserved name and view the following message:
`The new message could be `The snap name "cmake" is reserved. You can file a dispute to request a transfer of ownership or register a new name below.`
Then it could be redirected to the [file a dispute interface](https://snapcraft.io/register-name-dispute?snap-name=cmake).
