### ISSUE TITLE
Can't manage tracks if the snap hasn't had a release made to a track before 

### ISSUE THREAD

**Issue by Roadmaster** [canonical-web-and-design/snapcraft.io#1887]
### Expected behaviour
I should be able to "Promote" a snap to any track, even if the tracks haven't had any releases (possibly done with snapcraft) before.

### Steps to reproduce the problem
1- (Do this on a snap with tracks)
2- snapcraft close the-snap the-track/risk (and repeat for all open risks in the track)
3- Do the above until all tracks other than `latest` are closed.
4- Under "revisions available to promote", click on "promote" next to an available revision

What I expected:
- A list of latest/$risk (which is there) and/or $track/$risk (which is NOT there - ftr this snap does have a track called "unitrack"). 

What I saw:
- Only a list of latest/$risk.
![Screenshot_2019-05-06  Releases and revision history for hello-roadmr-unicrash-1 ](https://user-images.githubusercontent.com/15329/57234881-a8b7de80-6fef-11e9-8dec-09c3da7eb6a4.png)

I noticed that if I do a `snapcraft release my-snap my-revision unitrack/edge` or such, once a release is made to the track, then a "Show revisions available in" control appears in the top right; I can then select the "unitrack" track here, and "Promote" now shows me the risks under that track. This is what I wanted! Unfortunately, the "Show revisions available in" control does NOT show if there are no releases to the track in question. So it's a chicken-and-egg kind of problem :)
![Screenshot_2019-05-06  Releases and revision history for hello-roadmr-unicrash-1 (1)](https://user-images.githubusercontent.com/15329/57234902-b2414680-6fef-11e9-932d-0185c38aa103.png)

### Specs

- _URL:_ https://staging-api.snapcraft.io/hello-roadmr-unicrash-1/releases
- _Operating system:_ Ubuntu 18.04
- _Browser:_ Firefox 66.0.2 (64-bit)

**Comment by bartaz** [comment]
Release UI is based around data from channel map, so it currently only shows tracks that have something released. That's why it's currently not possible to release something to empty track or to release something to a new track.
I'm not sure if API gives us a list of all tracks (including empty), but for sure we don't have UI to create a new track, so that's what would need some design work.

**Comment by jkfran** [comment]
Hi @Roadmaster we believe the issue is gone as we couldn't reproduce it.
