### ISSUE TITLE
Installing multipass instructions on first-snap should link to multipass website

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/snapcraft.io#1903]
### Expected behaviour

The instructions for setting up snapcraft for non-Linux OSs should link to https://multipass.run/install 

### Steps to reproduce the problem
1. Initiate first-snap flow, for any language, but in this example for Python
2. Click on macOS
3. Note Step 1 link

### Specs

- _URL:_ https://snapcraft.io/first-snap/python
- _Operating system:_ Ubuntu 19.04
- _Browser:_ Firefox 66.0.4

**Comment by bartaz** [comment]
Good catch, thanks @sparkiegeek
