### ISSUE TITLE
Mac first snap flow instructions uses wrong filenames on test step

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/snapcraft.io#1910]
### Expected behaviour

The test step has commands like `multipass copy-files test-offlineimap-ev*.snap testvm:` (where ev is what I've put in the "choose snap name" box)

### Steps to reproduce the problem

* https://snapcraft.io/first-snap/python/macos/test
* Notice that the commands are, e.g. `sudo snap install --devmode --dangerous offlineimap*.snap`

**Comment by bartaz** [comment]
@evandandrea I guess it's the case for all languages in first snap flow?

BTW. It seems that test.yaml (content for macos test page) is very similar for all of the languages. It seems that apart from some minor wording changes the biggest difference is in a snap name - which by recent changes is replaced by user input anyway.

Can we assume that test instructions will be the same for all languages (with snap name correctly replaced), so there is no need to keep a copy of the content per language?
