### ISSUE TITLE
embedded pages should not be indexed

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#1928]
### Expected behaviour

Searching for a snap I made should result in the store page. It does, but also an 'embedded' page appears, which has almost no content so isn't a lot of use to users.

### Steps to reproduce the problem

Go to your favorite search engine and search for a snap name and the word snap.

![image](https://user-images.githubusercontent.com/1841272/58017506-4fc06e00-7af8-11e9-94b2-61a759eeccf1.png)

Please can we add a robots.txt (or whatever) to prevent /embedded pages being indexed.

**Comment by bartaz** [comment]
We discussed adding `rel="canonical"` metadata URL, so embedded pages are treated as snap details page by search engines.
