### ISSUE TITLE
Change of username in Ubuntu One should be reflected to Snapcraft.io

### ISSUE THREAD

**Issue by wilzbach** [canonical-web-and-design/snapcraft.io#1935]
### Expected behaviour

Being able to change a username in Ubuntu One and let the update reflect to Snapcraft.io

### Steps to reproduce the problem

1) Register and upload a package under a private username

In my case: https://snapcraft.io/story with 'wilzbach'

2) Realize that snapcraft.io displays the private username and there's no way to change the ownership nor set publisher names

3) Rename the account and user name in Ubuntu One

4) Follow the instructions on https://github.com/canonical-web-and-design/snapcraft.io/issues/404 to get the full name updated

5) Check snapcraft username on https://dashboard.snapcraft.io/dev/account/

![image](https://user-images.githubusercontent.com/4370550/58185671-c9e92200-7cb3-11e9-9ddf-1b5ece2cf135.png)

6) Check the username on the story (https://snapcraft.io/story)

![image](https://user-images.githubusercontent.com/4370550/58185888-2a785f00-7cb4-11e9-9e79-9a40edf28828.png)

(no updates on the Snapcraft.io page)

----

It would be great if a Snapcraft admin could help out and rename that account to 'storyscript' or transfer the ownership to a 'storyscript' account. Not sure which one is easier as I might have confused the Snapcraft DB with creating a new private account for myself to preserve my handle (and avoid anyone abusing any potential security holes).

Thanks a lot in advance!

---

Seems to be a common problem see e.g. https://github.com/canonical-web-and-design/snapcraft.io/issues/1845 or https://forum.snapcraft.io/t/snapcraft-store-displays-incorrect-username/10584

**Comment by therealjuan** [comment]
Thanks for bringing this to our attention. 

Have you tried logging out and logging in in snapcraft.io? 

Check if that helps or let us know so we can investigate further.

**Comment by wilzbach** [comment]
> Have you tried logging out and logging in in snapcraft.io

Yes, a few times.

> so we can investigate further.

That would be great. Thanks!

**Comment by cprov** [comment]
Hi wilzbach,

I've re-processed your snap manually and it is displayed as expected:

![image](https://user-images.githubusercontent.com/3610997/58823780-e4ef5680-8610-11e9-95ba-69cdc2f9a85f.png)

You have done exactly what is required to trigger an auto-update on `2019-05-22T14:45:08.459185Z` and I will investigate why it was only partially processed.

**Comment by slr** [comment]
same here. there is no changes occurred on https://snapcraft.io/account/details after editing Username on Ubuntu One

**Comment by flotwig** [comment]
Still having this issue, updated username on Launchpad but it does not reflect on the Snap listing page.

I wish there was a way to just write the publisher name as part of the listing instead of having to rename my Launchpad account to the publisher's name.
