### ISSUE TITLE
Banner ratio error message is unhelpful when banner size is nearly correct

### ISSUE THREAD

**Issue by stuartlangridge** [canonical-web-and-design/snapcraft.io#1936]
### Expected behaviour
The error message explains the problem rather than making it look like there is no problem.

### Steps to reproduce the problem
1. upload a banner image for a snap which is 1444x482
2. get the error message: `banner3to1.png has a width (1444 pixels) that is 3x its height (482 pixels). Its width needs to be 3x the height.`
3. look very puzzled for a moment
4. realise that the banner needs to be _exactly_ 3:1 ratio, and that the error message is very unhelpful in explaining this. Perhaps it should say `banner3to1.png has a width (1444 pixels) that is 3x its height (482 pixels). Its width needs to be 3x the height (for example, 1446x482).` or similar.

**Comment by therealjuan** [comment]
Thanks for reporting this as the message can be more helpful suggesting a set of dimensions and reducing unnecessary explanation:
`banner3to1.png dimensions are not valid. Its width must be 3x the height. (for example, 1446x482)`

What do you think?

**Comment by stuartlangridge** [comment]
Changing the message to be clearer about the problem is the important thing; the nuance of the wording could perhaps be a little improved, though. Maybe:

`banner3to1.png (1444x482 pixels) is not the correct aspect ratio: it needs to be 3:1 (e.g., 1446x482 pixels)`

That is: the issue isn't the dimensions (those are valid: they're the dimensions the image actually is, after all), but the aspect ratio; and better to use "e.g." than "i.e." because i.e. would imply that those suggested dimensions have to be used, where actually they're only an example of an image size that would be acceptable.

(It might be most helpful for the suggested dimensions to be the largest possible 3:1 image which is smaller than the provided image, so that the provided image can definitely be cropped to that size.)

**Comment by Lukewh** [comment]
@stuartlangridge I like this. Especially providing dimensions of the largest possible image if the image provided exceeds them.
