### ISSUE TITLE
Move static_url into a module

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/snapcraft.io#1940]
So it can be shared with other sites - e.g. maas.io.

It's currently here:

https://github.com/canonical-web-and-design/snapcraft.io/blob/ba0180b5191f1a07a3e762d3b708ccebb1a49524/webapp/template_utils.py#L58-L79

See also: https://github.com/canonical-web-and-design/maas.io/pull/333/

**Comment by danielmutis** [comment]
Already in flask-base.
