### ISSUE TITLE
FSF: Replace current pagination with button-style

### ISSUE THREAD

**Issue by therealjuan** [canonical-web-and-design/snapcraft.io#1969]
The current style for the pagination on First Snap Flow could be missed as it looks quite similar to a header or footer so might be worth exploring using regular buttons instead as on the first steps of the journey.

**Comment by matthewpaulthomas** [comment]
I think this is an example of why it’s a bad idea to call [a design pattern “breadcrumbs”](https://docs.vanillaframework.io/patterns/breadcrumbs/). It’s named after the Hansel and Gretel story where the breadcrumbs recorded a sequential path, so it’s understandable that they were used that way here. But nowadays when designers say “breadcrumbs” they’re _usually_ referring to navigation though a hierarchy, not through a sequence.

As well as using a button style instead, another thing that would make the steps look less like a header is having a heading for the flow as a whole, positioned between the global navigation and the steps. In my original wireframes, I did both:

![fsf-header](https://user-images.githubusercontent.com/19801137/59494434-09ef8f00-8e85-11e9-9417-31b7bbc08c66.png)

**Comment by therealjuan** [comment]
No one really talked about breadcrumbs but thanks for the #mansplaining. Not sure how adding a header will help in any way to the real issues here which are:

* Visitors not identifying how to proceed because the pagination at the bottom looks like a footer
* The package step could be simplified but that is covered by a [different issue](https://app.zenhub.com/workspaces/snap-squad-593688b45aa7c527b96f9401/issues/canonicalltd/snap-squad/1024)
