### ISSUE TITLE
microK8s Cannot Be Installed on CentOS 7

### ISSUE THREAD

**Issue by Xtigyro** [canonical-web-and-design/snapcraft.io#1974]
### Expected behaviour
An installed and working `microK8s` setup.

### Steps to reproduce the problem
```
sudo yum install epel-release
sudo yum -y install snapd
sudo systemctl enable --now snapd.socket
sudo ln -s /var/lib/snapd/snap /snap
sudo snap install microk8s --classic

Run install hook of "microk8s" snap if present (run hook "install": execv failed: Permission denied)

```

**Comment by flexiondotorg** [comment]
Hi @Xtigyro,

The [instructions for installing `snapd` on CentOS](https://docs.snapcraft.io/installing-snap-on-centos) ask that you either log out/in or restart your system? 

Please, can you confirm that you di that?

**Comment by bboozzoo** [comment]
This is a bug in our recent SELinux policy changes. The fix is here: https://github.com/snapcore/snapd/pull/6970 We'll look into making this available in updated snapd package.

**Comment by Xtigyro** [comment]
@flexiondotorg @bboozzoo Thank you very much, folks!

**Comment by bboozzoo** [comment]
@Xtigyro snapd update has been pushed to EPEL testing. Please see https://forum.snapcraft.io/t/snapd-updates-in-fedora-epel-for-enterprise-linux/8310/17 for details.

**Comment by therealjuan** [comment]
Closing as this is nothing to do with the storefront. Thanks for the report!
