### ISSUE TITLE
Logout does not get fully done opening  /account from docs

### ISSUE THREAD

**Issue by therealjuan** [canonical-web-and-design/snapcraft.io#1986]
## Steps to reproduce
1. Log in with a Developer account
2. Once you are viewing your `/snaps` log out from your account
3. You are in logged out state and visit the following documentation page to [create a snap store account](https://docs.snapcraft.io/t/creating-snap-store-brand-accounts/6271)

## What is happening?
You are logged in forcely with no option to register a new account

## What should happen?
You are given the option to either log in or create a new account

**Comment by Lukewh** [comment]
Discussed with @cprov during weekly meeting.
Next steps:
- UX decision on what the right approach should be considering:
 - a user logging out of snapcraft.io may still be logged in to other SSO services
 - a user logging out of snapcraft.io may want to log in with a different account

**Comment by jpmartinspt** [comment]
We should make change, so whenever you press the logout button you get logged out of Ubuntu One.

**Comment by bartaz** [comment]
While we are at it, there is quite annoying that currently when working on localhost logout always redirects to snapcraft.io instead of localhost. 
I can't count the times when it made me wonder why my stuff doesn't work, just because I got redirected to prod without noticing.

**Comment by jpmartinspt** [comment]
@bartaz I tried this but `login.ubuntu.com` does not seem redirect to `localhost`.

**Comment by bartaz** [comment]
> @bartaz I tried this but `login.ubuntu.com` does not seem redirect to `localhost`.

@jpmartinspt Hmmm... Too bad. But it does redirect to localhost when logging in, right? It wouldn't work otherwise... Weird

**Comment by jpmartinspt** [comment]
@bartaz The logout endpoint at least, seems happy to redirect to `snapcraft.io` but not to `localhost:8004`.
