### ISSUE TITLE
FSF - Include file name at the top right of yaml 

### ISSUE THREAD

**Issue by therealjuan** [canonical-web-and-design/snapcraft.io#1991]
Right now when visiting the first-snap flow for any programming language, we show visitors a sample snapcraft.yaml for them to download.

![image](https://user-images.githubusercontent.com/8167677/59359883-2c56a080-8cfd-11e9-887b-7f7a727994fb.png)

It will be good to add the name of the file (with the folder perhaps) on the top right similarly to what is happening on travis docs as this might help in the future when referring other type of files like `travis.yml`:

![image](https://user-images.githubusercontent.com/8167677/59360251-c6b6e400-8cfd-11e9-93ea-b36bb41bd2ee.png)

**Comment by hughesjordan** [comment]
![YAML file name.png](https://images.zenhubusercontent.com/5c052434391a6f6357ada9f5/878bc839-69e6-42e2-ab57-674cf6300bf7)
