### ISSUE TITLE
Allow youtube short urls for video input on store listings

### ISSUE THREAD

**Issue by diddledan** [canonical-web-and-design/snapcraft.io#1994]
### Expected behaviour

Using an URL that is copied from youtube of the form `https://youtu.be/idnum` should be accepted by the store listing edit page in the video field.

### Steps to reproduce the problem

Find a video on youtube and right-click the video pane to select the "copy video URL" menu item. Paste this short URL into the video field on your store listing edit page and submit. An error will indicate that the URL is invalid.

An example video URL is https://youtu.be/3OFhVtqfDBQ

**Comment by bartaz** [comment]
It's the store API that doesn't allow these URLs. So we need to request the change on the store side.

**Comment by bartaz** [comment]
Reported and in progress on store API: https://bugs.launchpad.net/snapstore/+bug/1832633
