### ISSUE TITLE
Distro pages: Instructions to install a snap differ from detail pages

### ISSUE THREAD

**Issue by therealjuan** [canonical-web-and-design/snapcraft.io#1995]
Currently on detail pages we add `--classic` to snaps that need classic confinement whereas on distro install instructions for the snap we don't.

![image](https://user-images.githubusercontent.com/8167677/59368813-046f3900-8d0d-11e9-98c2-4dd99b41f524.png)

![image](https://user-images.githubusercontent.com/8167677/59368852-16e97280-8d0d-11e9-8d9e-22acca5a792a.png)

There are a few options:
a. Include `--classic` as part of the install instructions
b. Remove `--classic` as the user will be prompted whilst trying to install the snap

(a) will stop people understanding why they need the classic option and perhaps could include it in further snap install commands whereas with (b) the user will be prompted that `classic` parameter will be needed but it will learn about why the parameter is needed.

(b)?

**Comment by audiofanatic** [comment]
Seems that the discussions in #928 concluded that (a) is what we want here too (I would expect that consistency between the generic and distro-specific pages is desirable).
