### ISSUE TITLE
Adding a gif to a store entry silently discards the image

### ISSUE THREAD

**Issue by diddledan** [canonical-web-and-design/snapcraft.io#1997]
### Expected behaviour

The GIF image should be saved and visible in the refreshed edit page.

### Steps to reproduce the problem

- Take the following image and try adding it to a store listing as a screenshot (I'm trying to add it to `openra`).

![openra-anim](https://user-images.githubusercontent.com/147548/59435143-f4ae2e00-8dba-11e9-83c3-d25a1a279a77.gif)

- Click save and wait for the edit page to refresh.
- The image is not visible anymore on the reloaded page, and the screenshot slot it was occupying responds as though no image is assigned so clicking on it again prompts for a file to upload anew. There is no message indicating failure condition.

### Specs

- _URL:_ https://snapcraft.io/openra/listing
- _Operating system:_ Ubuntu 19.04
- _Browser:_ Firefox 67.0.1 from the Ubuntu APT repositories (deb version: 67.0.1+build1-0ubuntu0.19.04.1)

**Comment by diddledan** [comment]
Oh, looks like I'm blind. The framerate is too slow... Perhaps this should actually be a request to lessen the restrictions on framerate a bit... Specifically I missed the error message at the top of the page indicating framerate issue so please close if you do not feel that a slower framerate should be allowed to let this specific gif and others like it through.

**Comment by Lukewh** [comment]
Hi @diddledan, I think the bigger issue here is that the error is hidden when you click save. I've created [this issue](https://github.com/canonical-web-and-design/snapcraft.io/issues/2436) to address that problem.
Reducing the minimum frame rate isn't something we'll be looking at currently, but we'll keep it in mind thanks :).
