### ISSUE TITLE
The "Promote" button opens a submenu but doesn't have UI indication that it does this

### ISSUE THREAD

**Issue by diddledan** [canonical-web-and-design/snapcraft.io#1998]
### Expected behaviour

We need a visual cue that the "Promote" button will open a submenu that requires further interaction.

### Steps to reproduce the problem

- Go to releases page for a snap and find the "Promote" button.

![image](https://user-images.githubusercontent.com/147548/59440159-7eaec480-8dc4-11e9-8b82-2880197a8dfb.png)

- Click it expecting an immediate action because it's a button, not a menu
- Notice that nothing happened except a menu opened

### Specs

- _URL:_ https://snapcraft.io/gimp/releases
- _Operating system:_ Ubuntu 19.04
- _Browser:_ Firefox

**Comment by popey** [comment]
At the summit last week we had a few occasions where new users to the snap store were completely unaware that this was a clickable thing.

**Comment by bartaz** [comment]
This button was removed while ago (changed to cog icon)
