### ISSUE TITLE
List of distributions the snap package installed on is so long.

### ISSUE THREAD

**Issue by keshavbhatt** [canonical-web-and-design/snapcraft.io#2000]
### Expected behaviour
In the lower portion where we are listing the distributions where the snap has been installed by users (metrics) is so long for some snaps which is not browser friendly (specially on mobile) users have to keep scrolling to reach bottom.

### Steps to reproduce the problem
Visit the page for spotify app https://snapcraft.io/spotify

### Specs

- _URL:_  https://snapcraft.io/spotify
- _Operating system:_ Android O (or any)
- _Browser:_ Chrome (latest) or any browser.

**Comment by kwm14** [comment]
@keshavbhatt thanks for reporting 😃 

@Lukewh a simple solution to reduce a long list of distributions, we could add a **_Show more_** link that expands the list. Similarly to what we've just implemented on our [distro pages ](https://snapcraft.io/install/spotify/debian) to reduce long scrolls if the content is too long.

![snap-distributions-list-v1](https://user-images.githubusercontent.com/17748020/59768326-123c3580-929c-11e9-966f-53d5afc88001.png)
