### ISSUE TITLE
Clicking on screenshot should open a lightbox image viewer.

### ISSUE THREAD

**Issue by keshavbhatt** [canonical-web-and-design/snapcraft.io#2001]
### Expected behaviour
When users clicks on an screenshot on the snap preview page they are expecting to get the image open in a lightbox image viewer.

### Steps to reproduce the problem
Visit  https://snapcraft.io/wonderwall click on any screenshot page will make user jump away from the website which is not a good practice (from SEO perspective too)

### Specs

- _URL:_ https://snapcraft.io/wonderwall
- _Operating system:_ Any
- _Browser:_ Any

### Solution
Implement any lightweight lightbox plugin to open screenshots on the same page with image navigation and close feature.

**Comment by therealjuan** [comment]
Thanks for the issue but would you be able to provide further information as we have a lightbox image viewer implemented in the storefront:

![image](https://user-images.githubusercontent.com/8167677/59459331-841f0580-8dea-11e9-88ee-c5f4c55432f4.png)

**Comment by keshavbhatt** [comment]
i tested it on my mobile phone Samsung S7 edge, and the image open in new tab instead of lightbox.

**Comment by keshavbhatt** [comment]
yes when desktop site is forcibly loaded on phone lightbox works.
