### ISSUE TITLE
Publicise: Embeddable cards display grows vertically indefinitely

### ISSUE THREAD

**Issue by audiofanatic** [canonical-web-and-design/snapcraft.io#2004]
### Expected behaviour
Preview of embeddable card doesn't grow in size.

### Steps to reproduce the problem
Visit the Publicise tab of a snap. In my case, I'm looking at https://snapcraft.io/cmake/publicise/cards

Click on "Embeddable cards" in the left sidebar. The preview grows in length with a blank line being added about once per second. This growth possibly only occurs while looking at the tab (doesn't seem to grow while switching to a different browser tab).

### Specs

- _URL:_ https://snapcraft.io/cmake/publicise/cards
- _Operating system:_ macOS mojave
- _Browser:_ Safari

**Comment by bartaz** [comment]
Thanks for the report. It seems in Safari our embedded card resize script gets into a loop for some reason.
This works well in Chrome and Firefox.

We will have a look for a fix for Safari.
