### ISSUE TITLE
Fedora pages don't follow logo usage guidelines

### ISSUE THREAD

**Issue by zyga** [canonical-web-and-design/snapcraft.io#2007]
### Expected behaviour

Usage of the Fedora logo is in accordance with the logo usage guidelines https://fedoraproject.org/wiki/Logo/UsageGuidelines#Common_guidelines

### Steps to reproduce the problem

Go to https://snapcraft.io/install/spotify/fedora

### Specs

- _URL:_
- _Operating system:_
- _Browser:_

**Comment by mairin** [comment]
We don't allow the redistribution of the Fedora logo in vector format. Can you use a high-res bitmap to address this issue?

**Comment by flexiondotorg** [comment]
Tagging @therealjuan

**Comment by therealjuan** [comment]
Hello @mairin 

Thanks for pointing to the right asset. 

The following examples use this image that you have shared with us but wanted to get your thoughts to make sure we don't break branding guidelines.

Would it be acceptable to...

...include this high-res bitmap asset in the header with a darker background?

![image](https://user-images.githubusercontent.com/8167677/59698143-fb87d700-91e6-11e9-9c62-67d208a059dc.png)

...use the same high-res bitmap asset in the install instructions content?

![image](https://user-images.githubusercontent.com/8167677/59698225-24a86780-91e7-11e9-9b97-c416d229027e.png)

[Please follow this link for a live version](https://snapcraft-io-canonical-web-and-design-pr-2024.run.demo.haus/install/skype/fedora)

**Comment by mairin** [comment]
@therealjuan that looks perfectly fine to me!
