### ISSUE TITLE
Checkmark ticks are too high

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2020]
![](https://user-images.githubusercontent.com/8167677/59669668-8b5f5e00-91b2-11e9-85e3-3cfe71ce4d64.png)

As seen in https://github.com/canonical-web-and-design/snapcraft.io/pull/1898#issuecomment-503021759

**Comment by therealjuan** [comment]
If only we updated to vanilla 2.0 ...

**Comment by kwm14** [comment]
# 2.0 coming soon @therealjuan 🚀 

<img width="468" alt="Screenshot 2019-06-19 at 14 24 12" src="https://user-images.githubusercontent.com/17748020/59769396-f8035700-929d-11e9-9e51-c7c647ddef95.png">

**Comment by therealjuan** [comment]
Fixed with New Vanilla Ice Ice baby
