### ISSUE TITLE
Snapcraft build is not logged in although the header thinks it is

### ISSUE THREAD

**Issue by stuartlangridge** [canonical-web-and-design/snapcraft.io#2032]
### Expected behaviour
Going to snapcraft.io/build while logged in should show me the logged in screen with a list of my set-up builds, not the "set up in minutes" screen for new users.

### Steps to reproduce the problem
Sign in to snapcraft.io to see one's existing snaps.
Go to build.snapcraft.io
Observe that the header shows my name (meaning that I'm logged in) but I see the "set up in minutes" screen that's shown to new users. I don't need to set up; I already _am_ set up. But I have to click that "set up in minutes" button in order to log in. This makes it feel like my work has been forgotten; it's strange to click a "set up in minutes" button (which is like "register an account" on other sites) when I already am registered.

(Technical note: I assume this is something to do with how signing in to snapcraft.io is through my Ubuntu One account, and signing in to build.snapcraft.io is through my github account, but this is an implementation detail that I should not have to care about; if I'm logged in, I'm logged in.)

![image](https://user-images.githubusercontent.com/4356350/59864880-a6cb9400-937f-11e9-89d8-3c1c92e59778.png)

### Specs

- _URL:_ https://build.snapcraft.io
- _Operating system:_ Ubuntu 18.04
- _Browser:_ Firefox

**Comment by tbille** [comment]
build.snapcraft.io is going to be deprecated soon.
This issue shouldn't be an issue on the [new github build implementation](https://snapcraft.io/blog/we-are-changing-the-way-you-build-snaps-from-github-repos)

Closing this issue.
