### ISSUE TITLE
Using multi line code blocks in a listing description is inconsistent between the preview and actual page

### ISSUE THREAD

**Issue by ahayzen** [canonical-web-and-design/snapcraft.io#2033]
### Expected behaviour

I expected the preview to show the same as the actual page (not to format multi line code blocks)

### Steps to reproduce the problem

1) Create a listing description which has a multi line code block (multiple lines wrapped by triple backticks)
![Screenshot from 2019-06-20 23-26-52](https://user-images.githubusercontent.com/3669750/59885366-ed86b180-93b2-11e9-9c5a-75b46d2058fc.png)

2) Click preview and notice how it formats the block as a code block
![Screenshot from 2019-06-20 23-27-29](https://user-images.githubusercontent.com/3669750/59885397-00998180-93b3-11e9-9e41-ccab49e15d7a.png)

3) Now click save and view the actual store page, notice how this does not format the code block
![Screenshot from 2019-06-20 23-28-04](https://user-images.githubusercontent.com/3669750/59885420-1a3ac900-93b3-11e9-8bb6-7a281e4d5754.png)

I understand that the store page uses a subset of markdown (which does not support multi line code blocks), so it is the preview which is wrong here and should format in the same way as the actual page ?

### Specs

 - Browser: Firefox 67

**Comment by bartaz** [comment]
@ahayzen Thanks a lot for the report. You are of course correct, both markdown implementations (for the page and preview) should be in line and this is a bug.
Preview uses client side (JavaScript) Markdown implementation and it seems we forgot to remove codeblock support from it when we did it for Python implementation for snap details page.
