### ISSUE TITLE
Can't upload logo and screenshots

### ISSUE THREAD

**Issue by dima11221122** [canonical-web-and-design/snapcraft.io#2037]
### Expected behaviour
I want to upload logo and screenshots of my snap. 
### Steps to reproduce the problem

for logo:
- go to my snap -> Listing
- in **Snap icon** field choose icon
- Press **Save**
- Page is reloaded and the error is shown:
`IOError: cannot identify image file <InMemoryUploadedFile: logo_mq.png (image/png)>`

for screenshot:
- go to my snap -> Listing
- In **Images** field press **Add image** and choose a screenshot
- Press **Save**
- Page is reloaded and the error is shown:
`IOError: cannot identify image file <InMemoryUploadedFile: Screenshot_2019-06-24_at_11_59_52.png (image/png)>`
### Specs

- _URL:_ [https://snapcraft.io/testmace/listing](https://snapcraft.io/testmace/listing)
- _Operating system:_ Ubuntu 18.04.2 LTS
- _Browser:_ Google Chrome 75.0.3770.100

**Comment by therealjuan** [comment]
Thanks for reporting the issue @dima11221122 . I've just tried in some of my snaps with different types of images.

Would you be able to post here the images you used so we can investigate on our end?

**Comment by dima11221122** [comment]
Here is the sample of screenshots:
https://drive.google.com/uc?export=download&id=1XdPz1BSajPVm8a8q8SlGrYkXQVtTy2Sp
here is logo:
https://drive.google.com/uc?export=download&id=1L1D9hR_WBnEFsqvBpWfHxGMMYzwsk8wF
How I got screenshot:
1. Made the screenshot using standard macos screenshot tool
2. Scale down the screenshot using gimp on ubuntu 18.04
Probably it will help you

**Comment by therealjuan** [comment]
Hello again.

I have been tried with multiple images and everything works correctly. Once I tried to use these images you shared with me, I was retrieving the same error.

Parsing the logo for instance through this [online file metadata reader](https://www.get-metadata.com), it gave me the following result:

`Warning Bad length ICC_Profile (length 1485568417)`

I opened your files and save them again and it fixed the errors. Here you have the files I used:

![logo_mq](https://user-images.githubusercontent.com/8167677/60103307-452c7080-9757-11e9-932b-4474a6d838d3.png)
<img width="1646" alt="Screenshot_2019-06-24_at_11_51_28" src="https://user-images.githubusercontent.com/8167677/60103308-452c7080-9757-11e9-8768-cda4e029c43e.png">

**Comment by dima11221122** [comment]
@therealjuan thanks a lot! I'll try to fix metadata

**Comment by dima11221122** [comment]
Yes, it works! You can close the issue

**Comment by therealjuan** [comment]
Thanks and please let us know how are you getting on. We love feedback!
