### ISSUE TITLE
Failed to start docker as service: /usr/bin/dockerd missing

### ISSUE THREAD

**Issue by Marco-Sulla** [canonical-web-and-design/snapcraft.io#2074]
### Expected behaviour

I should start the docker daemon using

```bash
sudo service docker start
```

### Steps to reproduce the problem

```bash
sudo snap install docker
sudo service docker start
```

### Actual result

```bash
[2019-07-08 15:22:21 $] sudo service docker start
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
[2019-07-08 15:22:37 $] systemctl status docker.service
[...]
lug 08 15:22:37 mrblack docker[17592]:  * /usr/bin/dockerd not present or not executable
```

### Specs

- _URL:_ not applicable
- _Operating system:_ Lubuntu 18.04.2 x86_64 kernel 4.15.0-54-generic
- _Browser:_ not applicable

### Notes
I tried also to remove and reinstall without success. I also tried to find `dockerd` in the whole system but there's no file with that name.

**Comment by Marco-Sulla** [comment]
Sorry, the correct command is:

```bash
sudo service snap.docker.dockerd  start
```

**Comment by jphellemons** [comment]
do you have an update?
