### ISSUE TITLE
docker-machine create does not find VBoxManage

### ISSUE THREAD

**Issue by Marco-Sulla** [canonical-web-and-design/snapcraft.io#2075]
### Expected behaviour

`docker-machine create` should work

### Steps to reproduce the problem

```bash
sudo snap install docker
docker-machine create default
```

### Actual result

> Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"

### Specs

- _URL:_ not applicable
- _Operating system:_ Lubuntu 18.04.2 x86_64 kernel 4.15.0-54-generic
- _Browser:_ not applicable

### Notes:

This bug was reported also on the [Github of Docker](https://github.com/docker/machine/issues/4590).

### Workaround

```bash
curl -L https://github.com/docker/machine/releases/download/v0.16.1/docker-machine-`uname -s`-`uname -m` >/tmp/docker-machine
chmod +x /tmp/docker-machine
/tmp/docker-machine create default  # test it
# if successful
sudo install /tmp/docker-machine /usr/bin/docker-machine
```
[Source](https://github.com/docker/machine/issues/4590#issuecomment-449945668)

**Comment by tbille** [comment]
Closing this issue since not related to the site it self.
In case this is still an issue you can open a topic in the forum: https://forum.snapcraft.io/
