### ISSUE TITLE
Snap App Banner color covers over App icon

### ISSUE THREAD

**Issue by mikeroyal** [canonical-web-and-design/snapcraft.io#2086]
In the store for the crystal-lang banner the dark coloring covers the icon for crystal-lang. I provided a screenshot below I would recommend changing the color to grey so the icon will be more visible or just lighten the current dark banner.

![snap-store](https://user-images.githubusercontent.com/45159366/61189255-ae5d2080-a63f-11e9-8e65-f34d35b82dec.png)

**Comment by Lukewh** [comment]
Thanks for this report @mikeroyal. I just started this morning and noticed the same thing so have done a quick PR for it. Hopefully I'll be able to deploy sometime this morning :)
