### ISSUE TITLE
Release UI: Indicate a revision can't be dragged as it has same revisions

### ISSUE THREAD

**Issue by therealjuan** [canonical-web-and-design/snapcraft.io#2092]
When dragging a set of revisions, we should indicate that dragging is not allowed in revisions that contain the same revision numbers as the one you are dragging:

![image](https://user-images.githubusercontent.com/8167677/61442392-d1414a80-a947-11e9-8042-f4e52ecbdcbb.png)

**Comment by Lukewh** [comment]
This has been fixed as part of another issue. Thanks for reporting.
