### ISSUE TITLE
Trending: Updated snap store buttons displaying data

### ISSUE THREAD

**Issue by therealjuan** [canonical-web-and-design/snapcraft.io#2093]
It will be good to display some additional data like Trendingness, Popularity or Install base next to the badges of Snap Store buttons:

![image](https://user-images.githubusercontent.com/8167677/61443457-d606fe00-a949-11e9-8f7e-b9996906dbeb.png)

`[ 🐦Get it from the Snap Store 📈Trending this month ]`
`[ 🐦Get it from the Snap Store 📈Trending this month | 100,000+ installs ]`

`[ 🐦Get it from the Snap Store ⭐ ]`
`[ 🐦Get it from the Snap Store ⭐| 100,000+ installs ]`

**Comment by kwm14** [comment]
## Initial explorations
A first pass at creating trending/install snap store buttons.

### 001
![snap-badge-rating-001](https://user-images.githubusercontent.com/17748020/61451545-93492400-a951-11e9-9c38-31fc73d9c845.png)

### 002
![snap-badge-rating-002](https://user-images.githubusercontent.com/17748020/61451547-93492400-a951-11e9-8496-0155263f5449.png)

### 003
![snap-badge-rating-003](https://user-images.githubusercontent.com/17748020/61451548-93492400-a951-11e9-810b-894f79709a21.png)

### 004
![snap-badge-rating-004](https://user-images.githubusercontent.com/17748020/61451549-93e1ba80-a951-11e9-945b-d52391e292bf.png)

**Comment by kwm14** [comment]
## Design review
Weekly meeting notes can be found here https://github.com/canonical-web-and-design/meeting-notes/issues/415

- Is the star needed? Does it add any value?
- 001 good balance but font sizes being the same causes battle hierarchy
- 004 badge favored exploration
- Try adding installs/trending under Snap store button

**Comment by therealjuan** [comment]
004 makes sense but we still need to know how to communicate if a snap is trending or is popular which are "transient" events that could affect the badge.

**Comment by kwm14** [comment]
## Further exploration
Explored a few more variations based on feedback, testing on both black and white versions of the buttons we have.

### 005
- Removing icons
- Focusing on keywords 'Trending' or '(x) installs'
![snap-badge-rating-005](https://user-images.githubusercontent.com/17748020/61724241-7bb0d780-ad65-11e9-892d-db27e1a152f2.png)

### 006
- Adding data below button
- Events added won't increase the length of the button 
- Colours used from Snapcraft brand guidelines 
![snap-badge-rating-006](https://user-images.githubusercontent.com/17748020/61724242-7c496e00-ad65-11e9-8f7f-ec71e00705cc.png)

### 007
- Same as above but with icons added which can be reflected on snap listing page 😉 
![snap-badge-rating-007](https://user-images.githubusercontent.com/17748020/61724245-7c496e00-ad65-11e9-8810-2399d79e4d8e.png)

### 008
- Trending badges, something different...
- Tooltip on hover to display event/data
![snap-badge-rating-008](https://user-images.githubusercontent.com/17748020/61724246-7c496e00-ad65-11e9-9347-ca8b3b7c0d8f.png)

**Comment by therealjuan** [comment]
I have the feeling that 007  makes sense and would be good if this tag is detachable so we can add it to detail pages :)

**Comment by kwm14** [comment]
Ok great. I will explore using that tag on the details pages 👍 @spencerbygraves 007 work for you visually?

**Comment by spencerbygraves** [comment]
@kwm14 @therealjuan I'm not totally convinced by the trending icon in 007, especially when used on it's own in your details page example. Might something with an arrow be clearer?

![image](https://user-images.githubusercontent.com/9105999/61808417-3d81e980-ae33-11e9-8ac8-fabb95ed553a.png)

**Comment by kwm14** [comment]
@spencerbygraves the icon is defined yet. It's a placeholder for now until we lock down the style and look of the snap store button 😃

**Comment by spencerbygraves** [comment]
@kwm14 oh, ok. Thanks!

**Comment by therealjuan** [comment]
I'll work out some icons for trending and popular apps even if they are placeholders for now. 

Just for the record that my original proposal looks very familiar!
![image](https://user-images.githubusercontent.com/8167677/61866537-360f1e80-aecd-11e9-9e66-56693dc5be6f.png)


As commented by @cassiocassio on the [design proposal](https://docs.google.com/document/d/14LWGpoxWLo5A66rzxdk_Lpa4dU-yzojDHCV87Cf1-w0/edit#heading=h.17b7d6xrozfw) the star could be misleading and confused with reviews.

Watch the space!

**Comment by therealjuan** [comment]
Popular
![Crown](https://user-images.githubusercontent.com/8167677/61868781-11697580-aed2-11e9-8a09-0a3de6a404a4.png)

Trending
![Trending](https://user-images.githubusercontent.com/8167677/61868782-11697580-aed2-11e9-9f7a-ec3eaa5655e0.png)

Fresh from the oven!

**Comment by cassiocassio** [comment]
Popular:
===
Very Royalist, Mr Real.

Diamond
?
Laurel Wreath
?

Google have a trends thing:
I feel the zig zig arrow is inevitable, although the on-fire thing has an early-days of the internet appeal.

![images.png](https://images.zenhubusercontent.com/59391bc151aa2c305780dbd6/07211e0a-c144-4115-8065-72eb25157c30)

**Comment by kwm14** [comment]
@therealjuan not sure on the crown icon for popular either. Sorry!

A suggestion of a heart or even the snap bag 🤔 

![snap-badge-installs-001](https://user-images.githubusercontent.com/17748020/61878951-f0148380-aee9-11e9-91c8-4774735345b2.png)

**Comment by kwm14** [comment]
> Popular
> ![Crown](https://user-images.githubusercontent.com/8167677/61868781-11697580-aed2-11e9-8a09-0a3de6a404a4.png)
> 
> Trending
> ![Trending](https://user-images.githubusercontent.com/8167677/61868782-11697580-aed2-11e9-9f7a-ec3eaa5655e0.png)
> 

@therealjuan can you send these as SVGs so I can drop them into buttons to see how they will look in situ 😉

**Comment by kwm14** [comment]
Another go 😉 for **Popular**
- Flame - Hot snap #popular
- Star - Different to rating. Top snap #popular

![snap-badge-installs-002](https://user-images.githubusercontent.com/17748020/61957227-ac3b8000-afb6-11e9-8828-c073d4ea36a7.png)

**Comment by therealjuan** [comment]
Let's go with the snap bag for now for popular and the chart for trending. We will change accordingly once we get the icons.

Ship it!

**Comment by kwm14** [comment]
## Signed off designs
**Dark**
![snap-badge-installs-dark](https://user-images.githubusercontent.com/17748020/62616447-71670f80-b907-11e9-80a6-b867272d4f26.png)

**Light**
![snap-badge-installs-light](https://user-images.githubusercontent.com/17748020/62616448-71ffa600-b907-11e9-9da3-dccbbf849437.png)
