### ISSUE TITLE
Trending: Indicate popular or trending snaps on detail pages

### ISSUE THREAD

**Issue by therealjuan** [canonical-web-and-design/snapcraft.io#2094]
It will be good to showcase how some snaps are trending or popular within their detail pages:

![image](https://user-images.githubusercontent.com/8167677/61447467-4c5b2e80-a951-11e9-9978-a9307c11e3cd.png)

![image](https://user-images.githubusercontent.com/8167677/61447480-51b87900-a951-11e9-9d02-458e7df9586e.png)

**Comment by kwm14** [comment]
## Initial explorations
A first pass at adding trending/install information to snap details.

### 001
![snap-badge-details-001](https://user-images.githubusercontent.com/17748020/61451634-c095d200-a951-11e9-9346-b7ef6a66c1c4.png)

### 002
![snap-badge-details-002](https://user-images.githubusercontent.com/17748020/61451737-03f04080-a952-11e9-9e67-62c24cba0c5e.png)

### 003
![snap-badge-details-003](https://user-images.githubusercontent.com/17748020/61451639-c095d200-a951-11e9-8ac9-eb5236560e28.png)

### 004
![snap-badge-details-004](https://user-images.githubusercontent.com/17748020/61451642-c12e6880-a951-11e9-8879-42947c5f146c.png)

**Comment by kwm14** [comment]
## Design review
Weekly meeting notes can be found here https://github.com/canonical-web-and-design/meeting-notes/issues/415

- Is the star clickable? Is this surfaced based on (x) installs?
- Regular font-weight not working
- If we want to use icons keep them to the right of the text
- 003 favored exploration but version/install buttons back to the right so it's consistent with JAAS
- Dots preferred over lines for dividers

**Comment by therealjuan** [comment]
A few comments: 

* I would probably avoid changing the install and channel map buttons
* Using dots makes sense
* I am missing how to communicate a snap is "trending this month" or popular using icons next to the snap title maybe?
* 004 with dots seems the best one

**Comment by kwm14** [comment]
## Further exploration
Explored a few more variations based on feedback, applying the [proposed snap button](https://github.com/canonical-web-and-design/snapcraft.io/issues/2093#issuecomment-514259919) from exploration 007.

### 005
![snap-badge-details-005](https://user-images.githubusercontent.com/17748020/61799918-eb859780-ae23-11e9-8f74-90072e028e9c.png)

### 006
![snap-badge-details-006](https://user-images.githubusercontent.com/17748020/61799919-eb859780-ae23-11e9-925b-a1855103d109.png)

@therealjuan @spencerbygraves thoughts?

### 007
![snap-badge-details-007](https://user-images.githubusercontent.com/17748020/61799920-ec1e2e00-ae23-11e9-9fa0-1ca8e225bc95.png)

### 008
![snap-badge-details-008](https://user-images.githubusercontent.com/17748020/61799922-ec1e2e00-ae23-11e9-9e1b-cc2fef24ece8.png)

### 009
![snap-badge-details-009](https://user-images.githubusercontent.com/17748020/61799923-ec1e2e00-ae23-11e9-95a6-f61c67b0635d.png)

**Comment by spencerbygraves** [comment]
@kwm14 I prefer 005 and 009 too.

**Comment by kwm14** [comment]
Thanks, @spencerbygraves @therealjuan 👍 

Signed off proposals without icons as we're still identifying which will be best suited [here](https://github.com/canonical-web-and-design/snapcraft.io/issues/2093).

![snap-badge-details-proposal-001](https://user-images.githubusercontent.com/17748020/61944179-fb70b900-af94-11e9-82b8-eb50f3442cfc.png)

![snap-badge-details-proposal-002](https://user-images.githubusercontent.com/17748020/61944180-fb70b900-af94-11e9-9a5c-45794bca73eb.png)
