### ISSUE TITLE
Error: Banner-02.png (740 x 240 pixels) does not have the correct aspect ratio: it needs to be 3:1 (e.g., 720 x 240 pixels)

### ISSUE THREAD

**Issue by tomasbulva** [canonical-web-and-design/snapcraft.io#2097]
Trying to upload banner to the snapstore listing of my snap
and getting following error: 
Banner-02.png (740 x 240 pixels) does not have the correct aspect ratio: it needs to be 3:1 (e.g., 720 x 240 pixels)

### Expected behaviour
Being able to upload banner

### Steps to reproduce the problem
drop banner-file on the drag target for banner in the listing details form

### Specs

- _URL:_ https://snapcraft.io/lynxwallet/listing
- _Operating system:_ osx mojave 10.14.5
- _Browser:_ Google Chrome Version 75.0.3770.142 (Official Build) (64-bit)

**Comment by therealjuan** [comment]
Hello @tomasbulva. Thanks for bringing to our attention. 

We only allow uploaded images to be 3:1 aspect ratio. In your particula case, it means that the storefront will allow an image of 720x240 instead of 740x240.

Let us know if you have any further problems.
