### ISSUE TITLE
Docs: /docs Using > The /snap directory 404's

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2104]
Seems to forward to the same url without `/docs` at the start of the path.

**Comment by jpmartinspt** [comment]
@anthonydillon actually meant that the "The /snap directory" link in the side nav 404's. Should be fixed by #2103.

**Comment by Lukewh** [comment]
That's what I meant... I just was giving the path in the sidenav because it took me so long to scan down the list and find it when I first read his comment :D

**Comment by jpmartinspt** [comment]
Will be fixed bu #2103.
