### ISSUE TITLE
Unclear how to log in to build.snapcraft.io

### ISSUE THREAD

**Issue by OddBloke** [canonical-web-and-design/snapcraft.io#2115]
### Expected behaviour

I would like a clear indicator of how to login.

I only visit the site occasionally when I need to manually kick off a snap build (normally prompted by a security warning email). When I look at the page, there are two options that present themselves to me "Set up in minutes :octocat:" (which I disregard, because I'm already set up) and "Developer account" (which I click on because for some reason I think that I want to log in to my snapcraft developer account to do snapcraft things as a developer). Then I'm presented with a list of snaps, this is going great, but when I click through to the snap in question, and keep clicking on things, I never find my way to something that lets me build my snaps. This is frustrating!

(Of course, I eventually work out that :octocat: is code for "click this to just login with Github as well" and get on with things, but this was a couple of frustrating minutes that I think would put off plenty of users!)

### Steps to reproduce the problem

1) Navigate to build.snapcraft.io

**Comment by solazio** [comment]
@OddBloke thanks for this. You can now build snaps by accessing the `Builds` tab once you click on your snap. Therefore I'm closing this issue.
