### ISSUE TITLE
To display snap name like publisher names

### ISSUE THREAD

**Issue by therealjuan** [canonical-web-and-design/snapcraft.io#2124]
Following the [thread on user naming](https://forum.snapcraft.io/t/how-to-display-account-names-and-usernames/4007) and how to display when the publisher name and username is similar, we should have the same logic with snap names:

* When space is tight (e.g. snap find), we display: blender
* When there is space (e.g. snap info, web), we display: Blender Foundation (blender)
* When there is space but username and display name match: Blender instead of Blender (blender)

**Comment by solazio** [comment]
We currently display:

- All screen sizes (e.g. snap find): Blender Foundation
- All screen sizes (e.g. snap info): Blender Foundation (blender)

This is a consistent way of displaying this info, therefore closing.
