### ISSUE TITLE
Parses invalid Markdown emphasis

### ISSUE THREAD

**Issue by robert-ancell** [canonical-web-and-design/snapcraft.io#2127]
The following is [not valid emphasis markdown](https://spec.commonmark.org/0.29/#example-378) (the whitespace should stop this being parsed), but is shown in bold on snapcraft.io:
```
** Foo **
```

For an example see the first line of the description of [Word Salad](https://snapcraft.io/word-salad).

**Comment by jkfran** [comment]
Hi, we are going to close this issue as we are using the https://github.com/lepture/mistune parser and this rule doesn't apply.
