### ISSUE TITLE
[Vanilla] Blog

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2132]

**Comment by bartaz** [comment]
@kwm14 I don't see anything obviously broken to fix, can you give it a look as well?

Demo: https://snapcraft-io-canonical-web-and-design-pr-2144.run.demo.haus/blog

**Comment by kwm14** [comment]
## Design review
- Looking good to me @bartaz 
- One update could be to use https://docs.vanillaframework.io/patterns/pagination/ instead of the current page pagination at the bottom of the page
