### ISSUE TITLE
[Vanilla] First snap flow

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2134]
- [ ] stepped list using circles and getting ovals (https://github.com/canonical-web-and-design/vanilla-framework/issues/2424)
- [x] accordion looking weird with numbers and icon on left
- [x] code lines in annotated snapcraft yaml have unnecessary background and have broken line breaks (https://github.com/canonical-web-and-design/snapcraft.io/pull/2145)

**Comment by bartaz** [comment]
@kwm14 

We are using accordion pattern in stepped instructions, and now with Vanilla 2.0 update it started to look a bit weird with +/- icons moved to the left. They are now close to step numbers making them look weirdly 'mathy'.
Any tips on how to fix that? Or is it ok to leave it as is?

<img width="1151" alt="Screenshot 2019-08-06 at 17 07 48" src="https://user-images.githubusercontent.com/83575/62551877-079a2780-b86d-11e9-8d11-8c7b384f13c0.png">

**Comment by kwm14** [comment]
@bartaz it does look funky...

How about this?

<img width="485" alt="Screenshot 2019-08-07 at 11 06 02" src="https://user-images.githubusercontent.com/17748020/62614496-67dba880-b903-11e9-9325-0294f0599865.png">
