### ISSUE TITLE
“Was this helpful?”

### ISSUE THREAD

**Issue by therealjuan** [canonical-web-and-design/snapcraft.io#2151]
@evandandrea commented on [Mon Nov 05 2018](https://github.com/canonical-web-and-design/docs.snapcraft.io/issues/61)

Advocacy would like a widget to solicit feedback, at the bottom of every docs page, on the rough edges in our documentation. Something like:

>We’re currently running an initiative to improve our documentation and would appreciate your feedback on the current material. Was this document helpful? [ yes ] [ no ]

For comparison, Visual Studio Code is a good example of this increasingly standard pattern:
https://code.visualstudio.com/docs

---

@evandandrea commented on [Sat Nov 10 2018](https://github.com/canonical-web-and-design/docs.snapcraft.io/issues/61#issuecomment-437568465)

@therealjuan has something we can use from maas.io

---

@evandandrea commented on [Fri Dec 07 2018](https://github.com/canonical-web-and-design/docs.snapcraft.io/issues/61#issuecomment-445178805)

It's Usabilla. You can see it live on the first-snap flows: https://snapcraft.io/first-snap

**Comment by lilyvidenova** [comment]
As we currently don't have an in-page widget to collect feedback, I'd like to propose a [pop-up one](https://app.usabilla.com/member/live/campaign/5ebe8c033544ec673b57e1b1).

![image](https://user-images.githubusercontent.com/17980375/82050904-d4fd4500-96b0-11ea-8953-263ee6fd7247.png)

It will show up when a user gets to the bottom of a page on docs (we have other options for control too, I'll be happy to discuss how exactly we do it). 

@igorljubuncic @popey could you take a look?

**Comment by lilyvidenova** [comment]
The second step after clicking Continue (managed to not upload the screenshot earlier...):

![image](https://user-images.githubusercontent.com/17980375/82059477-fe709d80-96bd-11ea-82be-177b69b3cb74.png)
