### ISSUE TITLE
Username links are broken

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#2152]
Related to canonical-web-and-design/docs.snapcraft.io#66 if you visit a page generated from the forum which contains references to users, those links are broken. 

https://docs.snapcraft.io/process-for-reviewing-classic-confinement-snaps/1460 for example has links to myself as https://docs.snapcraft.io/u/popey which is a broken link. It seems they're not being translated correctly by the machinery that converts forum posts to docs.

**Comment by Lukewh** [comment]
@popey When we migrated to snapcraft.io/docs I'm pretty sure we removed the ability to hand craft links. Please reopen if this is still an issue.
