### ISSUE TITLE
No visible effect from <strong> CSS in Firefox

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/snapcraft.io#2154]
[The docs.snapcraft.io front page](https://docs.snapcraft.io/), like most pages in the Docs section, is generated from [a Discourse post](https://forum.snapcraft.io/t/snap-documentation/3781).

This particular post relies on bold to convey meaning in two ways.

Definitions:
> - **snap** is both the command line interface and the application package format
> - **snapd** is the background service that manages and maintains your snaps
> - **snapcraft** is the command and the framework used to build your own snaps
> - **[Snap Store](https://snapcraft.io/store)** provides a place to upload your snaps, and for users to browse and install

And table headers:
> **Discovering snap:**
>…
> **Advanced features:**
>…
> **Building your own snaps:**

However, when published on docs.snapcraft.io, the bold is ~~discarded~~ not shown in Firefox. This makes the page structure a bit less obvious (or interesting) than it would be otherwise.

Some possible solutions:

* ~~The docs.snapcraft.io Markdown conversion should preserve bold formatting.~~ _Edit: Not a problem with the Markdown conversion._

* @degville should switch from using bold here to other formatting, such as `_`italics`_` for the defined terms, and `##`subheadings for the table headers.

* ~~The front page in particular should no longer be generated from a Discourse post. (We could end up switching that anyway, for navigation reasons. But it’s not a solid fix for this issue, because other pages might reasonably use bold in similar ways.)~~ _Edit: Not a problem with the Markdown conversion._

* The CSS should be fixed so that the bold styling is visible.

**Comment by solazio** [comment]
@matthewpaulthomas and @anthonydillon this looks good in Firefox now.

![image.png](https://images.zenhubusercontent.com/5cb4608f97df763a9090bdec/ea65306a-bc28-4b0e-8083-5b06edb14d2f)

Closing...

**Comment by matthewpaulthomas** [comment]
The problem has not improved since I reported it. In Firefox 72.0.1:

> ![image](https://user-images.githubusercontent.com/19801137/72329452-ac3a5400-36ac-11ea-85b9-7b1d9991de40.png)

Similarly in search results, matching text in the extracts is not bold:

> ![image](https://user-images.githubusercontent.com/19801137/72329874-72b61880-36ad-11ea-960a-b5d4e7d648d8.png)

I would understand, though, if you decided to close it on the grounds that it’s a Vanilla bug and you don’t want to fix it locally.

**Comment by Lukewh** [comment]
I think you're correct @matthewpaulthomas this is still a problem that needs a Vanilla fix. I'd worry about straying from "The Vanilla Path" :tm: locally, so I'll close this issue. If this is some kind of configuration that can be changed on others machines and you know how to change it you could add something to the vanilla issue - I'd be happy to fire up a VM and twiddle.
