### ISSUE TITLE
No Qt / QtQuick / QML specific docs

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#2156]
NPS feedback.
External report that there's not a clear way to package Qt / QtQuick / QML applications as snaps. 

From my perspective, it's certainly not straightforward if you're dependent on a newer version of the Qt libs available in 18.04. However even if you use the shipped versions, we don't have specific details targeting developers of Qt based applications.

**Comment by Lukewh** [comment]
Would this be covered, in-part, by https://snapcraft.io/docs/t/desktop-app-support-qt/6833 ?
Could those documents be expanded to include QtQuick and QML?
Who's the best person to assign this issue to?

**Comment by jkfran** [comment]
@degville do you know if this can be closed?

**Comment by degville** [comment]
> @degville do you know if this can be closed?

Yes, I think so.
