### ISSUE TITLE
No simple bash script docs

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#2157]
NPS Feedback
Some people want to use snaps to package up simple shell scripts. I covered this in a snapcraft live some weeks back, but that's lengthy. It might be prudent for us to have a simple guide to packaging up shell scripts. Especially given bash is shipped in core, so the dependencies (other than what are needed by the application functionality) are already covered.

As a bonus, it may be nice to cover adding Yad / dialog / similar tools to enable people to create simple graphical snaps with just shell scripts and simple gui packages.

**Comment by Lukewh** [comment]
Who would be the best person to assign this issue to?
Where are documentation issues tracked more generally?

**Comment by degville** [comment]
I've added this to the docs roadmap on the forum. https://forum.snapcraft.io/t/the-docs-roadmap/8763
