### ISSUE TITLE
No Python / GTK specific docs

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#2159]
NPS feedback
Developer wanted to create a snap based on a python / GTK application. They found the documentation scattered around a lot of places. 

This could be a use case we could do a specific doc for, as it's quite a common combination of technologies in the Linux world.

**Comment by degville** [comment]
I've added this as an item on the docs roadmap forum post. https://forum.snapcraft.io/t/the-docs-roadmap/8763
