### ISSUE TITLE
Docs: broken link to "Permission requests"

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/snapcraft.io#2162]
Clicking on "Permission requests" on snapcraft docs (https://snapcraft.io/docs/process-for-aliases-auto-connections-and-tracks) leads to forum post: https://forum.snapcraft.io/t/process-for-aliases-auto-connections-and-tracks/455

**Comment by nottrobin** [comment]
The docs system will only display content on https://snapcraft.io/docs that is in [the "doc" category](https://forum.snapcraft.io/c/doc). Any links to topics in other categories (as with this post which is in the "store-requests" category) will always forward you over to the forum post.

The fix here is either to move the topic to the "doc" category, link to a different topic instead, remove the link from the side-nav, or simply accept that it will forward you over to the forum.

**Comment by therealjuan** [comment]
Just going for a different approach after discussing with @degville:

We will create a page containing compiled documentation from the forum post for this topic and tagged as #doc so it can work as the other posts. This will make us accept the issue has been happily solved :)

**Comment by Lukewh** [comment]
This seems fixed - closing.
