### ISSUE TITLE
Searching for "go" returns the snap named "go" in the 7th row of results

### ISSUE THREAD

**Issue by OddBloke** [canonical-web-and-design/snapcraft.io#2173]
### Expected behaviour

First row, probably just plain first?

### Steps to reproduce the problem

Search for "go"

![go-search-lol](https://user-images.githubusercontent.com/62736/62812602-77f6b200-bad4-11e9-9824-63e479c67d32.png)

**Comment by Lukewh** [comment]
Thanks for the report @OddBloke. Examples like this will inform our rules when we get to improving search results. Unfortunately it's not been a priority thus far, but we're aware search results aren't ideal.

**Comment by Lukewh** [comment]
@OddBloke the store have updated the API and queries like this now prioritise exact matches :+1:

**Comment by OddBloke** [comment]
LGTM now, thank you!
