### ISSUE TITLE
Vanilla 2.0 - Revisit fluid grid

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/snapcraft.io#2174]
Our custom fluid grid component can be (in theory) replaced by Vanilla patterns.
We should explore if Vanilla 2.0 grid or inline images patterns could help with replacing flexible grid.

**Comment by Lukewh** [comment]
From @lyubomir-popov https://codepen.io/lyubomir-popov/pen/ympBrJ

**Comment by lyubomir-popov** [comment]
Please let me know if you run into issues with the above implementation. I'm happy to dial things in to accomodate specific guidelines/min sizes etc.
