### ISSUE TITLE
Ubuntu install of Serveo fails

### ISSUE THREAD

**Issue by gshafer** [canonical-web-and-design/snapcraft.io#2188]
### Expected behaviour

Install serveo on Ubuntu

### Steps to reproduce the problem

Follow directions here: https://snapcraft.io/install/serveo/ubuntu

### Specs

- _URL:_ https://snapcraft.io/install/serveo/ubuntu
- _Operating system:_ Ubuntu 16
- _Browser:_

**Comment by therealjuan** [comment]
Hello @gshafer 

Thanks for bringing this into our attention. There seems to be a problem with the `serveo` snap as I couldn't get it installed in a fresh ubuntu instance. Have you tried installing a different snap on your system?

**Comment by gshafer** [comment]
I installed “hello” this morning and it installed and ran fine. Looks like serveo snap is the problem.

**Comment by therealjuan** [comment]
I will be closing the issue. We would like to contact the developer but there is no contact available and get you posted in case we get a resolution. Thanks for raising the problem.
