### ISSUE TITLE
Automatically trigger the tour on snap listing page

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/snapcraft.io#2201]
- [ ] define what triggers the tour and how do we check it programatically
- [ ] store tour state in local storage (if completed, skipped) - how do we know if we should show it again?
- [ ] implement automatic trigger for the tour

**Comment by bartaz** [comment]
@hughesjordan Question about how we trigger tour automatically by "50% of listing fields incomplete". Which fields do we consider:

- snap icon: we can check if they have icon or not
- snap title: snap always has a title (it may default to package name, but is never empty)
- category:  we can check if they have category or not
- video:  we can check if they have category or not
- images:  we can check if they have images or not
- banner:  we can check if they have banner or not
- summary and 
- description - both are mandatory in snapcraft.yaml, so will never be empty
- contact (developer website and contact) - two fields, but should we consider them as one (we do in the tour), so if one is filled we count it as filled?
- license: we don't show it in tour, so not sure if we consider it for counting?

So, excluding fields that always have a value we end up with:
icon, category, video, images, banner, contact (2 combined or separate).
Which gives us 6 (or 7 fields if we treat 2 contact fields separately). So if any user only has 2 (or 3 in case of contact fields separate) we show the tour?

**Comment by hughesjordan** [comment]
@bartaz Yep, let's go with the fields you have specified above and treating the contact fields as combined.

Thoughts on treating summary and description as 'incomplete' if they are under a certain character limit? Or in the case of the summary field, if it matches the snap name? (only for the purpose of triggering the tour) This could perhaps help to drive better utilisation of these fields
