### ISSUE TITLE
Metrics showing inaccurate values 

### ISSUE THREAD

**Issue by therealjuan** [canonical-web-and-design/snapcraft.io#2207]
![image](https://user-images.githubusercontent.com/8167677/63527434-0289d900-c4f9-11e9-8ffb-98e3d7af69f2.png)

There are some instances where the tooltip is not showing accurate values on metrics and probably it has to do with some data that has changed or we haven't updated.

[Raised in the forum in here](https://forum.snapcraft.io/t/by-channel-metric-not-showing-accurate-references/12897)

**Comment by jkfran** [comment]
This issue seems to solve. Please reopen if not.
