### ISSUE TITLE
Can't report a non-functioning snap

### ISSUE THREAD

**Issue by PJaros** [canonical-web-and-design/snapcraft.io#2211]
I wanted to report a problem with a a snap-app on this [page](https://snapcraft.io/tic80). Which crashes after installing and running it. I wanted to report the problem. I need to select a "reason", but the only reasons available are:
- "Copyright or trademark violation"
- "Snap Store terms of service violation"

There is no way for me to report that the app isn't functioning.

Here is what happens on the CLI:

```
madmike@desktop:~/git/TIC-80$ snap find tic-80
Name   Version  Herausgeber    Hinweise  Zusammenfassung
tic80  0.50.1   typicalncoder  -         TIC-80 is a fantasy computer for making, playing and sharing tiny games.
madmike@desktop:~/git/TIC-80$ sudo snap install tic80
tic80 0.50.1 aus Sturov Fedor (typicalncoder) installiert
madmike@desktop:~/git/TIC-80$ tic80
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

**Comment by therealjuan** [comment]
Thanks for bringing this into our attention. Unfortunately we are not owners of the snap so there is little we can do with the snap. I would suggest that you can contact the packager of the snap with your problem in the following address: sturov.fedor@yandex.ru

Alternatively, we create a [new issue](https://github.com/canonical-web-and-design/snapcraft.io/issues/2214) on snapcraft.io to make sure we message publishers to encourage providing ways to contact them to avoid cases like this.

Thanks again!

**Comment by PJaros** [comment]
You should really give your users a easy way to report bad or broken software and pull the plug on those with with serious problems.

Bad software will reflect badly on the platform deliverying it.
