### ISSUE TITLE
Encourage publishers to provide contact details

### ISSUE THREAD

**Issue by therealjuan** [canonical-web-and-design/snapcraft.io#2214]
There are some cases where snaps are malfunctioning and sometimes this creates a confusion on visitors that might be a problem with the store. As we don't take ownership of this problem as it is due to the packager of the snap... It will be good to:

- Encourage publishers on the listing page of a snap to provide contact details. What it means is to showcase a warning style message on contact details to make sure publishers provide ways to contact them in case of problems

- Include a message on snap listing pages with no contact details that if there are problems with a given snap, this is due to the publisher and the store has little to do with it

**Comment by danielmutis** [comment]
We are working on solving this issue by allowing publishers to add links to their metadata.
