### ISSUE TITLE
Snap homepage shows unsupported architectures

### ISSUE THREAD

**Issue by AlanGriffiths** [canonical-web-and-design/snapcraft.io#2218]
### Expected behaviour

The architectures shown on the snap homepage should match those in the /releases management page.
 
### Steps to reproduce the problem

While experimenting with the build.snapcraft service I inadvertently built mir-test-tools for s390x which got pushed to latest/edge automatically. That build is unwanted, has incorrect content, and I have no capability for, nor interest in, supporting s390x for this snap.

On the /releases management page I closed the channel and re-publish the non-s390x revisions and that page shows the intended architectures.

I don't get USN notification emails from the store about this s390x release, so I assume it isn't actually in the store.

However, the "Show architectures" dropdown on  https://snapcraft.io/mir-test-tools still shows s390x.

**Comment by bartaz** [comment]
Thanks for reporting this.

It seems that `channel_map` returned by the store API still contains signs of s390x release (released to latest/edge in Feb 2019):

```
[
  # many other releases...
  # ...
  {
    channel: {
      architecture: "s390x",
      name: "edge",
      "released-at": "2019-02-12T15:17:19.272832+00:00",
      risk: "edge",
      track: "latest"
    },
    confinement: "strict",
    "created-at": "2019-02-12T15:09:33.576184+00:00",
    download: {
      deltas: [],
      "sha3-384":
        "610b4b76bb2232d6cace6277123f83aefa595b1b3666ed597258ae7f3b8b391f57b5941a9331816411e85c5505f82e75",
      size: 110870528,
      url:
        "https://api.snapcraft.io/api/v1/snaps/download/yKN3pQpV784MwUBgiDYlYhccSnLhxZQD_29.snap"
    },
    version: "0.26.3+16.04.20170605"
  }
];

```

@cprov Do you know why this may be the case if the channel with s390x release was closed and then repopulated with other architectures?

**Comment by Lukewh** [comment]
Reported to the store team: https://bugs.launchpad.net/snapstore/+bug/1842631

**Comment by Lukewh** [comment]
This seems to have been a caching issue. Everything seems to be in order now.
