### ISSUE TITLE
Discourse body limit hit for docs

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/snapcraft.io#2234]
After adding a few new URLs to the mapping table on https://forum.snapcraft.io/t/snap-documentation/11127, and attempting to save, the procedure fails with the following error:

`Body is limited to 32000 characters, you entered 32454.`

![Screenshot_20190906_132029](https://user-images.githubusercontent.com/7047542/64427407-19a7f980-d0a9-11e9-8d88-85ba35dc92f4.png)

(this is the meta-topic used to expose documentation topics at their correct URLs).

**Comment by nottrobin** [comment]
I think we'd need to ask IS to install something like https://github.com/jomaxro/discourse-plugin-site-setting-override.

Until then, is there any way to reduce the length of that post?

**Comment by degville** [comment]
@nottrobin and I had a brief discussion about this on IRC. I've agreed to make an RT to increase the post limit to 99k in the first instance, but there was some discussion about whether the publishing scripts should be aware of the limit, whether we should be increasing the post limit (we don't want to encourage large posts) or who should own the landing page and its character limits. Ultimately, though, it's a Discourse limit rather than a limitation of the implementation.

**Comment by galgalesh** [comment]
Any progress on this? This is holding up a bunch of improvements to the docs.

**Comment by nottrobin** [comment]
@galgalesh oh aye, I think it's solved (in https://portal.admin.canonical.com/C121172/, for internal people).
