### ISSUE TITLE
TypeError: Object doesn't support property or method 'scrollTo'

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2237]
https://sentry.is.canonical.com/canonical/snapcraft-io/issues/4027/?referrer=github_plugin

```
TypeError: Object doesn't support property or method 'scrollTo'
  at animateScrollTo (./static/js/public/scroll-to.js:10:21)
  at Anonymous function (./static/js/public/scroll-to.js:24:9)
  at d (/static/js/modules/raven.min.js:2:4663)
```

**Comment by bartaz** [comment]
Edge doesn't support `scrollTo` in current version, need to fallback to `scrollTop`: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15534521/
