### ISSUE TITLE
Metrics: Investigate Public snap details page

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/snapcraft.io#2244]
## Public snap details page
- [x] "Territories" World map with tooltip on hover (without numbers)
- [x] Logarithmic "Users by distribution" - vertical bar chart

**Comment by kwm14** [comment]
## Map chart usage review
In regards to the map chart, this is replicated on the publishers snap metrics page so we can update with my [suggestions](https://github.com/canonical-web-and-design/snapcraft.io/issues/2243#issuecomment-530890888).

**Comment by Lukewh** [comment]
> Currently we're not showing any numbers, so it would be good to surface that or as a percentage similarly to u.com, if the data is available? @Lukewh @bartaz

We don't show any data publicly as there is a risk people could reverse engineer the data to get (even rough) estimates of the number of users a snap has. We keep the numbers in the publisher area for publishers eyes only.

**Comment by kwm14** [comment]
> We don't show any data publicly as there is a risk people could reverse engineer the data to get (even rough) estimates of the number of users a snap has. We keep the numbers in the publisher area for publishers eyes only.

Ahhhhhh I see, that makes sense 👍Guessing the same rules apply for 'Users by distribution (log)', hence why it isn't displaying any data?

**Comment by Lukewh** [comment]
> Ahhhhhh I see, that makes sense +1Guessing the same rules apply for 'Users by distribution (log)', hence why it isn't displaying any data?

+1

**Comment by kwm14** [comment]
## Review
As we can't display any data to the public, is it worth having these metrics on this page?

Removing would bump up **'Install Spotify on your Linux distribution'** section which is getting a lot of traction based on David Calle's lightning talk in Paris 👍 

@Lukewh @bartaz Maybe we can track some snap pages with CrazyEgg to see if people are engaging with the metrics? Or can we remove?

**Comment by Lukewh** [comment]
@kwm14 we could certainly add tracking to see how many people are engaging. We should also be able to see how many people are clicking on the distro specific links.

David Calle's talk was highlighting how those pages do well for Google search results, I'm not sure the value in bumping them up the page - though this could be an interesting A/B test.

**Comment by bartaz** [comment]
We can bump the links above graphs without removing them. (or A/B test both versions by first measuring current one).

The graphs are meant to give a 'feeling' of where the snap is popular without giving any specific numbers. It's certainly more important to publishers (and that's why they get specific numbers and detailed graphs), but for users it may be interesting as well to see that given snap is actively used around the world and in wide range of distros.

**Comment by kwm14** [comment]
Thanks, @Lukewh @bartaz for your comments 👍 

## Next steps
Work to be carried out next cycle 20.04.
- Add tracking to see how many people are engaging
- See how many people are clicking on the distro-specific links
- Referenced a [filed issue](https://github.com/canonical-web-and-design/snapcraft.io/issues/2000#issuecomment-503554122) where distro logs are too long, design proposal can be found here as a first pass to fix
- As we can't show numbers for a public-facing snap we can implement more/less bar chart seen on ubuntu.com

![snap-details-001](https://user-images.githubusercontent.com/17748020/65695376-5a26e180-e06f-11e9-99b7-005fca15a1d2.png)
