### ISSUE TITLE
Webfont swap

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/snapcraft.io#2289]
Use `font-display: swap` (or optional).

Fallback font may need some tweaking:

![swap](https://user-images.githubusercontent.com/83575/66196780-6aefdc80-e699-11e9-973e-8bb58b450e04.gif)

**Comment by barrymcgee** [comment]
@spencerbygraves

**Comment by spencerbygraves** [comment]
@bartaz @barrymcgee thanks for the demo. Would we need to decide between swap and optional in [Vanilla first](https://github.com/canonical-web-and-design/vanilla-framework/issues/2569)?

**Comment by barrymcgee** [comment]
@spencerbygraves Yes - but Vanilla is currently blocked so we're adding the change to sites in the meantime until Vanilla is updated.

**Comment by spencerbygraves** [comment]
@barrymcgee ok, can we track the decision in the Vanilla issue though? Just so we have it noted.

**Comment by kwm14** [comment]
@spencerbygraves an issue has been created on Vanilla board 😉 https://github.com/canonical-web-and-design/vanilla-framework/issues/2569

**Comment by bartaz** [comment]
We will wait for vanilla to implement it
