### ISSUE TITLE
Base 64 encoded image embedded in CSS

### ISSUE THREAD

**Issue by jkfran** [canonical-web-and-design/snapcraft.io#2296]
### Expected behaviour
For performance reasons, we should not have base64 embedded images.

### Steps to reproduce the problem
https://github.com/canonical-web-and-design/snapcraft.io/blob/578929e9b8ce01f3e26bd5365afc588719f343cf/static/sass/_snapcraft_release.scss#L501

**Comment by bartaz** [comment]
Good catch @jkfran, thanks!
