### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by omichel** [canonical-web-and-design/snapcraft.io#2299]
### Expected behaviour
I would like to login with my "cyberbotics" account and display the normal Account Details and other pages, but that fails.

### Steps to reproduce the problem
1. Log with with "cyberbotics" account (e-mail is webmaster@cyberbotics.com).
2. I get this message:
```
Bad Gateway
Please try again later

You can check the service status at status.snapcraft.io.

If the problem persists please check the Snapcraft forum or report an issue.
```

### Specs

- _URL:_ https://snapcraft.io/account/details
- _Operating system:_ Windows 10 (latest version)
- _Browser:_ Firefox (latest version)

**Comment by jpmartinspt** [comment]
Hi @omichel, are you still unable to login?

**Comment by omichel** [comment]
Hi, yes I am still getting the same "Bad gateway" message.

**Comment by jpmartinspt** [comment]
Can you please log in into [login.ubuntu.com](https://login.ubuntu.com/), go to the personal details tab and check if you have an username set in there? If you don't could you try setting one and the retry logging in to [snapcraft.io](https://snapcraft.io?

**Comment by omichel** [comment]
I do have a username:
![image](https://user-images.githubusercontent.com/1264964/66388029-93434800-e9c5-11e9-9c67-5ed0ef25980b.png)

**Comment by omichel** [comment]
It works from my other user account, but not from cyberbotics:
![image](https://user-images.githubusercontent.com/1264964/66388588-bfab9400-e9c6-11e9-9f1b-88cba166be4f.png)

**Comment by jpmartinspt** [comment]
Can you log out of your cyberoptics account on snapcraft.io and re-login? (If you haven't tried that already)

**Comment by omichel** [comment]
Unfortunately, I already tried and just tried once again, but no success, same error message.

**Comment by omichel** [comment]
Note: the username is "cyberbotics", not "cyberoptics".

**Comment by jpmartinspt** [comment]
Ooups, sorry about that! Having a look at what's going on now, I'll ping in here ASAP.
