### ISSUE TITLE
UndefinedError

### ISSUE THREAD

**Issue by fida1989** [canonical-web-and-design/snapcraft.io#2304]
### The Problem
![Screenshot at 2019-10-08 22-52-56](https://user-images.githubusercontent.com/2511367/66415905-7dae3c80-ea1e-11e9-91ed-2dd9b6106d17.png)

### Steps to reproduce the problem

Browsing snap store web url: https://snapcraft.io/store

### Specs
- LinuxMint 19.2
- Mozilla Firefox

**Comment by anthonydillon** [comment]
This needs a priority

**Comment by tbille** [comment]
This must have been an issue with the API down. This section has been updated with the new version of the API for store.
It is not relevant anymore.
Reopen in case you face it again.
