### ISSUE TITLE
blog post missing form for whitepaper

### ISSUE THREAD

**Issue by jlosito** [canonical-web-and-design/snapcraft.io#2322]
The blog post below makes reference to a form which users can fill out in order to possibly download the associated whitepaper, but no form is listed.

### Specs

- _URL:_ https://snapcraft.io/blog/management-of-snaps-in-a-controlled-enterprise-environment
- _Operating system:_ Ubuntu 19.10
- _Browser:_ Firefox 70.0

**Comment by Lukewh** [comment]
Thanks for the report @jlosito. The issue seems to be the form being blocked by Firefox's built-in Enhanced Tracking Protection. While we look into how we can resolve this - you can work around by disabling ETP for the page to fill the form in.

**Comment by Lukewh** [comment]
You should be able to fill the form in now, without any work arounds.
