### ISSUE TITLE
images incorrectly scaled on app page

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#2339]
### Expected behaviour

Screenshots uploaded to store should scale correctly on snap store page.

### Steps to reproduce the problem

Visit https://snapcraft.io/bombsquad - note scaled images on right, click them to see the full size. Note the scaling looks vertically stretched.

Looks like this.

![Screenshot from 2019-11-07 10-26-40](https://user-images.githubusercontent.com/1841272/68381291-4f20a000-0149-11ea-920e-c1d555cfb5f0.png)

Should look like this.

![BombSquadBannerAlt](https://user-images.githubusercontent.com/1841272/68381363-76776d00-0149-11ea-8597-d1799105b20c.png)

### Specs

- _URL:_  https://snapcraft.io/bombsquad
- _Operating system:_ Ubuntu 19.10 :heart: 
- _Browser:_  Firefox 70.000

**Comment by Lukewh** [comment]
A fix has been deployed to production (the fix was for another issue, but hadn't been deployed yet).
