### ISSUE TITLE
Search auto-focus and/or hotkey

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [canonical-web-and-design/snapcraft.io#2365]
This is a tiny feature request.

### Expected behaviour

When landing [here](https://snapcraft.io/store), it would be really nice if the UI focus of the browser would be initially set to the search box. This would invite more users to bookmark this page and quickly search for desired software even without using any external tools or browser plugins/addons/scripts.
Alternatively (or additionally) the site might support the hotkey ALT+SHIFT+F to focus on the search box. This is a feature present on Wikimedia sites as well as some other websites. Not ubiquitous by far yet, but still nice to have for those in the know. This feature usually goes along with a tooltip/alt-text to the search box which mentions the hotkey. See Wikipedia search box for reference.

In order to search something user has to:
1. Navigate to https://snapcraft.io/store
2. Visually find search box
3. Place hand on mouse (unless already there)
4. Locate cursor (via moving the mouse)
5. Move cursor to search box
6. Left click on search box
7. Start typing

Steps 2-6 can be avoided by either of these features. First feature would presumably avoid these steps for slightly more users than feature 2 (search hotkey). 

### Steps to reproduce the problem

Navigate to https://snapcraft.io/store
Start typing and learn that focus is nowhere specific.
Press ALT+SHIFT+F and learn that you have to use the mouse to search.

### Specs

- _URL:_ https://snapcraft.io/store
- _Operating system:_ Linux (Kubuntu 18.04 LTS)
- _Browser:_ Firefox 70.0.1 (64-bit)

**Comment by matthewpaulthomas** [comment]
Neither [Google Play](https://play.google.com/store) nor the [Microsoft Store](https://www.microsoft.com/en-us/store/apps/windows?icid=CNavAppsWindowsApps) auto-focus their search fields. But on the Snap Store, the search field is much more prominent (even with the main heading starting “Search”). But maybe that’s a leftover from when there was much less other stuff on the page.

**Comment by i-need-to-tell-you-something** [comment]
Good point. This made me realize that accommodations for my (keyboard->faster; faster->better) workflow might break someone else's workflow. Perhaps there exists some desire to not have the UI focus put there despite the fact that I currently can't imagine a drawback to this change (other than a bit of dev time).

I think for example in the iOS app store app, the lack of prominence (and obviously auto-focus) of search is an intended feature - to force the user to wander in the featured/recommended section despite the user's initial intentions. The user getting what they came for is secondary. I can imagine that Google and Microsoft benefit from the same direction. This increases the value of being featured and can provide users with stuff they didn't know they wanted. On the other hand it probably increases user money spent on the platform and therefore is incentivizing the platform owners to move in that direction.
