### ISSUE TITLE
Snapcraft should not allow programs with "unset" license

### ISSUE THREAD

**Issue by leandroramos** [canonical-web-and-design/snapcraft.io#2380]
I think snapcraft should filter programs that don't show the license. For example, WPS Office (yes, WPS proprietary that tries to hide it). Isn't there a way to demand it from the software developer?

Users deserve to know the software license before installing it, and snapcraft can help the users on it.

https://snapcraft.io/wps-office-multilang

![image](https://user-images.githubusercontent.com/3253741/69819893-921ce300-11de-11ea-80db-52973feec7f8.png)

**Comment by leandroramos** [comment]
To clarify, I think the license should be mandatory in snapcraft.yaml, not optional.

![image](https://user-images.githubusercontent.com/3253741/69902720-92001d00-136f-11ea-9d35-cd5d7b5a041f.png)

**Comment by Lukewh** [comment]
Hi @leandroramos thanks for the suggestion.

The best place to post this would be the [Snapcraft forum](https://forum.snapcraft.io/c/other) as it's related to the fundamental workings of Snaps and is not something we can enforce on the website specifically or alone.

If/ when you post on the forum, please add a comment here with a link so we can keep up to date.

**Comment by leandroramos** [comment]
> Hi @leandroramos thanks for the suggestion.
> 
> The best place to post this would be the [Snapcraft forum](https://forum.snapcraft.io/c/other) as it's related to the fundamental workings of Snaps and is not something we can enforce on the website specifically or alone.
> 
> If/ when you post on the forum, please add a comment here with a link so we can keep up to date.

Hi. I'm here because @popey suggested. I'm gonna answer to him on the forum. Thank you

**Comment by Lukewh** [comment]
I see you've updated [your post](https://forum.snapcraft.io/t/wps-office-shows-unset-license/14390/4) on the forum so I'm going to close this issue. Thanks again.
