### ISSUE TITLE
FSF - Java steps outdated

### ISSUE THREAD

**Issue by ElanMan** [canonical-web-and-design/snapcraft.io#2381]
Clicking on 'Package and publish your app' on snapcraft.io homepage takes you to up to date tutorial

Click on 'Package and publish your app' on snapcraft.io homepage. Pick the language your app is written in as Java, click continue. Choose Linux as Operating system, click 'Package Snap'. The following tutorial, creating a snap of freeplane, leads to errors in the build.
However, the tutorial [here](https://snapcraft.io/docs/java-applications) works fine

### Specs

- _URL:_ https://snapcraft.io/first-snap/java/linux/package
- _Operating system:_ Linux
- _Browser:_ Firefox

**Comment by Lukewh** [comment]
@ElanMan Thanks for the report - I've updated the issue title to reflect where the issue lies, we should get to this in the next couple of weeks.
