### ISSUE TITLE
Issue with image resolution for banners

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2382]
See https://forum.snapcraft.io/t/jpeg-banner-quality-is-visibly-degraded-in-the-store/14393/2

**Comment by Lukewh** [comment]
I looked into this a little - not sure how much of an issue it really is. I've checked on both hidpi and standard dpi screens and the banners look ok to me.

**Comment by oSoMoN** [comment]
I'm attaching the original banner, resized to 1104×368 in gimp and exported as a JPG (from the original size of 1920×640), and the one generated at this size by the CDN. Even to my untrained eye there's a very visible loss in quality, have a look for example at the textures on the wall of the Egyptian building on the rightmost part of the image.

Original banner (resized):
![banner-original-resized-in-gimp](https://user-images.githubusercontent.com/11027549/70249298-7d12f780-177c-11ea-9a33-7c48e82bbcad.jpg)

Banner generated by the CDN:
![banner-store-cdn](https://user-images.githubusercontent.com/11027549/70249319-84d29c00-177c-11ea-94d4-83036640f688.jpg)
