### ISSUE TITLE
Validation mail delivery fails to host lookup issue

### ISSUE THREAD

**Issue by monochromec** [canonical-web-and-design/snapcraft.io#2387]
### Expected behaviour
Account validation email in inbox after singing up
### Steps to reproduce the problem
1) Create new account
2) Wait for validation email to arrive
### Specs
Postfix barfs at incoming validation mail:
"Helo command rejected: Host not found"
Is your mail server DNS configured correctly?
- _URL:_
- _Operating system:_
- _Browser:_

**Comment by jkfran** [comment]
Hello @monochromec 

It could be a temporary problem, could you please try again and let us know if issue persist?

Thank you.

**Comment by jkfran** [comment]
I will close this issue, if you continue to have problems please reopen it.

Thank you.
