### ISSUE TITLE
metrics gone to zero

### ISSUE THREAD

**Issue by johanneswilm** [canonical-web-and-design/snapcraft.io#2389]
### Expected behaviour

The metrics normally show how many users have a snap installed. For the [fiduswriter](https://snapcraft.io/fiduswriter/metrics) the metrics have gone to 0 today which cannot be the actual number. This has previously happened for short periods of time earlier during the day, probably when the site was updating with the stats of the previous day. It is now midday in Europe and it still shows zero, so something seems to have gone wrong.

### Steps to reproduce the problem

1. As someone with access rights, go to https://snapcraft.io/fiduswriter/metrics . 

2. Look at the number of users for yesterday.

**Comment by Lukewh** [comment]
@johanneswilm, we're currently experiencing some issues with our metrics, so they're not currently being processed. Once the issues are resolved all metrics should be processed and the missing days should be updated. I'll leave this open until that happens though.

**Comment by Lukewh** [comment]
Metrics seem to be populated now - can you confirm @johanneswilm?

**Comment by johanneswilm** [comment]
Indeed, it is working again.

**Comment by johanneswilm** [comment]
This happened again today. Metrics are currently at zero.

**Comment by Lukewh** [comment]
Yep - issue with metrics processing, it's currently catching up, should be back in a couple of hours.

**Comment by johanneswilm** [comment]
It worked last night but the issue is back today.

**Comment by Lukewh** [comment]
Looks like things have fully caught up now - hopefully this doesn't become a common issue.
