### ISSUE TITLE
“Show details” on Releases points downward but opens upward

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/snapcraft.io#2403]
From @bartaz in #2395:

> Looking at the 'Show details' with a dropdown-like arrow I really expect the details to open below it.
>
> ![](https://user-images.githubusercontent.com/83575/70899608-44361680-1ff7-11ea-8d3f-b4e63998e6aa.png)
>
> Details opening up above the confirmation and moving it down the page is quite unexpected (even when I expect it because I know it will be there...).

**Comment by matthewpaulthomas** [comment]
Off-hand I can think of three ways of fixing this:

1. (easiest, least effective) Flip the chevron graphic, so that it points upward when closed, downward when open.

2. Make the progressive-release UI appear below the Revert/Save bar, rather than above it.

3. (hardest, most effective) Merge the progressive-releases table into the “Releases available to install” table — that is, put the slider for a pending release inside the cell for that release. Besides simplifying the UI overall, that would result in no “Show details” toggle at all.

**Comment by Lukewh** [comment]
> Off-hand I can think of three ways of fixing this:
> 
>     1. (easiest, least effective) Flip the chevron graphic, so that it points upward when closed, downward when open.

Please can I do this?

>     2. Make the progressive-release UI appear below the Revert/Save bar, rather than above it.

@bartaz has also hinted at this - and I'm not adverse to it. Fine I can do this.

>     3. (hardest, most effective) Merge the progressive-releases table into the “Releases available to install” table — that is, put the slider for a pending release inside the cell for that release. Besides simplifying the UI overall, that would result in no “Show details” toggle at all.
![](https://i1.kym-cdn.com/photos/images/facebook/000/041/343/index.php20110724-22047-58b7hk.png)
