### ISSUE TITLE
Investigate release UI action bottlenecks

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2411]
Specifically for progressive releases [see comment](https://github.com/canonical-web-and-design/snapcraft.io/pull/2395#issuecomment-567918676).

**Comment by matthewpaulthomas** [comment]
Perhaps whenever a slider is dragged, the undragged sliders should update only once per second or so. (And if, by next update, they still haven’t finished the previous update, they should stop trying until you’ve let go of the slider.)
