### ISSUE TITLE
https://snapcraft.io/core returns 502 Bad Gateway

### ISSUE THREAD

**Issue by nobuto-m** [canonical-web-and-design/snapcraft.io#2414]
### Expected behaviour

https://snapcraft.io/core should return 200 OK like other apps.

### Steps to reproduce the problem

```
$ curl -sv -o/dev/null https://snapcraft.io/core
...
< HTTP/2 502 
< server: openresty/1.15.8.2
< date: Fri, 27 Dec 2019 04:34:33 GMT
< content-type: text/html; charset=utf-8
< content-length: 36039
< strict-transport-security: max-age=15724800
< x-hostname: snapcraft-io-748f99fdd-kvbfv
< x-view-name: webapp.store.snap_details_views.store.snap_details
< x-vcs-revision: 1576662053-826c26b
< x-request-id: 7417541b90161dd6c3ed990a1f6e5dc9
< link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect, <https://res.cloudinary.com>; rel=preconnect, <https://dashboard.snapcraft.io>; rel=preconnect
< 
{ [3681 bytes data]
* Connection #0 to host snapcraft.io left intact
```

### Specs

- _URL:_ https://snapcraft.io/core
- _Operating system:_ Ubuntu 19.10
- _Browser:_ N/A

**Comment by nobuto-m** [comment]
This has been observed since 2019-12-26 03:03:00 UTC.

**Comment by nobuto-m** [comment]
It's now up.

**Comment by nobuto-m** [comment]
This is happening again since 2020-01-16 03:02:25 UTC.

**Comment by Lukewh** [comment]
We have some updates that are yet to go live - will leave this open until we can confirm if there's an improvement. Thanks for the report.

**Comment by tbille** [comment]
Closing this issue, we have now a front caching. Hopefully this will help improving the situation when the snapstore API is down.
