### ISSUE TITLE
Username is not changing

### ISSUE THREAD

**Issue by JakobDev** [canonical-web-and-design/snapcraft.io#2418]
I had changed my username in Ubuntu One a few months ago, but it's not changing on snapcraft.io. Only the full name has changed.

**Comment by Lukewh** [comment]
@JakobDev thanks for the report - we're looking into it.

**Comment by Lukewh** [comment]
@JakobDev can you update your Snap store username at https://dashboard.snapcraft.io/dev/account/ and let me know when that's done. We need to do one extra step our end before the change is reflected.
Once that's done you may need to log out and back in again.

**Comment by JakobDev** [comment]
@Lukewh I had changed my username now with the your link. https://snapcraft.io/account/details
 Shows my new username now. I don't know about this site before. On https://snapcraft.io/account/details there is only a "Edit Details" link to https://login.ubuntu.com/ where I had changed my Data. Changing the E-Mail and Full Name there, had also chnanged these Things on snapcraft. Only the Username I changed at  https://login.ubuntu.com/ was not chnging on snapcraft. Maybe you should link clarify that.

**Comment by Lukewh** [comment]
Glad it's working now @JakobDev we'll [look into improving](https://github.com/canonical-web-and-design/snapcraft.io/issues/2426) username updates thanks.

**Comment by JakobDev** [comment]
@Lukewh The Account Details are showing the new Username, but my Apps are still showing the old Username.

**Comment by Lukewh** [comment]
@JakobDev I'll investigate further, sorry about this.

**Comment by Lukewh** [comment]
@JakobDev can you provide the name of one of your snaps please?

**Comment by JakobDev** [comment]
[jdTextEdit](https://snapcraft.io/jdtextedit)

As you can see, it still displays the old name wilma456 and not the new name jakobdev.

**Comment by Roadmaster** [comment]
Hi, I've done a "reindex" of jdTextEdit and I believe it now shows the correct name.

**Comment by JakobDev** [comment]
Can you do the same with my other snaps:
[CClLite](https://snapcraft.io/cclite)
[jdReplace](https://snapcraft.io/jdreplace)
[jdLangTranslator](https://snapcraft.io/jdlangtranslator)

btw:
This should be done automatic in the future.

**Comment by Roadmaster** [comment]
> Can you do the same with my other snaps:
> [CClLite](https://snapcraft.io/cclite)
> [jdReplace](https://snapcraft.io/jdreplace)
> [jdLangTranslator](https://snapcraft.io/jdlangtranslator)

Sure! Done.

> 
> btw:
> This should be done automatic in the future.

Absolutely, we're working on it.

- Daniel

**Comment by JakobDev** [comment]
The name has no changed in all of my snaps. Thanks.
