### ISSUE TITLE
https://snapcraft.io/docs down

### ISSUE THREAD

**Issue by Chade** [canonical-web-and-design/snapcraft.io#2422]
### Expected behaviour
Open documentation

### Steps to reproduce the problem
Open link https://snapcraft.io/docs

### Specs

- _URL:_https://snapcraft.io/docs
- _Operating system:_Ubuntu18.04
- _Browser:_Chrome / Firefox

**Comment by fitojb** [comment]
Works for me…

**Comment by anthonydillon** [comment]
Working for me too. Might have been a brief page. If this issue persists please reopen.
