### ISSUE TITLE
Confusing 'Legacy banner' error displayed when saving changes

### ISSUE THREAD

**Issue by seb128** [canonical-web-and-design/snapcraft.io#2423]
Trying to add a banner to one of my snaps the website accepted the image (after I modified it to be of the correct ratio) but when clicking saved at the top of the page it returned an error

'Legacy banner (banner.png) image must be 1218x240 pixels in size.'

But the image is a 1035x345 png which is compliant with the described restrictions. Luckily popey helped me and pointed out it was because I had named my image 'banner.png' (since it's a banner!) which apparently the website special case. 
The warning display was not explicit enough for me to get the clue of why it was considering the banner a legacy one and why it was making up requirements not matching the described restriction

**Comment by Lukewh** [comment]
@seb128 thanks for the report. It seems the name is prioritised over the aspect ratio, which is to say - if the file name is "banner" the code exits too soon. I'll update the code to prevent this from happening in the future.

**Comment by solazio** [comment]
This is an [issue with the API](https://bugs.launchpad.net/software-center-agent/+bug/1859602). We will update this issue once the [API issue](https://bugs.launchpad.net/software-center-agent/+bug/1859602) is fixed.

**Comment by solazio** [comment]
This is [fixed](https://bugs.launchpad.net/software-center-agent/+bug/1859602) now. Closing
