### ISSUE TITLE
brackets in urls break clickable links

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#2424]
### Expected behaviour

The [mosaic](https://snapcraft.io/mosaic) snap had `https://en.wikipedia.org/wiki/Mosaic_(web_browser)` in the description which the web store turned into a clickable link like `https://en.wikipedia.org/wiki/Mosaic_(web_browser`. So I changed it to `https://en.wikipedia.org/wiki/Mosaic_%28web_browser%29` to work-around for now. It looks bad, and we should probably render the original (correct) url nicely.

**Comment by jkfran** [comment]
@popey This should be fixed now:
https://github.com/canonical-web-and-design/snapcraft.io/pull/2432

**Comment by popey** [comment]
@jkfran Awesome, it is indeed fixed! Thank you!
