### ISSUE TITLE
Update Store username via dashboard

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2426]
Currently if updating your username via snapcraft.io you go immediately to Ubuntu SSO - we should implement an update form in snapcraft.io that hits both dashboard and Ubuntu SSO.

**Comment by JakobDev** [comment]
It would be also nice, if you could link the update form at https://snapcraft.io/account/details
. There is currently only a link to Ubuntu SSO, so many Users will not find that form.

**Comment by tbille** [comment]
Duplicate https://github.com/canonical-web-and-design/snapcraft.io/issues/1845
