### ISSUE TITLE
Definition and requirements

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2427]

**Comment by bartaz** [comment]
@Lukewh @jkfran Ping me when you have questions, I may remember where to look in the code.

**Comment by jkfran** [comment]
@bartaz Thank you Bartek! I will keep it in mind

**Comment by cristinadresch** [comment]
@jkfran just so you know, we have changed this to definition so it won't include any actual work for this iteration. So if you couple pls investigate it only by Friday would be great
