### ISSUE TITLE
Cannot connect to site when all services seem to be online

### ISSUE THREAD

**Issue by CircuitBreaker88** [canonical-web-and-design/snapcraft.io#2430]
### Specs

- _URL:_ https://snapcraft.io/innova/listing
- _Operating system:_ Windows 10
- _Browser:_ Brave Browser

**Comment by Lukewh** [comment]
Hi @CircuitBreaker88 the page seems to be working - perhaps the API was under heavy load at the time you tried accessing the page. If the issue persists please reopen the issue with further details.

**Comment by CircuitBreaker88** [comment]
I found the issue, those pages are not supported on Brave Browser

If I load them on my FireFox Dev edition all goes fine

But the moment I try on my Brave Browser it should bad gateway
If you can please check site compatibility with the Brave Browser that would be great

Thank You for your time
CircuitBreaker

**Comment by Lukewh** [comment]
Hi @CircuitBreaker88 - I've been logged in and using Brave for the past few hours without issue. I have my shield settings to the default and I'm using this version of Brave:
Version 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)

Have you modified any of your Settings/ are you using a different version of Brave?

Cheers,
Luke

**Comment by tbille** [comment]
This is doesn't seems to be an issue anymore. 
Closing the issue.
Please re-open if you still have the issue @CircuitBreaker88
