### ISSUE TITLE
 Built, failed to release

### ISSUE THREAD

**Issue by johanneswilm** [canonical-web-and-design/snapcraft.io#2431]
### Expected behaviour

For the `fiduswriter` app, I click on the "Build manually now" button. Seemingly at random, builds for some architectures are marked as "Built and released" whereas others are marked as "Built, failed to release".  Some marked that way will be released anyway. Others will not be released at all. Also this happens seemingly at random. Doing another manual build will do the same with other architectures. There is nothing in the logs explaining what is going on.

### Steps to reproduce the problem

1. Navigate to https://build.snapcraft.io/user/fiduswriter/fiduswriter-snap
2. Click on "Build manually now" button.
3. Wait for result.

### Specs

- _URL:_ https://build.snapcraft.io/user/fiduswriter/fiduswriter-snap
- _Operating system:_ Ubuntu 
- _Browser:_ Chrome

**Comment by Lukewh** [comment]
@johanneswilm thanks for the report. We're starting migration of build.snapcraft.io into snapcraft.io, hopefully this should resolve some issues, and we'll ensure to check builds complete properly. In the meantime, if you discover any details that seem relevant, please update this issue.

**Comment by johanneswilm** [comment]
It worked last night but the issue is back today.

**Comment by solazio** [comment]
This should be fixed now in the `Builds` tab on snapcraft.io
