### ISSUE TITLE
We couldn't find anything for your search subiquity

### ISSUE THREAD

**Issue by Nachtmerrie** [canonical-web-and-design/snapcraft.io#2435]
### Expected behaviour

https://snapcraft.io/subiquity to be in the search results

### Steps to reproduce the problem

Search for `subiquity` or `canonical` on https://snapcraft.io/store

### Specs

- _URL:_ https://snapcraft.io/search?q=subiquity

**Comment by Lukewh** [comment]
Hi @Nachtmerrie, the publisher has set the Snap as "unlisted" that means it won't show in search results - there can be many reasons for this however if you feel this is an error you can use the "Contact Canonical" link on the Snap page and file a bug.
