### ISSUE TITLE
Strange styling of external links on mobile safari

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/snapcraft.io#2464]
### Expected behaviour
External site icons look "normal"
### Steps to reproduce the problem
Using iOS 13.3 and mobile safari, visit snapcraft.io

![photo_2020-01-23_11-50-16](https://user-images.githubusercontent.com/246192/72973802-8f053400-3dd6-11ea-87a8-993d31aae200.jpg)

### Specs

- _URL:_ snapcraft.io/store
- _Operating system:_ iOS 13.3
- _Browser:_ Mobile Safari

**Comment by bartaz** [comment]
Already reported to Vanilla: https://github.com/canonical-web-and-design/vanilla-framework/issues/2728

**Comment by solazio** [comment]
This will be addressed in Vanilla https://github.com/canonical-web-and-design/vanilla-framework/issues/2728 and closing it here.
