### ISSUE TITLE
Rename API classes

### ISSUE THREAD

**Issue by jkfran** [canonical-web-and-design/snapcraft.io#2467]
What do you think of the naming - `Launchpad` and `launchpad`, vs `LaunchpadAPI` and `launchpad_api`?

I would normally do the latter, but maybe the former does make sense and is more succinct - `launchpad.get_snaps` is not wrong - maybe `API` is technically redundant, since as we're programming, everything is an application programming interface in one sense.

This would imply, then, that we should be consistent with this naming everywhere and call our SnapStoreAPI simply `SnapStore` etc. (and it should probably be `SnapStore` rather than `Snapcraft`) but this is all way out of scope of this PR. So it's really just me talking to myself.

Please disregard this comment =)

_Originally posted by @nottrobin in https://github.com/canonical-web-and-design/snapcraft.io/pull/2454_

**Comment by jkfran** [comment]
We will need to change our Store API module:
https://github.com/canonical-web-and-design/canonicalwebteam.store-api/issues/17

**Comment by nottrobin** [comment]
Thanks Fran, great work
