### ISSUE TITLE
Signposting of Build on the homepage

### ISSUE THREAD

**Issue by danielmutis** [canonical-web-and-design/snapcraft.io#2472]

**Comment by danielmutis** [comment]
### Zeplin

Web: https://zpl.io/aR7dgxg
App:  zpl://screen?sid=5e3037237eecc454cf99956a&pid=5e283884b530e49813514f33

**Comment by clagom** [comment]
@danielmutis we reviewed this, are you going to review it with advocacy or someone else too?

**Comment by danielmutis** [comment]
@clagom yes, I will try to set up something with them and Luke.

**Comment by clagom** [comment]
Ok, assigned also @Lukewh then
