### ISSUE TITLE
Build: switch-over messaging campaign

### ISSUE THREAD

**Issue by danielmutis** [canonical-web-and-design/snapcraft.io#2491]

**Comment by danielmutis** [comment]
### Work in progress blog post
https://drive.google.com/open?id=18SI7sJXrAP2A2De7JfvTA0l1A7wOX3GZeVGc-v2UuP0

### Zeplin
Web: https://zpl.io/2pXlOEN
App: zpl://project?pid=5e283884b530e49813514f33

**Comment by cristinadresch** [comment]
@clagom @Lukewh to review

@danielmutis any comments from advocacy yesterday?

**Comment by danielmutis** [comment]
@cristinadresch Igor will take a look at the blog post and make some comments, I am waiting for his feedback. Claudio and Luke took a look at the work yesterday.

**Comment by cristinadresch** [comment]
@danielmutis great! thanks
