### ISSUE TITLE
dupe in text

### ISSUE THREAD

**Issue by almooj** [canonical-web-and-design/snapcraft.io#2492]
### Expected behaviour
display "a snap" text only once

### Steps to reproduce the problem
description text at the begining of the page

Releasing your app

After creating **a snap a snap**, you should upload it to the Snap Store, from where it can reach a potential audience of millions.
****
### Specs

- _URL:_https://snapcraft.io/docs/releasing-your-app
- _Operating system:_
- _Browser:_

**Comment by solazio** [comment]
@Lukewh updated the text. Thanks :+1:
