### ISSUE TITLE
snapcraft push fails for large snap

### ISSUE THREAD

**Issue by paroj** [canonical-web-and-design/snapcraft.io#2498]
### Expected behaviour
`snapcraft push` succeeds

### Steps to reproduce the problem
1. build a snap from this repo: https://github.com/paroj/stuntrally/blob/master/snapcraft.yaml
2. run `snapcraft push`
3. hangs forever at "Processing..."

also reproducible with build.snapcraft.io: https://build.snapcraft.io/user/paroj/stuntrally/821952

probably related to the snap size which is 991MB

**Comment by Lukewh** [comment]
Thanks for the report - I've created an bug on launchpad for the snapcraft cli project - you can view it's status here: https://bugs.launchpad.net/snapcraft/+bug/1862325

**Comment by paroj** [comment]
I reported it here as the issue only appeared after the recent server issues. Maybe its both though.

**Comment by paroj** [comment]
it is working now again..

**Comment by tbille** [comment]
Closing the issue.
Feel free to reopen @paroj if you face the issue again.
