### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#2503]
### Expected behaviour

Modifying listing for a snap, uploading a screenshot, I sometimes get 413 Request Entity Too Large

### Steps to reproduce the problem

Create a new snap and add a screenshot. 

### Specs

- _URL:_ https://snapcraft.io/spek/listing
- _Operating system:_ Ubuntu 20.04
- _Browser:_ Firefox 73

**Comment by popey** [comment]
Still keep getting this when modifying screenshots of snaps. Currently trying to upload a 1.5MB screenshot to the ephemeral snap. Fails every time.

**Comment by tbille** [comment]
This seems to be a content cache issue. Here is where we are tracking the change of configuration: https://portal.admin.canonical.com/C124626

**Comment by Lukewh** [comment]
This is now fixed and live on production :+1:

**Comment by jkfran** [comment]
This is now fixed with RT#124626
