### ISSUE TITLE
"/docs/writing-local-plugins" page returns AttributeError

### ISSUE THREAD

**Issue by RyoshiKayo** [canonical-web-and-design/snapcraft.io#2517]
### Expected behaviour
Navigate to https://snapcraft.io/docs/writing-local-plugins and see documentation for writing local plugins.

### Steps to reproduce the problem
1) Visit https://snapcraft.io/docs/supported-plugins
2) Click on "Writing local plugins" at the top, which redirects you to https://snapcraft.io/docs/writing-local-plugins

### Specs

- _URL:_ https://snapcraft.io/docs/writing-local-plugins
- _Operating system:_ Win 10 x64
- _Browser:_ Firefox 72.0.2 (64-bit)

**Comment by jkfran** [comment]
Hello @RyoshiKayo ,

Sorry about this, it should be working fine now.

Thank you!
