### ISSUE TITLE
Check the launchpad API for information we get for a build

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2521]
Specifically whether there is any information about the webhook URL.

**Comment by jkfran** [comment]
Hey @Lukewh ,

I have been comparing builds and also looking into the Launchpad documentation, I can't find a property that we can use to identify a build from the previous webhooks.

However, I have seen that the property "description" for Snaps in Launchpad is not being used maybe we can update the description to add something like "Generated with Snapcraft v1.0.0" or whatever, so if it is empty that means the snap what generated with the previous build.s.i.

Maybe we need to check with Launchpad this but WDYT?

**Comment by Lukewh** [comment]
+1 as we talked about earlier something like "Generated with snapcraft.io v1".

To discuss with the launchpad team.

**Comment by jkfran** [comment]
Just to keep track: https://bugs.launchpad.net/snapstore/+bug/1863744
