### ISSUE TITLE
Investigation

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2526]
https://github.com/canonical-web-and-design/build.snapcraft.io/blob/master/src/server/db/models/repository.js

Can we retrieve the information for this schema from launchpad alone?

**Comment by jkfran** [comment]
@Lukewh I will close this issue, also I have created this doc:
https://docs.google.com/document/d/1mKZsEfbufycZEL3kIqOioj-QUOqEMUltGjuYHAguh0Q/
