### ISSUE TITLE
APIs for updating the screenshots

### ISSUE THREAD

**Issue by fabiospampinato** [canonical-web-and-design/snapcraft.io#2558]
### Expected behaviour

There should be some way for programmatically updating a listing's screenshots, without one people are most probably not going to bother updating them manually very frequently.

### Steps to reproduce the problem

🤷‍♂️

### Specs

- _URL:_ 🤷‍♂️
- _Operating system:_ macOS 10.14
- _Browser:_ Chrome 79

**Comment by Lukewh** [comment]
Hi the documentation for the binary-metadata API is here https://dashboard.snapcraft.io/docs/api/snap.html#get--dev-api-snaps-(snap_id)-binary-metadata
Hope that helps :+1:

**Comment by fabiospampinato** [comment]
Oh nice, thanks!

I'd be useful to have a clear example of now to upload screenshots this way though, I'm not sure what "<...> – additional files" means exactly 🤔
