### ISSUE TITLE
Provide links for enabling 2FA

### ISSUE THREAD

**Issue by fabiospampinato** [canonical-web-and-design/snapcraft.io#2559]
### Expected behaviour

When running `snapcraft login`, which is the command the website told me to run, I was being suggested to enable 2FA, but I see no mention of how to do this in my account page or anywhere else on the website that I could find.

### Steps to reproduce the problem

Try to enable 2FA.

### Specs

- _URL:_ 🤷‍♂️
- _Operating system:_ macOS 10.14
- _Browser:_ Chrome 79

**Comment by fabiospampinato** [comment]
Actually a link is provided: https://help.ubuntu.com/community/SSO/FAQs/2FA

However by browsing the page it isn't clear how to enable it. I don't think I've ever enable 2FA in a site with such a long page describing what it is, IMHO if the other websites don't need it neither does Ubuntu, whose users are more technical than average, would this long and confusing page.

**Comment by Roadmaster** [comment]
I've done some rearranging of content, so now https://help.ubuntu.com/community/SSO/FAQs/2FA is short and sweet and contains a link to the former wall of text (which is still valuable info, just as you observed not ideal for people just looking to enable 2FA). The new canonical help URL is https://help.ubuntu.com/community/SSO/2FactorAuthentication. I'll try to nudge linkers (SSO itself, Snapcraft) to link to the new URL instead. But redirects are in place so I think we can close this issue.

**Comment by tbille** [comment]
Thanks @Roadmaster 
Closing the issue.
@fabiospampinato if you have any questions or doubts feel free to reopen :smile:
