### ISSUE TITLE
Search for “apache” returns spurious results

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/snapcraft.io#2561]
1\. [Search the Store for “apache”](https://snapcraft.io/search?q=apache).

What happens:
- The # 1 result is [Nextcloud](https://snapcraft.io/nextcloud), which doesn’t even _mention_ Apache in its listing.
- Results # 2, 3, and 4 mention Apache only in their descriptions.
- Apps that actually mention Apache in their names come in at # 5,  16, 26, and 27.

What should happen:
- All else being equal, items that mention Apache in their name should appear first.

With luck, this might be partly/completely the same cause as #1007, but I can’t tell.

[Discovered while reviewing [ubuntu.com#6753](https://github.com/canonical-web-and-design/ubuntu.com/pull/6753) — the search quality is now affecting a task outside of snapcraft.io.]

**Comment by AnnSoMuller** [comment]
That issue was solved, closing it
