### ISSUE TITLE
Can't release snaps

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#2584]
### Expected behaviour

I'm trying to release from edge to stable/beta, and it's not working.

![Screenshot from 2020-03-02 17-18-41](https://user-images.githubusercontent.com/1841272/75700409-ec2fb780-5ca9-11ea-93fa-a604dee0e338.png)

If I highlight the edge channel, then select to release to stable/beta. Nothing happens.

![Screenshot from 2020-03-02 17-19-28](https://user-images.githubusercontent.com/1841272/75700464-01a4e180-5caa-11ea-8564-75290c752e10.png)
It briefly says "Loading" in the green button, then back to as it was:

![Screenshot from 2020-03-02 17-20-13](https://user-images.githubusercontent.com/1841272/75700540-1f724680-5caa-11ea-9aef-6aaca76e5c4c.png)

### Specs

- _URL:_ https://snapcraft.io/jenkins/releases
- _Operating system:_ Ubuntu 20.04
- _Browser:_ Firefox

**Comment by popey** [comment]
Possibly related, on another snap I am getting "Error:Error while closing channels: latest/stable. Permission "package_release" is required as a macaroon caveat." 

![Screenshot from 2020-03-02 23-51-45](https://user-images.githubusercontent.com/1841272/75728807-d1c50080-5ce0-11ea-8d61-edbf72da74d4.png)

**Comment by popey** [comment]
Logged out of everything, closed browser, started again, sacrificed a chicken in a pentagram and now it works  colon shrug colon.

**Comment by Lukewh** [comment]
There was an issue with caching on production that may be related to this. I'm going to close this, but if it happens again please reopen :)!
