### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'media_upload'

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#2588]
### Expected behaviour

Trying to upload a second screenshot. This one.

![Screenshot from 2020-03-03 21-58-43](https://user-images.githubusercontent.com/1841272/75824255-1b722180-5d9b-11ea-9cd7-6d8d2c70313b.png)

Tried a few times. Fails all the time.

### Steps to reproduce the problem

Try to upload a screenshot.

### Specs

- _URL:_ https://snapcraft.io/sosumi/listing
- _Operating system:_ Ubuntu 20.04
- _Browser:_ Firefox

**Comment by popey** [comment]
There's something busted in that sometimes I refresh and see my name in the top right, sometimes I see "Developer Account" like I'm logged out. If I click that, I'm able to see my snap listing pages, but if I try and fiddle with them I get various errors like above. I suspect I need to completely log out of sso

**Comment by popey** [comment]
Logging out/in doesn't fix it, it's still showing sometimes my name, sometimes "Developer Account" like I'm going through two proxies, one has my cookie, the other doesn't.

**Comment by Lukewh** [comment]
This seems to be an issue with the store and it's being investigated

**Comment by Lukewh** [comment]
Turns out might be an issue on the storefront

**Comment by Lukewh** [comment]
We've had to rollback so we can investigate further. I'll leave this open until we deploy a new version with a fix.
