### ISSUE TITLE
Site Shows MAAS Supported for CentOS 7.6 but it's not

### ISSUE THREAD

**Issue by shawnweeks** [canonical-web-and-design/snapcraft.io#2591]
Not sure where to put this bug. At https://snapcraft.io/install/maas/centos it indicates that CentOS 7.6 is supported but it's not since MAAS 2.7 requires libseccomp >= 2.4 which is only included in CentOS 8.x

### Specs

- _URL:_
- _Operating system:_
- _Browser:_

**Comment by clagom** [comment]
I think would be interesting to work on this as a wider use case, we might get a similar situation for CharmHub too. Let's sync when you work on this @danielmutis @Lukewh

**Comment by clagom** [comment]
(FYI @lilyvidenova) ^

**Comment by Lukewh** [comment]
The generic "Enable snapd" section of the page says "Snap is available for CentOS 7.6+, ... "
"Snap" in this use-case means "snapd". The page is indicating that snapd works on CentOS 7.6+, not necessarily "The Snap", in this case MAAS.

I'm going to prefix what I'm about to say with - I don't really know what `libseccomp` is - however I'm pretty sure this is an issue with the MAAS snap. If MAAS requires `libseccomp` it should really be included within the MAAS snap - the idea of snaps is that they include all of their dependencies.

**Comment by sparkiegeek** [comment]
Please can you include the steps to reproduce? Is this specific to the MAAS snap or more generically for snapd on CentOS (I suspect the latter)

**Comment by shawnweeks** [comment]
The issue is for the MAAS Snap. It won’t deploy on CentOS prior to 8. All you have to do is install snap on CentOS 7.6 and run sudo snap install maas --channel=2.7

It will fail due to the version of that library included in the OS. I’m assuming older versions of Maas probably work but I didn’t try them.

Sent from my iPhone

On Mar 10, 2020, at 5:20 AM, Adam Collard <notifications@github.com> wrote:

﻿

Please can you include the steps to reproduce? Is this specific to the MAAS snap or more generically for snapd on CentOS (I suspect the latter)

**Comment by sparkiegeek** [comment]
> The issue is for the MAAS Snap. It won’t deploy on CentOS prior to 8. All you have to do is install snap on CentOS 7.6 and run sudo snap install maas --channel=2.7 It will fail due to the version of that library included in the OS. I’m assuming older versions of Maas probably work but I didn’t try them.

What happened? What version of snapd is installed? How did you determine that it's specific to MAAS and not another snap? How did you determine that it's `libseccomp`? What happens on CentOS 8?

https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by shawnweeks** [comment]
When you run the maas snap install command I provided it say it requires libseccomp >= 2.4 and  exits. On CentOS 8.x the install proceeds normally. I’ve already deleted the VMs I tested this on because it was so easy to reproduce.

**Comment by tbille** [comment]
Hey,

Checking at the [tests for CentOS](https://github.com/snapcore/snapd/pull/9182/checks?check_run_id=1002533471) it seems it's more related to the maas snap. Could you open an issue on the [maas project](https://bugs.launchpad.net/maas/+filebug) if it's still an issue.

Thanks
