### ISSUE TITLE
[releases] revision tooltip says "devmode", but actually means `grade: devel`, too

### ISSUE THREAD

**Issue by Saviq** [canonical-web-and-design/snapcraft.io#2600]
### Expected behaviour
The tooltip says what actually prevents a given revision from being promoted to candidate/stable.

### Steps to reproduce the problem
Upload a revision with `grade: devel`, hover over it in releases page.

- _URL:_ https://snapcraft.io/multipass/releases
- _Operating system:_ N/A
- _Browser:_ N/A

![obraz](https://user-images.githubusercontent.com/231077/76394756-4994ca00-6376-11ea-92c6-217b00c4f0c6.png)

**Comment by Lukewh** [comment]
Thanks @Saviq we'll look at this at the start of next iteration (next week) :+1:
