### ISSUE TITLE
new builds page has weird look next to my gh id

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#2609]
Adding a new application to the new builds section of the store. Added successfully, but the layout is a bit weird. The bit on the right where my avatar has my nickname next to it seems oddly laid out.

![Screenshot from 2020-03-12 11-22-46](https://user-images.githubusercontent.com/1841272/76516825-0dd03200-6454-11ea-88d0-9653cedecb59.png)

**Comment by Lukewh** [comment]
Is this still an issue? It may have been the cache (as our first user).

**Comment by solazio** [comment]
@popey we assume this was cached css and is not a problem anymore. Please re-open if needed.
