### ISSUE TITLE
internal server error when adding build

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#2610]
Adding a new repo via the new build UI. Clicking "Start building" I got an Internal Server Error. :( 

![Screenshot from 2020-03-12 11-23-43](https://user-images.githubusercontent.com/1841272/76516902-2fc9b480-6454-11ea-9517-cc4f8588fe4f.png)

Tried again and got the same.

**Comment by Lukewh** [comment]
@popey you may need to logout and back in again as the store permissions have changed - not ideal, but if it works let me know :+1:
