### ISSUE TITLE
Bad Gateway for Account Details and  "My published Snaps"

### ISSUE THREAD

**Issue by Recollectr** [canonical-web-and-design/snapcraft.io#2611]
### Specs

- _URL:_
- _Operating system:_
- _Browser:_

**Comment by Lukewh** [comment]
We're looking into the root cause of this, in the meantime if you see this issue please try logging out and back in.

**Comment by Lukewh** [comment]
We believe this to be fixed - if you continue experiencing the issue, please reopen this issue
