### ISSUE TITLE
Persistent Bad Gateway error for "Account details" and  "My published Snaps" pages

### ISSUE THREAD

**Issue by Recollectr** [canonical-web-and-design/snapcraft.io#2612]
## Expected behaviour
Expect that this error will not appear in the place of the proper page contents

![image](https://user-images.githubusercontent.com/40473980/77103669-28c11a00-69f1-11ea-9855-814da92dd69d.png)

## Steps to reproduce the problem
For us, simply visit the backend pages of snapcraft.io listed below. We tried logging out and back in, as well as clearing browser data. This problem has persisted for a week, but is not reflected in the service status tracker.

## Specs
URL: https://snapcraft.io/account/details & https://snapcraft.io/snaps
Operating system: Windows 7
Browser: Chrome & Firefox

**Comment by Recollectr** [comment]
We closed this issue when the issue seemed to be resolved by login, when previously it had not been. Unfortunately the error has returned and persists.

**Comment by Lukewh** [comment]
Hi, thanks for the report. We're looking into this.we had some issues that we pushed a fix out for yesterday, but it seems you're still seeing the error. Can you try clearing cookies for https://snapcraft.io and see if that helps, thanks.

**Comment by Recollectr** [comment]
Thanks for your help. It seems alright for now. We'll re-open if this issue reoccurs.
