### ISSUE TITLE
User testing: list of action points and improvements

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2616]
@danielmutis commented on [Mon Mar 09 2020](https://github.com/canonical-web-and-design/build.snapcraft.io/issues/1252)

List of actionable items to improve the Release UI based on the feedback from the user testing.

**Comment by danielmutis** [comment]
https://docs.google.com/document/d/10sI4ZlYpXG2QBg2KYV0xA5E6BUVFEACEGXzqL1YUySA/edit#

**Comment by cristinadresch** [comment]
@clagom to review it this week

**Comment by clagom** [comment]
Added comments in the docs
https://docs.google.com/document/d/10sI4ZlYpXG2QBg2KYV0xA5E6BUVFEACEGXzqL1YUySA/edit#heading=h.1gx0p3is8ltg

**Comment by cassiocassio** [comment]
Having a peek.

Would be super if, when we've eventually written GitHub issues/epics for what comes out of this research, that we could tag those issues back to "UXReseach02.20" or something similar, and be able to point to the number that got done.

That might be too granular, but it would be great to talk about and evangelise  how the research led to improvements/features.
