### ISSUE TITLE
Info on "upgrading snapcraft" from the page on bases 404's

### ISSUE THREAD

**Issue by rcj4747** [canonical-web-and-design/snapcraft.io#2621]
### Expected behaviour
Link to documentation that exists

### Steps to reproduce the problem
Navigate to https://snapcraft.io/docs/base-snaps and scroll down to the "Choosing a base" section.  Follow the link in the last paragraph "Snaps that don’t use bases can often migrate to one without too much difficulty. See [Upgrading snapcraft](https://snapcraft.io/t/upgrading-snapcraft/11658) for more details on potential differences."

The link "[Upgrading snapcraft](https://snapcraft.io/t/upgrading-snapcraft/11658)" leaded to a 404.

### Specs

- _URL:_ https://snapcraft.io/docs/base-snaps
- _Operating system:_ Ubuntu
- _Browser:_ Chrome

### Suggestion

If no other documentation exists I have been pointed at [Snapcraft 3.0 Release Notes](https://snapcraft.io/docs/release-notes-snapcraft-3-0) to help navigate the upgrade from a core to core18 based snap.

**Comment by Lukewh** [comment]
I've updated the link so that it goes to the relevant forum post instead - thanks for the report :+1:
