### ISSUE TITLE
500 error on get-repos

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/snapcraft.io#2625]
I hit a 500 when viewing /publisher/github/get-repos.

Sentry: https://sentry.is.canonical.com/canonical/snapcraft-io/issues/7397/

## Screenshot
![image](https://user-images.githubusercontent.com/1413534/77114171-fda3ee00-6a23-11ea-9a66-bd1b95daab4f.png)

**Comment by Lukewh** [comment]
How did you get to that URL? What were the steps you took leading up to the error? Any further information would be really useful thanks.

**Comment by anthonydillon** [comment]
I wasn't aware this was not public yet. I saw an issue in sentry so checked out the URL and it errored.

**Comment by jkfran** [comment]
Hey, I created a PR for this, a 401 response is more appropriate than a 500.

But anyway, this URL should only be called when the user is authenticated on GitHub.
