### ISSUE TITLE
Internal Server Error - builds page

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#2631]
Trying to trigger a build I keep getting Internal Server Error.
I clicked build and got internal server error. 
On one refresh I could see it actually building, but refreshing the page caused the internal error.

https://snapcraft.io/jenkins/builds

```
Source map error: Error: request failed with status 404
Resource URL: https://snapcraft.io/static/js/modules/raven.min.js?v=a7021b6
Source Map URL: raven.min.js.map

Request to access cookie or storage on “<URL>” was blocked because it came from a tracker and content blocking is enabled. 
```
(I assume the second was due to my adblocker, but the first shouldn't be. Dunno if either is related).

![Screenshot from 2020-03-24 09-31-30](https://user-images.githubusercontent.com/1841272/77410077-47892d00-6db2-11ea-8c78-370400c0ee67.png)

**Comment by Lukewh** [comment]
Hello @popey, are you still seeing this issue? Looks like this was around the time we had issues across all sites and should now be resolved. Cheers

**Comment by popey** [comment]
I am getting this again.

**Comment by jkfran** [comment]
Hello @popey ,

This seems to be caused because a temporal Launchpad issue.

Does it keep happening to you? If it is persistent please let me know the snap.

**Comment by popey** [comment]
Maybe not seen it for some days, and I'm willing to accept it's a backend lanuchpad issue. Be nice if you exposed that somewhere, even in the js console so i don't bug you guys and go direct to the launchpad devs :D

**Comment by jkfran** [comment]
If this issue is happening often we should consider a nicer error message for the users when Launchpad return a timeout.

We don't usually output backend errors in the console but I agree that it will be nice. I will leave this issue open for a few more days, let us know if this happen again.
