### ISSUE TITLE
Snap store instructions are incorrect for RHEL 8

### ISSUE THREAD

**Issue by bmw** [canonical-web-and-design/snapcraft.io#2646]
Pages such as https://snapcraft.io/install/certbot/rhel say that `snapd` is not available for RHEL 8 unless you build the RPM yourself. This is no longer accurate and you can find the package under https://download.fedoraproject.org/pub/epel/8/Everything/x86_64/.

It would be nice to get these instructions updated so they were accurate in the listings on the snap store.

One potential complication with this is the additional repositories that should be enabled with the EPEL repository is different between EPEL 7 and EPEL 8. See https://fedoraproject.org/wiki/EPEL#Quickstart.

**Comment by popey** [comment]
These instructions should be updated to reflect how they are at https://snapcraft.io/docs/installing-snap-on-red-hat - which I understand are correct?

**Comment by Lukewh** [comment]
@bmw @popey I've updated the steps - could you take a look https://snapcraft-io-canonical-web-and-design-pr-2671.run.demo.haus/install/vlc/rhel, thanks.

**Comment by popey** [comment]
I don't have a RHEL 7 or 8 system handy to test those steps on. @bmw  - do they look sane to you?

**Comment by bmw** [comment]
I don't have easy access to a RHEL system either.

With that said, the only potential problems with the instructions I see based on comparing them to the instructions at https://fedoraproject.org/wiki/EPEL#Quickstart are:

1. Do you intend for the `subscription-manager` command to be run on both RHEL versions and does it work on RHEL 8?
2. Are any other repos listed there required to use the snap package from EPEL or might they be in the future? These repos would be `"rhel-ha-for-rhel-*-server-rpms"` on RHEL 7 and `codeready-builder-for-rhel-8-*-rpms` and `PowerTools` for RHEL 8.
