### ISSUE TITLE
Issues connecting one specific repository to the Snapcraft Build Service

### ISSUE THREAD

**Issue by lotharsm** [canonical-web-and-design/snapcraft.io#2661]
I currently have issues with connecting one specific GitHub repository to the Snapcraft.io build system. All other repositories are working without any issues. This specific issue is persistent across the last 3 days, so a temporary issue is somewhat unlikely. I was able to add other repositories in the meantime.
![rvm-snapcraft](https://user-images.githubusercontent.com/11882577/78875771-b0c59d00-7a4e-11ea-81b2-31c1c720e42e.PNG)

### Expected behaviour
The repository is correctly hooked up to the Snapcraft Build service.

### Steps to reproduce the problem
Add the repository https://github.com/lotharsm/residualvm-snapcraft via the URL https://snapcraft.io/residualvm/builds

### Specs
- _URL:_ https://snapcraft.io/residualvm/builds
- _Operating system:_ Tested on Win10 and Ubuntu 20.04
- _Browser:_ Tested on Firefox and Chrome

**Comment by jkfran** [comment]
Hello @lotharsm ,

Thank you for your report. I am looking at the logs and we are getting an error when we are processing your snapcraft.yaml in the repo. Looks like you defined the same key twice:

https://github.com/lotharsm/residualvm-snapcraft/blob/master/snap/snapcraft.yaml#L34
https://github.com/lotharsm/residualvm-snapcraft/blob/master/snap/snapcraft.yaml#L52

I hope this helps you, let me know.

**Comment by jkfran** [comment]
We're going to improve the message, leaving this open to track the work

**Comment by lotharsm** [comment]
> Thank you for your report. I am looking at the logs and we are getting an error when we are processing your snapcraft.yaml in the repo. Looks like you defined the same key twice:
> 
> https://github.com/lotharsm/residualvm-snapcraft/blob/master/snap/snapcraft.yaml#L34
> https://github.com/lotharsm/residualvm-snapcraft/blob/master/snap/snapcraft.yaml#L52
> 
> I hope this helps you, let me know.

D'oh. Thank you _so_ much for spotting this - it drove me crazy I couldn't find any obvious issues with the snapcraft.yaml file since it always built correctly. I fixed the issue and I'm happy to report that the first run of builds is already up and running.

Thanks!
