### ISSUE TITLE
Link to the documentation on the jack1 interface is broken

### ISSUE THREAD

**Issue by DiogoConstantino** [canonical-web-and-design/snapcraft.io#2670]
### Expected behaviour
The document should exist on the path it's being linked to (https://snapcraft.io/t/the-jack1-interface/13093).

### Steps to reproduce the problem

1. Go to the web page with the list of supported interfaces (https://snapcraft.io/docs/supported-interfaces)
2. Click on the link to jack1 interfaces

### Specs

- _URL:_ https://snapcraft.io/t/the-jack1-interface/13093
- _Operating system:_ Ubuntu
- _Browser:_ Firefox

**Comment by Lukewh** [comment]
@DiogoConstantino Looks like this is fixed now, thanks @degville
