### ISSUE TITLE
No feedback when trying to release an unapproved revision

### ISSUE THREAD

**Issue by Saviq** [canonical-web-and-design/snapcraft.io#2689]
### Expected behaviour
In the "Releases" page, unapproved revisions are clearly marked and it's obvious why you can't release them.

### Steps to reproduce the problem
1. Upload a revision that will fail automatic review to the store.
1. Try to release that revision
1. Silent failure

### Specs

- _URL:_ https://snapcraft.io/multipass/releases
- _Operating system:_ N/A
- _Browser:_ N/A

**Comment by Saviq** [comment]
After a quick debugging session with @Lukewh, I realized it's snaps _queued after_ an unapproved one are the problem.

**Comment by Lukewh** [comment]
@lilyvidenova 
![image](https://user-images.githubusercontent.com/479384/83423314-b1f9c180-a422-11ea-8ee6-f17bb81fc749.png)

**Comment by lilyvidenova** [comment]
For the moment we will keep everything as it is. 
We will include improving the colours with the Release UI improvements work.
