### ISSUE TITLE
Blog redirect domain issue

### ISSUE THREAD

**Issue by edu-ap** [canonical-web-and-design/snapcraft.io#2692]
### Expected behaviour
Take user to ubuntu.com/blog

### Steps to reproduce the problem

In the "Related blog posts" section, the URLs for blog posts currently take users to:
- https://snapcraft.io/blog/maas-2-7-released
when they should be
- https://ubuntu.com/blog/maas-2-7-released

### Specs

- _URL:_ https://snapcraft.io/maas
- _Operating system:_ Ubuntu 20.04
- _Browser:_ Chrome

**Comment by jkfran** [comment]
Hello @edu-ap 

We are working in a fix for this issue and it will be live soon.

Thank you!
