### ISSUE TITLE
"Category" on Listing page contains "None" as only entry

### ISSUE THREAD

**Issue by stuartlangridge** [canonical-web-and-design/snapcraft.io#2693]
### Expected behaviour

Either I get to see a list of categories or, if for some technical reason I can't see that list (perhaps I haven't pushed a snap file, or I have pushed a snap file but it's private or unlisted in the store, or something went wrong with the API that fetches the category list) then the category dropdown should be disabled, with a message stating that I can't set a category at the moment but I can (and should) later. I can't think of any reason why I should ever be presented with a Category select element which has one entry, "None", and nothing else; that's never going to be correct.

### Steps to reproduce the problem

Create a new snap in the snap store.

### Specs

- _URL:_ https://snapcraft.io/groovy-gorillas/listing
- _Operating system:_ Ubuntu 18.04
- _Browser:_ Firefox

**Comment by stuartlangridge** [comment]
![image](https://user-images.githubusercontent.com/4356350/80262668-18eac480-8686-11ea-90c3-66abc0b13383.png)

**Comment by jkfran** [comment]
Hello @stuartlangridge 

Thank you for the report, the current status of the snap shouldn't trigger this issue, this seems to be happening only when the API call that fetch the category list fail, I had open a PR to disable the dropdown.
