### ISSUE TITLE
No feedback of ongoing builds

### ISSUE THREAD

**Issue by stuartlangridge** [canonical-web-and-design/snapcraft.io#2698]
### Steps to reproduce the problem

Go to https://snapcraft.io/SNAPNAME/builds. Hit "Trigger new build." See the "Build triggered" message, and hit refresh.
There is no indication whatsoever that a build is going on, or queued. I do not know whether a build is queued up but hasn't started yet, or if it is currently being built, or if the build isn't going to happen because an error occurred that it didn't show me.

### Expected behaviour

I have some indication that a build is ongoing, or queued, or errored.

### Specs

- _URL:_ https://snapcraft.io/pick-colour-picker/builds
- _Operating system:_ Ubuntu 18.04
- _Browser:_ Firefox

**Comment by jkfran** [comment]
Hello @stuartlangridge ,

We had changed the functionality of the button recently to make it more clear than your request is being processed, you will see a spinner animation in the button without leaving the page. If something goes wrong when you request a build a notification will appear with an error message.

Thank you.

**Comment by stuartlangridge** [comment]
"you will see a spinner animation in the button **without leaving the page**."
The problem is that if I do leave the page and come back, there is no spinner. Click "Trigger new build", then hit refresh. There is then no indication that a build has been triggered, which is what this issue is about; if a build is in the process of being requested, then the button should load _as a spinner_, and it doesn't. So I think that this issue is not closed.

**Comment by jkfran** [comment]
Hello @stuartlangridge ,

This issue is now fixed after https://github.com/canonical-web-and-design/snapcraft.io/pull/2824, now when you do a page refresh right after clicking the button all the pending builds will appear in the table with the status "Building soon".

Let us know if you have any issue.

Thank you.
