### ISSUE TITLE
Releases table doesn't look good on mobile

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/snapcraft.io#2703]
Go to `/<snap_name>/releases` on mobile and see the releases table is not fitting into the screen and looks ugly.

![image.png](https://images.zenhubusercontent.com/5cb4608f97df763a9090bdec/e2ebb882-20ae-482d-9d81-cc98fcede575)

**Comment by steverydz** [comment]
Closing as this is currently undergoing a redesign https://github.com/canonical-web-and-design/marketplace-tribe/issues/2239
