### ISSUE TITLE
list of GitHub repositories missing

### ISSUE THREAD

**Issue by kubiko** [canonical-web-and-design/snapcraft.io#2710]
### Expected behaviour
Seeing list of git repositories while being on page:
https://snapcraft.io/<snap name>/builds page
### Steps to reproduce the problem
go to:
https://snapcraft.io/<snap name>/builds
and try to setup build
### Specs

- _URL:_ https://snapcraft.io/<snap name>
<img width="722" alt="Screenshot 2020-04-29 at 14 49 49" src="https://user-images.githubusercontent.com/1101724/80603772-c5cb9580-8a28-11ea-80b4-f6ef31119107.png">
/builds
- _Operating system:_ macOS, Android, iOS
- _Browser:_ Safari/Chrome

**Comment by Lukewh** [comment]
This was fixed!
