### ISSUE TITLE
Rendering of description differs from preview

### ISSUE THREAD

**Issue by jibel** [canonical-web-and-design/snapcraft.io#2715]
Markdown is correctly interpreted on the preview page but not on the main page.

For example https://snapcraft.io/dl-ubuntu-test-iso/preview shows the back quotes are correctly interpreted as fixed size text;
but on https://snapcraft.io/dl-ubuntu-test-iso the back quotes are not interpreted and are displayed on the screen.

**Comment by Lukewh** [comment]
@jibel good catch thanks, we'll look into it :)

**Comment by tbille** [comment]
It seems we have more inconsistencies: the links are styled in the preview section but not in the listing page:

**Preview**
![image](https://user-images.githubusercontent.com/2707508/142620124-cf6a4e43-db89-41cb-a688-24fd0d58fe85.png)

**Listing**
![image](https://user-images.githubusercontent.com/2707508/142620160-b037c362-287c-4140-909e-adaf0ce6ade9.png)


Styled links (`[text](URL)`) are not allowed but are displayed in the preview page.

See discussions: https://forum.snapcraft.io/t/use-of-markdown-in-snap-metadata-summary-description/2128

**Comment by Lukewh** [comment]
This should now be fixed
