### ISSUE TITLE
 Cannot install SkanLite with SNAPS

### ISSUE THREAD

**Issue by mrsturd** [canonical-web-and-design/snapcraft.io#2718]
### Expected behaviour
Cannot install SkanLite with SNAPS as shown at
https://snapcraft.io/install/skanlite/raspbian

I get the message "error" snap "skanlite" is not available on edge for this architecture (armhf) but exists on other architectures (amd64)."

### Steps to reproduce the problem
1. on raspberry pi type
sudo apt install snapd

2. then reboot
3. then type
sudo snap install skanlite --edge

### Specs

- _URL:_ https://snapcraft.io/install/skanlite/raspbian
- _Operating system:_ Raspbian GNU/Linux 10 (buster) 
- _Browser:_ NONE
- _OS:_ Raspberry Pi 3 B+

**Comment by Lukewh** [comment]
Hi,

This is the issue tracker for the snapcraft.io website. The snap needs to be built for different architectures by the publisher.
You can file a bug against the snap here: https://bugs.kde.org/enter_bug.cgi?product=neon&component=Snaps

Thanks!
