### ISSUE TITLE
snapcraft.io site displays Raspberry Pi install option for purely amd64 snap

### ISSUE THREAD

**Issue by a2udev** [canonical-web-and-design/snapcraft.io#2720]
### Expected behaviour
If a snap in the snapcraft.io store only has an amd64 build, Raspberry Pi will not show up in the list of Linux Distributions with install options.

### Steps to reproduce the problem
- Create a snap with only an amd64 build.
- Deploy it on the snapcraft.io store.
- View its Linux Distribution install options on its snapcraft.io store page.

### Example
- https://snapcraft.io/accountable2you
- https://forum.snapcraft.io/t/how-do-i-customize-distribution-list-in-snap-store/16832/8

**Comment by RCMainak** [comment]
Can I work on this?

**Comment by timmccabe** [comment]
Roughly when can we expect to see this fully deployed?

I see that the bug is marked as closed, but Raspberry Pi still shows up when the only build is amd64.
https://snapcraft.io/accountable2you

Thanks!

**Comment by a2udev** [comment]
Roughly when can we expect to see this fully deployed?

I see that the bug is marked as closed, but Raspberry Pi still shows up when the only build is amd64.
https://snapcraft.io/accountable2you

Thanks!

**Comment by RCMainak** [comment]
@a2udev this bug has been fixed & deployed to demo server. You can check it there.

**Comment by Lukewh** [comment]
@a2udev we're having some deployment issues, but once they're sorted it'll be live :)

**Comment by timmccabe** [comment]
It appears to be completely resolved now! Thank you guys!

**Comment by a2udev** [comment]
It appears to be completely resolved now! Thank you guys!
