### ISSUE TITLE
snapcraft error, from process_error

### ISSUE THREAD

**Issue by shenko** [canonical-web-and-design/snapcraft.io#2726]
### Expected behaviour
by enteringn the snapcraft command I get the following error. I think this is because I did a upgrade, but im not sure, it was working fine yesterday. 

### Steps to reproduce the problem
$ snapcraft
Traceback (most recent call last):
  File "/usr/local/bin/snapcraft", line 5, in <module>
    from snapcraft.cli.__main__ import run
  File "/usr/local/lib/python2.7/dist-packages/snapcraft/__init__.py", line 340, in <module>
    from snapcraft._baseplugin import BasePlugin  # noqa
  File "/usr/local/lib/python2.7/dist-packages/snapcraft/_baseplugin.py", line 196
    ) from process_error
         ^
SyntaxError: invalid syntax

### Specs

snap --version
snap    2.44.3
snapd   2.44.3
series  16
ubuntu  18.04
kernel  5.3.0-51-generic

- _URL:_
- _Operating system:_
- _Browser:_

**Comment by shenko** [comment]
snap info snapcraft
name:      snapcraft
summary:   easily create snaps
publisher: Canonical✓
store-url: https://snapcraft.io/snapcraft
contact:   https://forum.snapcraft.io/c/snapcraft
license:   GPL-3.0
description: |
  Package, distribute, and update any app for Linux and IoT.
  
  Snaps are containerised software packages that are simple to create and install. They auto-update
  and are safe to run. And because they bundle their dependencies, they work on all major Linux
  systems without modification.
commands:
  - snapcraft
snap-id:      vMTKRaLjnOJQetI78HjntT37VuoyssFE
tracking:     latest/stable
refresh-date: 9 days ago, at 02:47 EDT
channels:
  latest/stable:    3.11                2020-04-08 (4282) 63MB classic
  latest/candidate: 4.0                 2020-04-27 (4657) 66MB classic
  latest/beta:      ↑                                          
  latest/edge:      4.0+git11.gc1e849e4 2020-05-06 (4691) 67MB classic
installed:          3.11                           (4282) 63MB classic

**Comment by shenko** [comment]
I have updated to 'edge' or version 4.0 using;
    snap refresh --edge snapcraft
unfortunately it yields the same error.

**Comment by shenko** [comment]
same result for 'beta' version 4.0. I don't know know what else I can do, at this point.

**Comment by Lukewh** [comment]
Hi this is the issue tracker for the snapcraft.io website.
You can report bugs for the snapcraft CLI tool [here](https://bugs.launchpad.net/snapcraft/+filebug)

Thanks.

**Comment by shenko** [comment]
I have updated my system to ubuntu 20.04, but thank you I have left a report anyways with them
