### ISSUE TITLE
Inkscape (snap) uses wrong home directory

### ISSUE THREAD

**Issue by andrist** [canonical-web-and-design/snapcraft.io#2734]
Not sure where to report issues with individual snaps; please close/redirect as appropriate.

### Actual behaviour
Selecting [Home] in the "File > Open ..." dialog opens ~/snap/inkscape/7627/

### Expected behaviour
Selecting [Home] in the "File > Open ..." dialog opens the "~/" folder (i.e., user home).

### Steps to reproduce the problem
1) Vanilla Ubuntu 20.04 installation
2) Install Inkscape (snap) through "Ubuntu Software"
3) Launch Inkscape
4) File > Open ...
5) Select [Home] in the sidebar

### Specs

- _Inkscape Version:_ 1.0-6e3e5246a0-2020-05-07 (latest stable, updated 07.05.2020)
- _Operating system:_ Ubuntu 20.04

Note: All paths in preferences are relative to this wrong home directory, i.e., 
~/snap/inkscape/7627/../../../.config/inkscape/preferences.xml

**Comment by Lukewh** [comment]
Hi @andrist,

Thanks for taking the time to report an issue. This is the issue tracker for the snapcraft.io website. Inkscape have their own bug reporting and tracking process which can be found on their [Report Bugs](https://inkscape.org/contribute/report-bugs/) page. Hope this helps :)!

**Comment by andrist** [comment]
It doesn't, but thanks for taking the time to triage.

NOTE: The bug is specific to installing with snap, it doesn't happen with inkscape that is installed through regular apt-get install.

**Comment by fitojb** [comment]
Cf. https://github.com/canonical-web-and-design/snapcraft.io#bugs-in-snaps-and-tools
