### ISSUE TITLE
Improve snap listing page layout

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/snapcraft.io#274]
On market page we allow users to add/change icon of the snap.

Icon element has couple of overlays:
- white transparent 'circle border' - that is meant to suggest that icon is going to be used both as a square or cicrcle
- black transparent 'half circle' - with edit icon

The way this two overlays are used and are visible all the time on top of the icon make it really unreadable and confusing.
As a user uploading an icon I don't recognise my icon when added to market page. 

Icon on dashboard:
<img width="667" alt="screen shot 2018-01-30 at 17 30 05" src="https://user-images.githubusercontent.com/83575/35578225-bad32fc4-05e3-11e8-8c12-df25fcd4ee36.png">

Icon on market page:
<img width="879" alt="screen shot 2018-01-30 at 17 29 57" src="https://user-images.githubusercontent.com/83575/35578226-baed2d52-05e3-11e8-8b45-df260a56a1cf.png">

### Expected

Icon preview on market page should be better, so that user would be able to see the icon they are choosing not covered in confusing overlays.

**Comment by shivjoshi1996** [comment]
@lyubomir-popov We are considering making the icon overlay display on hover-only, would you be okay with this?

**Comment by lyubomir-popov** [comment]
@bartaz @shivjoshi1996 I would suggest putting it as a text link so it is still discoverable without interaction - as in the screenshot below:

![image](https://user-images.githubusercontent.com/2741678/35980535-d19c444c-0ce2-11e8-8369-b46b2cc1b5af.png)

**Comment by therealjuan** [comment]
This has been fixed previously with the updated changes to listing pages.
