### ISSUE TITLE
Instruction to move away from build.snapcraft.io are incorrect

### ISSUE THREAD

**Issue by galgalesh** [canonical-web-and-design/snapcraft.io#2751]
Following the instructions in the ["We are changing the way you build snaps from GitHub repos"](https://snapcraft.io/blog/we-are-changing-the-way-you-build-snaps-from-github-repos) blogpost results in a broken webhook. You get a `403 “invalid secret”` response.

This has been reported at least two times in the store category of the forum.

* https://forum.snapcraft.io/t/403-invalid-secret-after-updating-automatic-build-webhook-on-github/17212/3?u=galgalesh
* https://forum.snapcraft.io/t/403-invalid-secret-after-updating-automatic-build-webhook-on-github/17212

**Comment by jkfran** [comment]
Hello, this issue was fixed with https://github.com/canonical-web-and-design/snapcraft.io/pull/2963

The webhooks will work, thank you!
