### ISSUE TITLE
build-snapcraft-io seems to require an extreme amount of permissions to my Github account

### ISSUE THREAD

**Issue by stuartlangridge** [canonical-web-and-design/snapcraft.io#2752]
### Expected behaviour

build-snapcraft-io needs enough access to my Github account to fetch the source of a project to build it as a snap, and that's it. If it needs to create a webhook, then OK, ask for write permissions for webhooks on a specific project. Do not ask for write access to literally everything I have on github, 'cos you ain't gettin' it. You're a build tool, not my boss.

### Steps to reproduce the problem

1. Go to https://snapcraft.io/[snapname]/builds
2. click Log in to your github account, as suggested
3. See that build-snapcraft-io requires the following list of permissions:

![image](https://user-images.githubusercontent.com/4356350/82160677-e69c4380-988e-11ea-890e-f07d098ff717.png)

4. say "nuh-uh, snapcraft! no way am I giving you the ability to write and delete everything on every project I own! Why do you want to add new deploy keys to my projects? Delete all my issues on private projects you don't even know exist! why would you even ask for this?!"
5. file this bug

### Specs

- _URL:_ https://snapcraft.io/tabular/builds
- _Operating system:_ Ubuntu 18.04
- _Browser:_ Firefox

**Comment by Lukewh** [comment]
@stuartlangridge thanks for the report.

@jkfran can we check what the minimum set of permissions we need are please?
