### ISSUE TITLE
Shouldn't have distro pages for snaps unavailable on that distro's arch

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2753]
See https://forum.snapcraft.io/t/skype-on-rasbian-buster/17558/3

**Comment by RCMainak** [comment]
I think this issue should be fixed by #2727 :thinking:

**Comment by Lukewh** [comment]
> I think this issue should be fixed by #2727 thinking

That just fixes the link in the pages - not direct links to the pages from things like search engines.
