### ISSUE TITLE
/store: Installing a snap with no stable provides wrong install command

### ISSUE THREAD

**Issue by fcole90** [canonical-web-and-design/snapcraft.io#2764]
If you open https://snapcraft.io/node can click on install and it suggests a normal install, but it fails. This is because node has no "stable" channel, but only 10/stable and so on.

### Expected behaviour
Clicking on install to provide a working command to install the snap.

### Steps to reproduce the problem
- Go to https://snapcraft.io/node
- Click install, which prompts run `sudo snap install node --classic`
- Paste it in your terminal
- Let it fail:
```
$ sudo snap install node
error: snap "node" is not available on stable but is available to install on
       the following channels:

       edge       snap install --edge node

       Please be mindful pre-release channels may include features not
       completely tested or implemented. Get more information with 'snap info
       node'.
```

(I think this message is bad but that's an issue for the snap team: https://bugs.launchpad.net/ubuntu/+source/snap/+bug/1879374)

### Specs

- _URL:_  https://snapcraft.io/node
- _Operating system:_ Ubuntu 20.04
- _Browser:_ Chrome stable

**Comment by tbille** [comment]
This has been fixed since https://github.com/canonical-web-and-design/snapcraft.io/issues/2952
Thanks for opening the issue.
