### ISSUE TITLE
snapcraft-yaml-reference lacks hooks: block

### ISSUE THREAD

**Issue by knitzsche** [canonical-web-and-design/snapcraft.io#2773]
### Expected behaviour
I would expect the snapcraft.yaml reference page [1] to include mention of the top-level hooks: block
[1] https://snapcraft.io/docs/snapcraft-yaml-reference
### Steps to reproduce the problem
Open the above page and search for "hooks"
### Specs

- _URL:_
- _Operating system:_
- _Browser:_

**Comment by jkfran** [comment]
Seems to be solved now. Can you confirm @degville ?

**Comment by degville** [comment]
Yes, this is solved - thanks!
