### ISSUE TITLE
Store pagination links are tiny and hard to spot

### ISSUE THREAD

**Issue by fitojb** [canonical-web-and-design/snapcraft.io#2777]
### Expected behaviour

Up to now, whenever I visited the Games category of the Store, I always found the same few results. It took me a while to realize I could load more of them by changing the page.

### Steps to reproduce the problem
0. Have failing eyesight or tired eyes.
1. Go to https://snapcraft.io/search?category=games
2. Scroll to the bottom.

![image](https://user-images.githubusercontent.com/554953/82551837-9212f580-9b26-11ea-964b-64cad516b69f.png)

For the benefit of discoverability by dumbasses like meself, please enclose these links in a box (like in `/first-snap` — cf. #1969), or add icons to them.

**Comment by RCMainak** [comment]
I would like to working on issue.

**Comment by fitojb** [comment]
Thanks @RCMainak !
