### ISSUE TITLE
Register snap, move buttons to left

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2786]

**Comment by anasereijo** [comment]
The action buttons on the 'Register a snap' page are displayed on the right-hand side of the page. This is consistent with the positioning of action buttons in other pages such as 'Snap listing' page. 

See screenshots below

**Register snap page**
<img width="1160" alt="Screenshot 2021-11-19 at 15 17 57" src="https://user-images.githubusercontent.com/36884067/142646530-e6187a8a-07b1-4621-add0-5b9e9a03509a.png">

**Snap listing page**
<img width="1177" alt="Screenshot 2021-11-19 at 15 19 10" src="https://user-images.githubusercontent.com/36884067/142646769-2604b714-691d-44dd-88c1-6cbfd6504f8d.png">

That said, I will close this issue. Please re-open if I am looking at the wrong thing :)
