### ISSUE TITLE
Listing - Both buttons should be disabled when there are no changes

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2795]
Don't show save and revert at all until there's something to do

**Comment by anasereijo** [comment]
This has been implemented. see below

![Screenshot 2021-11-18 at 15.20.13.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/1fb41ffd-2e6d-4ebc-a2f2-53cf48fad96e)
