### ISSUE TITLE
Listing - category spacing is strange

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2796]
We should change this to be a single component.

**Comment by anasereijo** [comment]
Visual to work on how to group better the Category sub-items as now looks disjoint.

![Screenshot 2021-11-18 at 15.15.44.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/42658de9-5246-40b2-9039-77f382f01ad6)

![Screenshot 2021-11-18 at 15.15.51.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/dced842c-6727-498e-9271-5d31f547629d)
