### ISSUE TITLE
Listing - Multiple errors that don't help you find out where the error is

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2800]
What can we do here? Create anchor links and consolidate into 1 error

**Comment by anasereijo** [comment]
closing as this doesn't seem to be an issue anymore. See screenshot below:

![Image Pasted at 2021-11-18 15-08.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/90b6b8b6-cb01-4d9c-9b66-7454836ae08d)
