### ISSUE TITLE
Build tab not showing correct status for all architectures

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#2819]
### Expected behaviour

After clicking "Trigger new build", and waiting for some time, I would expect to see the status for all architectures.

### Steps to reproduce the problem
Trigger a build while there's a bit of a queue on launchpad
Note that any build which is 'Needs building' state in launchpad, is just invisible on the build tab
I triggered matterbridge snap, twice. Once which built okay for i386 and amd64. It however never built (yet) for the other architectures. But I have no status showing that.
![Screenshot from 2020-05-25 16-14-37](https://user-images.githubusercontent.com/1841272/82825431-25d81f00-9ea3-11ea-867d-8914667669bd.png)
If I dig, over on launchpad I see:
![Screenshot from 2020-05-25 16-14-44](https://user-images.githubusercontent.com/1841272/82825503-456f4780-9ea3-11ea-8076-84b66a2dd054.png)
I also note the builders are busy:
![Screenshot from 2020-05-25 16-15-56](https://user-images.githubusercontent.com/1841272/82825517-4acc9200-9ea3-11ea-856a-b64632fbfa4f.png)

So under this state, I'd expect to be told they're waiting on a builder, or some other "Pending" state.

### Specs

- _URL:_ https://snapcraft.io/matterbridge/builds
- _Operating system:_ Ubuntu
- _Browser:_ Firefox

**Comment by jkfran** [comment]
Hello @popey ,

This issue is related to https://github.com/canonical-web-and-design/snapcraft.io/issues/2749, we are currently working on it.

Thank you.

**Comment by jkfran** [comment]
Hi @popey ,

I am to close this issue since it should be working fine now after https://github.com/canonical-web-and-design/snapcraft.io/pull/2824. Let us know.

Thank you!
