### ISSUE TITLE
Icon delete button is not accessible

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/snapcraft.io#2826]
The button to delete an icon is not a link or button and so can not be targetted via tab.
![image](https://user-images.githubusercontent.com/1413534/83002497-09ec8e80-a005-11ea-9475-b1a7a3cac7aa.png)

**Comment by anthonydillon** [comment]
Also could maybe be the word "Delete"?

**Comment by solazio** [comment]
@lilyvidenova should I keep the icon and make it a button or link to be accessible or you prefer to use the "Delete" word instead?
