### ISSUE TITLE
Recurring update notification with no actual updates

### ISSUE THREAD

**Issue by pronoym99** [canonical-web-and-design/snapcraft.io#2835]
### Current problem
Recollectr always comes with the notification that a new version namely 3.13.54 is available and will be installed on exit. I always open Recollectr after that and close it after some time after checking the version. Always hoping that it would be auto-updated after I exit the app. But it never does. And the notification repeats itself after every system boot. 

### Expected behaviour
The app should automatically update itself as soon as a new version is available.

### Specs

- _Operating system:_ windows 10 Pro 64 bit
- _Current version of Recollectr:_ 3.13.49

**Comment by solazio** [comment]
@pronoym99 this is the issue tracker for [snapcraft.io](https://snapcraft.io/) website. Try to report your problem by emailing support@recollectr.io or visiting https://recollectr.io/contact/

You can confirm that the snap is up to data by using this command  in a terminal `snap refresh recollectr`
