### ISSUE TITLE
staging build server should talk to staging services

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/snapcraft.io#2845]
## Summary

The staging service of build.snapcraft.io should talk to the corresponding staging service of the dashboard and API services to help identify regressions.

## Process

Use build.staging.snapcraft.io

## Current and expected result

Interactions are with dashboard.snapcraft.io, not dashboard.staging.snapcraft.io

**Comment by Lukewh** [comment]
https://github.com/canonical-web-and-design/canonicalwebteam.launchpad/issues/30 should help with this.

**Comment by tbille** [comment]
Done.
