### ISSUE TITLE
No way to reauthorize store uploads of a snap

### ISSUE THREAD

**Issue by cjwatson** [canonical-web-and-design/snapcraft.io#2847]
If you change your SSO password, then the store won't let you upload a snap until you've reauthorized it (because the macaroon held by Launchpad will now be invalid).  Launchpad has a way to do this (by going to $snap_url/+authorize), but as far as I can see the only way to do this in BSI is to remove and re-register the snap, which is pretty heavyweight: for example, this loses your build history.

It would be very helpful if BSI had a way for the owner of a snap to reauthorize uploads of it.  Note that this is separate from the task of notifying people when they need to do this.

**Comment by jkfran** [comment]
I tried to reproduce this issue in snapcraft.io, it doesn't happen. These were my steps:
1. Register a snap in snapcraft.io
2. Link the snap with a repo in the "Builds" tab.
3. Wait until the snap is build
4. Go to login.ubuntu.com and change my password
5. Trigger the GitHub webhook of the snap repo
6. The snap was built on Launchpad as usual.

I will close this issue.
