### ISSUE TITLE
Cannot remove repo where snap name was revoked

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/snapcraft.io#2848]
https://forum.snapcraft.io/t/revoked-snap-is-still-getting-built/8482 seems to indicate that it's not possible to remove a repo when the snap name has been revoked (not transferred). mmtrt, can you confirm that you selected the repo on the main screen and explicitly tried to remove it?

If it is indeed not possible, this is a similar issue to the now-fixed canonical-web-and-design/build.snapcraft.io#998 (resolved in canonical-web-and-design/build.snapcraft.io#1107).

**Comment by jkfran** [comment]
I think this is not possible anymore since we moved build.snapcraft.io to snapcraft.io
