### ISSUE TITLE
Add messaging for people without JavaScript turned on

### ISSUE THREAD

**Issue by therealjuan** [canonical-web-and-design/snapcraft.io#2850]
@nottrobin commented on [Fri Nov 30 2018](https://github.com/canonical-websites/snapcraft.io/issues/1380)

Currently, if I visit https://build.snapcraft.io/user/nottrobin with JavaScript disabled, I see this:

![image](https://user-images.githubusercontent.com/519935/49284380-585eb280-f48c-11e8-9a49-7e72f52a1cfb.png)

I actually have 11 repos set up in build.snacraft.io. I can click "Add repos", in which case I see this:

![image](https://user-images.githubusercontent.com/519935/49284402-6a405580-f48c-11e8-921c-7436e0a16727.png)

Both are very misleading. We should add a message to explain to people that they can't use the app with JavaScript turned off.

**Comment by lilyvidenova** [comment]
How about something nice and friendly like: 

"It seems like you've got JavaScript turned off, so everything seems blank. Please enable JavaScript to use all the available features."

![no JS on builds](https://user-images.githubusercontent.com/17980375/97568404-e4faae00-19de-11eb-939d-41df0a103bd7.png)
![no JS on metrics](https://user-images.githubusercontent.com/17980375/97568461-e926cb80-19de-11eb-8d6b-216b643f63c4.png)
![no JS on releases](https://user-images.githubusercontent.com/17980375/97568506-eb892580-19de-11eb-8465-9bd86fbb83bf.png)
