### ISSUE TITLE
Promotion gone crazy

### ISSUE THREAD

**Issue by JackDandy** [canonical-web-and-design/snapcraft.io#2852]
## Summary

The promotion keeps going back to older releases that are no longer required. Seems there is some smart logic that is tripping over itself.

## Process

See attached screen video.

## Current and expected result

It would be nice to see some logic in what revisions are available for selection. Instead, in between page refreshes, or not, the UI bounces from the latest to older revisions, I've tried for a long time to try and "catch" it up, to no avail.

## Screenshot

<img src="https://i.vgy.me/4HpYqY.gif">

This gif video is around 2 mins. The full blank white screen is when the F5 button in the browser is pressed to refresh the page. 

It would be preferable to simply not have to do any of this dance at all, like what is feature requested in my other thread... [autopromote, i.e. setting which level auto-builds should be released to](https://github.com/canonical-web-and-design/build.snapcraft.io/issues/1186)

**Comment by Lukewh** [comment]
@JackDandy is this still an issue? We've made changes to the Release UI and I think it may have sorted this.

**Comment by JackDandy** [comment]
@Lukewh

I think you are correct, I will close this issue.

Thank you for following up.
