### ISSUE TITLE
Improve error message when a linked repo is removed from GH

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/snapcraft.io#2854]
If you have a snap connected to a GH repo and you remove the repo, you will see an error saying "This repository doesn't contain a snapcraft.yaml", but perhaps we should be more explicit and say the repo does not exist.

![image.png](https://images.zenhubusercontent.com/5cb4608f97df763a9090bdec/a171f663-955a-4b48-addd-75a708cb3f7a)

**Comment by lilyvidenova** [comment]
Do we know when a repo doesn't exist vs when the yaml is just missing? 

If we do, could we have two messages: 

`This repository doesn't contain snapcraft.yaml. More on how to create it. (linking to https://snapcraft.io/docs/creating-snapcraft-yaml)`

and

`Your snap is linked to REPO-NAME, but this repository doesn't exist. Disconnect repo.`

**Comment by clagom** [comment]
If doable, UX wise would work well
