### ISSUE TITLE
How to delete your account?

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/snapcraft.io#2857]
As discussed in the workshop, build.snapcraft.io doesn't store any state for the user. Therefore, you can effectively "delete your account" by simply:

- deleting all your added repositories
- revoking the app's permissions in GitHub settings 

However, we may, for users' peace of mind, want to either:

- Explain the above steps to "deleting your account" in an FAQ or other documentation page
or
- Provide a "delete your account" link somewhere which simply deletes your repos for you - although I don't know if its possible to revoke GitHub permissions from our end.

**Comment by jkfran** [comment]
This issue was for build.snapcraft.io.
