### ISSUE TITLE
Respect publishing rights for shared snaps

### ISSUE THREAD

**Issue by timsueberkrueb** [canonical-web-and-design/snapcraft.io#2862]
`build.snapcraft.io` doesn't seem to respect publishing rights for snaps when they are shared from another Ubuntu One account (via `dashboard.snapcraft.io`) with the currently logged in account.

Specific user story:
> For our organization, we are using the sharing feature from [dashboard.snapcraft.io](https://dashboard.snapcraft.io) to share access for our packages to the individual maintainers (and their own, individual Ubuntu One accounts). So, I'm able to add an organization repository without any problems. Although, when it comes to the step "register a snap name for publishing", I have to sign in to Ubuntu One, which I do with my individual account the snap package is shared with via dashboard.snapcraft.io. However, unfortunately, the site doesn't seem to respect the fact that the package is shared with my account and denies access with the message: "Sorry, that name is already taken".

See [this forum topic](https://forum.snapcraft.io/t/registering-organization-snaps-for-publishing/645) for more information.

**Comment by Lukewh** [comment]
I don't think this is an issue any more since moving build.snapcraft.io/ to snapcraft.io/<snap>/builds. Please try there and if it's still an issue reopen this issue.
