### ISSUE TITLE
Build snaps for pull requests

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/snapcraft.io#2863]
Today we support building snaps for every commit that gets pushed to the default branch on GitHub. This allows for a workflow where you:

1. Open a pull request
1. Have your code automatically tested by Travis or CircleCI
1. Have your code reviewed by humans who will clone your branch and build locally
1. Land your pull request on master
1. Have your code automatically built and published by build.snapcraft.io

We could help earlier in that workflow by giving the reviewing developers prebuilt binaries to test with. These would be close to the binaries created off master after the branch lands.

This would allow for a workflow where you:

1. Open a pull request
1. Have your code automatically tested by Travis or CircleCI
1. Have your code automatically built by build.snapcraft.io and published to a channel branch (e.g. latest/edge/sergiusens:default-options)
1. Have your code reviewed by humans who will install from the channel branch
1. Land your pull request on master
1. Have your code automatically built and published by build.snapcraft.io

**Comment by Lukewh** [comment]
Perhaps we should add some documentation around doing this with GitHub actions?

**Comment by degville** [comment]
Adding some official documentation on using GH actions is a good idea, and something I've been meaning to do. There's already some forum discussion and forum-based scripts, but I've created a docs roadmap item to create some proper documentation for this.
