### ISSUE TITLE
Handle someone choosing to create snapcraft.yaml before name is registered

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/snapcraft.io#2877]
We recommend that someone register the snap name before adding a snapcraft.yaml — because for publishing, snapcraft.yaml needs to include the registered name.

But you might want to add a snapcraft.yaml before registering the snap name, for example if you want to see whether your software works as a snap at all.

Therefore, we should customize the contents of the template snapcraft.yaml in this case, to tell you that it won’t publish until you register the name, and tell you how to proceed.

**Comment by Lukewh** [comment]
I think this case is covered by the snapcraft.io/<snap>/builds integration.
