### ISSUE TITLE
Many i386 builds in "previous builds"

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/snapcraft.io#2878]
![screen shot 2017-10-25 at 11 54 13](https://user-images.githubusercontent.com/1523179/31995200-5f1aad4c-b97b-11e7-8deb-f973282bfdc9.png)
https://build.snapcraft.io/user/paritytech/parity

This seems odd to me. Is there a reasonable explanation for why we're seeing one amd64, one armhf, and five i386 builds in the "previous builds" section?

**Comment by Lukewh** [comment]
This doesn't seem to be an issue on the snapcraft.io/<snap>/builds page. Please reopen if you come across it again. Thanks.
