### ISSUE TITLE
Repo list keeps cached linter status

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#2879]
## Summary

See issue canonical-web-and-design/build.snapcraft.io#668 for full background.
 
## Process

Connect a repo with a broken yaml (duplicate stanza such as can be seen in the 'before' of [this commit](https://github.com/snapcrafters/pulsemixer/commit/dbb6e2236f098f0e6d58e08f1c83661c4bd1a198) ). Fix the yaml and refresh the build page.

## Current and expected result

It still shows that I have a broken yaml (see screenshot). I'd expect it to re-check and say "okay, this yaml is good now". It seems happy that the yaml is indeed good because it started building the snap. However the status still shows that it's bad.

## Screenshot

![image](https://user-images.githubusercontent.com/1841272/31127069-aa0c26a6-a845-11e7-8775-9490e165e7b9.png)

**Comment by Lukewh** [comment]
No longer relevant with the move to snapcraft.io. Thanks though.
