### ISSUE TITLE
Consider populating snapcraft.yaml with contextual config

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#2880]
Given b.d.i is talking to github and can see a project source and meta data, it seems to make sense to use that data to pre-populate the yaml rather than give a generic boilerplate example.

The metadata such as project name, most recent version, short name and description could potentially be gleaned easily and injected directly into the initial yaml.

Via some simple heuristics we could determine whether a project uses the python, nodejs, autotools, go or cmake/qmake project and populate a part with some appropriate data including the source url. With the use of some comments we could indicate to the developer that this is not guaranteed to work as-is, but is a template built based on the available code.

**Comment by Lukewh** [comment]
I don't think this is still relevant with the move to snapcraft.io. We also have the first snap flow that covers this use-case. Please reopen if you think it's still relevant - and provide specific details.
