### ISSUE TITLE
Adding Appliance Links

### ISSUE THREAD

**Issue by rhys-the-davies** [canonical-web-and-design/snapcraft.io#2882]
### It would just be a link to the relevant page that Peter and Ant are working on at the moment something like:

'Download the openHAB Ubuntu Appliance' - Install a ready-made openHAB image on a Raspberry Pi, an Intel NUC or a try it in a VM and get started. 

The copy for the various appliances are here: https://drive.google.com/drive/u/0/folders/1s872nhzjZxz5-WYGnnEUxysyRFgoA1p2

- _URL:_
- _Operating system:_
- _Browser:_

**Comment by clagom** [comment]
@lilyvidenova @danielmutis Maybe we can have a look at CharmHub layout (e.g. Ubuntu - also on Kubernetes)?

**Comment by danielmutis** [comment]
@lilyvidenova On Charmhub there are these links to other supported platforms. 
<img width="1230" alt="Screenshot 2020-06-12 at 09 43 17" src="https://user-images.githubusercontent.com/59825615/84483630-8502a580-ac91-11ea-974b-a40eddd4e273.png">

**Comment by rhys-the-davies** [comment]
'Also available as an Ubuntu Appliance' would work

**Comment by lilyvidenova** [comment]
I think the quickest solution will be following the Charmhub example:
![image](https://user-images.githubusercontent.com/17980375/84770897-5574d580-afd0-11ea-9957-07a0c3db28d8.png)

@rhys-the-davies @clagom

**Comment by lilyvidenova** [comment]
And on hover of the link:

![image](https://user-images.githubusercontent.com/17980375/84771091-b56b7c00-afd0-11ea-9520-4f699edce4d7.png)

just to provide a bit more context before the user commits to following the link.

**Comment by lilyvidenova** [comment]
And also add the link to the appliances page on the install modal:

![image](https://user-images.githubusercontent.com/17980375/84771475-6a059d80-afd1-11ea-90cc-b6bdaf9a3331.png)

**Comment by lilyvidenova** [comment]
@Lukewh wanna take a look at this one? I think it'll be nice to have it up close to the /appliances launch (that should be today I think)

**Comment by clagom** [comment]
I would add “Also” to the “available” to make it clearer, as per @rhys-the-davies copy

**Comment by lilyvidenova** [comment]
I felt the Also is a bit superfluous, added:

![image](https://user-images.githubusercontent.com/17980375/84778231-996cd800-afda-11ea-87e9-61af4e8dcbab.png)
![image](https://user-images.githubusercontent.com/17980375/84778277-ae496b80-afda-11ea-8e07-adcba981128e.png)

![image](https://user-images.githubusercontent.com/17980375/84778271-ab4e7b00-afda-11ea-870f-bb1099b7a1de.png)

**Comment by Lukewh** [comment]
Looks good to me - is this ready to go?

**Comment by clagom** [comment]
I think so, adding UX +1

**Comment by lilyvidenova** [comment]
Yep 🚀

**Comment by rhys-the-davies** [comment]
Sorry for being late to see this, but we need to add 'an'. 'Also available as _an_ Ubuntu Appliance'. While that's being changed I agree with Lils note of 'Also' being 'superfluous' so can we use: 'Available as an Ubuntu Appliance'
