### ISSUE TITLE
Snapcraft builds: Remove the "successfully linked" messsage

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2890]
The header show's it was successful

**Comment by jkfran** [comment]
I am not sure if this was fixed or it means to remove the current one, this is how it looks like right now:

---

**This is the previous step; selecting the repo:**
![Screenshot from 2020-08-18 14-32-09](https://user-images.githubusercontent.com/6353928/90519865-830d0500-e160-11ea-9acd-11f1cca2596a.png)

---

**And this is where the success message appears:**
![Screenshot from 2020-08-18 14-30-47](https://user-images.githubusercontent.com/6353928/90519923-95873e80-e160-11ea-8b0e-148f356cae80.png)

**Comment by Lukewh** [comment]
The idea was to remove the :heavy_check_mark: message all together - it's extra information. You can see it's linked by the "Your snap is linked to: " text and the entire page changes :+1:
