### ISSUE TITLE
Have different messages for different risks

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2898]
See https://github.com/canonical-web-and-design/snapcraft.io/pull/2896#issuecomment-644859715

**Comment by Lukewh** [comment]
@lilyvidenova any more thought on candidate:
"Snaps on the /beta channel may have unfinished parts, breaking changes may occur.

I'd like to come up with something useful for candidate too but I'll need a bit more time for it, so no message will be better than a pretty wrong message."

**Comment by lilyvidenova** [comment]
I think something like this gives a bit more context about what the level means: 

"Snaps at /candidate risk level need some additional real world experimentation before they move forward to stable."
