### ISSUE TITLE
${warning}

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#2900]
Did I catch something mid-deploy?

`${warning}`

![Screenshot from 2020-06-17 16-21-44](https://user-images.githubusercontent.com/1841272/84917034-b70f6f80-b0b6-11ea-9790-a99660518c88.png)

**Comment by Lukewh** [comment]
Very odd - do you still see it? Probably cached static files if it's no longer there.

**Comment by popey** [comment]
No, seems okay now. Magic.

**Comment by Lukewh** [comment]
Going to close - but reopen if you see it again... I'll also keep checking a few snaps today

**Comment by nottrobin** [comment]
@Lukewh, @lilyvidenova was this reopened because it's actually still an issue? Do you have any details on how it popped back up?

**Comment by lilyvidenova** [comment]
@nottrobin - yes, this is still an issue and it seems to randomly disappear for some people, it has been consistently the case for me. 

![image](https://user-images.githubusercontent.com/17980375/85397338-4c918000-b54b-11ea-9549-89560f7ef6e8.png)

**Comment by lilyvidenova** [comment]
@nottrobin this is (potentially) related to https://github.com/canonical-web-and-design/snapcraft.io/issues/2904

**Comment by nottrobin** [comment]
Do we know why this would have ever shown? Because if it was a cache, there must have been a reason why it would have appeared this way at some point in the past.

**Comment by lilyvidenova** [comment]
@nottrobin it is trying to display the work done in https://github.com/canonical-web-and-design/snapcraft.io/pull/2896#issuecomment-644859715 and https://github.com/canonical-web-and-design/snapcraft.io/issues/2898

**Comment by nottrobin** [comment]
Oh so this could be a JS error? I assume that `${}` syntax is a JavaScript one? So maybe if you can see it all the time @lilyvidenova, could you look in your console log for JS errors?

**Comment by Lukewh** [comment]
It's an issue with the cache. An old version of the JS file is being served that doesn't strip the `${warning}` out of the template.

**Comment by nottrobin** [comment]
ah I see. OK thanks.

**Comment by Lukewh** [comment]
https://github.com/canonical-web-and-design/snapcraft.io/pull/2912 provides a work around until we figure out what the issue *really* is
