### ISSUE TITLE
Custom GA events are not being sent

### ISSUE THREAD

**Issue by caldav** [canonical-web-and-design/snapcraft.io#2904]
When loading any page, Raven JS tries to issue a call to an nonexistent Google Analytics property and fails with `Loading failed for the <script> with source “https://www.google-analytics.com/gtm/js?id=GTM-MJJ7C2K&t=gtm3&cid=506658963.1528712213”`

All subsequent GA events issued by the site, such as install events, are not being sent. It seems that, when failing to call its own property, Raven is hijacking the ga() function and preventing other calls to be issued.

**Comment by lilyvidenova** [comment]
Marking this as high priority, as I'd really like to have some data from the A/B test for the upcoming sprint

**Comment by solazio** [comment]
@caldav we believe this is related to a content cache issue we have and basically the served js and css are old. Can you please check again if it's still happening as I cannot replicate it at the moment.

**Comment by caldav** [comment]
@solazio  Are you saying you don't see: `Loading failed for the <script> with source “https://www.google-analytics.com/gtm/js?id=GTM-MJJ7C2K&t=gtm3&cid=506658963.1528712213”.` in the console when loading a snapcraft.io page? If you don't see it, then the issue is on my end and the GA issue is a different one.

**Comment by solazio** [comment]
@caldav I had the AdBlocker on and that's why I was not seeing it. Leave it with us a bit longer as we have the IS involved as well. Thanks

**Comment by solazio** [comment]
@caldav this has nothing to do with raven. A first request is made to https://www.googletagmanager.com/gtm.js?id=GTM-KCGXHQS which is successful - that's the [id we have in the code](https://github.com/canonical-web-and-design/snapcraft.io/blob/master/templates/_layout.html#L19). After that the script makes a call to https://www.google-analytics.com/gtm/js?id=GTM-MJJ7C2K which is [nowhere in our code](https://github.com/canonical-web-and-design/snapcraft.io/search?q=MJJ7C2K&unscoped_q=MJJ7C2K) and seems to be injected by the script. This second call is the one 404ing. 
By the way it looks is a problem inside the GTM... maybe something is not linked corectly.
If you want we an do a call today so we figure it out together.
Thanks

**Comment by caldav** [comment]
Thanks for investigating further, this prompted me to look harder at GTM and found a link to a dead Optimize property. Bug is fixed.
