### ISSUE TITLE
Trying to build for i386 when base is core20

### ISSUE THREAD

**Issue by sergiusens** [canonical-web-and-design/snapcraft.io#2905]
### Expected behaviour

No build is attempted for the build-all scenario

### Steps to reproduce the problem
Create a snap with `base: core20` and hook up to build.
![imagen](https://user-images.githubusercontent.com/1146853/85181418-443ff900-b25c-11ea-8abc-f499c8709dfd.png)
Would produce (like on https://snapcraft.io/black/builds/1008259):
![imagen](https://user-images.githubusercontent.com/1146853/85181475-66d21200-b25c-11ea-8893-17bda7d3be1e.png)

**Comment by jkfran** [comment]
@sergiusens from what I understand the i386 architecture should be ignored when the base is core20, right?

If this is true, I think Launchpad shouldn't try to build the snap for this architecture, especially when the snapcraft.yaml doesn't contain any specific architecture.

I found the following issue on Launchpad about this:
https://bugs.launchpad.net/launchpad/+bug/1862258

**Comment by tbille** [comment]
This is a bigger issue than just a fix.

We will organise a design discussion with @sergiusens to figure out how we can handle this type of behaviour.

**Questions:**
- What should happen when a architecture is not handle any more by launchpad?
- What should happen when a new architecture is added in launchpad?
- Should those architecture appear/disappear from the build interface? (this is confusing)

@jkfran I am removing this from our iteration for now.

**Comment by cjwatson** [comment]
This should be fixed from the Launchpad point of view: i386 builds will no longer be dispatched for core20.
