### ISSUE TITLE
snap repository clear business conditions for software consumers

### ISSUE THREAD

**Issue by CrisLobin** [canonical-web-and-design/snapcraft.io#2925]
Hi.

I was just testing the snap repository for Debian Linux.

searching for a renamer app. Found one, called "smart-file-renamer". Installed it. The first file to rename, was free. For the rest, I requiered a payment for the full version.

My suggestion is that, mandatory for apps to show in advance, if they are free or not, and the amount to pay for the full version.

Thanks

CrisLobin

**Comment by tbille** [comment]
Hi thanks for opening an issue. This is the repo for the website. But this sounds like a great topic for discussion over on the snapcraft forum: https://forum.snapcraft.io/
