### ISSUE TITLE
flutter logo on the first-snap page is upside down

### ISSUE THREAD

**Issue by kenvandine** [canonical-web-and-design/snapcraft.io#2937]
The flutter logo on the first-snap page is actually upside down

See https://flutter.dev/ for an example of what it should look like.

**Comment by kenvandine** [comment]
It was reported on the forum, https://forum.snapcraft.io/t/flutter-logo-upside-down-on-main-website/18730

**Comment by VelocityDesign** [comment]
Yes. I noticed this too.
