### ISSUE TITLE
Error: SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/snapcraft.io#2945]
https://sentry.is.canonical.com/canonical/snapcraft-io/issues/180/?referrer=github_plugin

```
Error: SyntaxError: Unexpected token < in JSON at position 0
  at None (./static/js/public/snap-details/blog-posts.js:81:15)
```

**Comment by solazio** [comment]
This error `Failed to fetch` seems to happen when JS is fails to fetch `/api/snap-posts/<snap>` endpoint. There doesn't seem to be any error in the backend that would lead to the error in JS and therefore I'm closing this issue.
