### ISSUE TITLE
New GitHub webhook not working

### ISSUE THREAD

**Issue by benfrancis** [canonical-web-and-design/snapcraft.io#2949]
### Steps to reproduce
* Switch GitHub webhook from old build.snapcraft.io URL to the new snapcraft.io URL as described in https://snapcraft.io/blog/we-are-changing-the-way-you-build-snaps-from-github-repos

### Expected behaviour
* Build is triggered by next GitHub commit

### Actual behaviour
* Build not triggered, webhook log in GitHub says the request got a 403 response "Invalid secret"

Is there some other change that needs making to an existing build.snapcraft.io webhook, in addition to just changing the URL? E.g. changing the secret?

**Comment by jkfran** [comment]
Hello @benfrancis ,

Thank you for reporting this issue, it seems it was a bug indeed, now it should be possible for you to use the webhook.

**Comment by benfrancis** [comment]
Great, thanks! 🎉
