### ISSUE TITLE
Mmhu@evandandrea I would suggest there's room for a 3b. before step 4: automated testing of the snap package published to the channel branch (complementary to human testing).  Unless that's automatically assumed to be covered by the corresponding webhooks issue?

### ISSUE THREAD

**Issue by chrisnrick** [canonical-web-and-design/snapcraft.io#2961]
@evandandrea I would suggest there's room for a 3b. before step 4: automated testing of the snap package published to the channel branch (complementary to human testing).  Unless that's automatically assumed to be covered by the corresponding webhooks issue?

_Originally posted by @WebDrake in https://github.com/canonical-web-and-design/snapcraft.io/issues/2863#issuecomment-306234662_

**Comment by tbille** [comment]
Thanks for opening this issue.
We will up-date documentation about this.
You can still follow the progress on #2863
