### ISSUE TITLE
Visual design second A/B test

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/snapcraft.io#2970]
![second test carosel A.png](https://images.zenhubusercontent.com/5af976724b5806bc2bd30860/121c9daa-b5ea-4a98-8647-43590d4a476e)![second test carosel B.png](https://images.zenhubusercontent.com/5af976724b5806bc2bd30860/18deae7b-054d-4fbf-8e19-3c8f112f9c6e)

The two mock ups depict the first two states of the carousel, the rest will be the same, always containing 3 snaps. 

I am not sure whether it'll look better to have the search bar on a background or to show the green search button on the white background - I have no preference.

**Comment by anthonydillon** [comment]
@lilyvidenova just an idea and probably future feature but what about moving the search to above the featured apps and have autocomplete search directly on the homepage. Simular to how the snaps are searched on [the image builder](https://ubuntu.com/core/build).

**Comment by lilyvidenova** [comment]
Thanks, @anthonydillon. I think we can keep this for  slightly further ahead - I'd like to first test moving the whole store to be the home page and then we can iterate and improve the search. Do you think that's a good plan?

**Comment by anthonydillon** [comment]
Sounds good, just saw this and thought there was an opportunity there.

**Comment by spencerbygraves** [comment]
@lilyvidenova here's some options for you.

**01**

![image](https://user-images.githubusercontent.com/9105999/88931948-5e1a2600-d275-11ea-97d1-35c8a6f8205a.png)

**Same but with full width card**

![image](https://user-images.githubusercontent.com/9105999/88932022-70945f80-d275-11ea-956e-a9d8780a912d.png)

**Search box on white**

![image](https://user-images.githubusercontent.com/9105999/88932104-8f92f180-d275-11ea-9946-ace09c40666b.png)

**Search at the top?**

![image](https://user-images.githubusercontent.com/9105999/88932214-b0f3dd80-d275-11ea-9736-f4b313739bb5.png)

**Comment by lilyvidenova** [comment]
Thanks @spencerbygraves! I really like the last one with the search on top! @clagom can you take a look too, please?

**Comment by clagom** [comment]
I think the one with the search on top works very well. I like @anthonydillon proposal btw as a follow up of this design. Let's see what advocacy team think

**Comment by tbille** [comment]
@clagom @spencerbygraves 

I think the third choice seems the preferred one. Having the search bar on top also is the best.
From @popey here is the list of categories that will be displayed: **Featured - Development - Games - Server.**

We just need to figure out a small description for those categories.

Other comment:
![image](https://user-images.githubusercontent.com/2707508/89204026-5f1cc180-d5ad-11ea-8b1f-9caaaf83b923.png)
Should be replaced with: `Available snaps`

**Comment by clagom** [comment]
Sounds good @tbille

**Comment by spencerbygraves** [comment]
@tbille here you go.

![image](https://user-images.githubusercontent.com/9105999/89271753-101a6f00-d635-11ea-8ad0-71456a431749.png)
