### ISSUE TITLE
Search result count incorrect

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/snapcraft.io#2971]
Visit https://snapcraft.io/search?q=zsh

It says that there are 4 snaps found but only 3 are shown.

<img width="1175" alt="Screen Shot 2020-07-22 at 12 43 08 PM" src="https://user-images.githubusercontent.com/532033/88215536-0a765f80-cc19-11ea-9fed-6e9d2817749f.png">

**Comment by tbille** [comment]
@hatched thanks for spotting this. This is an API issue. I raised a bug here: https://bugs.launchpad.net/snapstore-server/+bug/1888664

I'll leave it open until fixed on store side.

**Comment by AnnSoMuller** [comment]
as it has its own issue in launchpad, I close it here
