### ISSUE TITLE
Open Drive (Google Drive Snap Package) unable to connect with google account.

### ISSUE THREAD

**Issue by rp-web** [canonical-web-and-design/snapcraft.io#2987]
I'm not sure if here is the proper place report a problem, I'm trying the keepassxc password manager but I need to sync it with my smartphone that requires the database file to be in the cloud (in this case google drive), I am a new Linux user (Manjaro) and unfortunately, there is no package in the Arch repository for Google Drive GUI (at least I haven't found any), I found this snap package called Open Drive (or ODrive) that seems to be simple and practical, but when I try to log in the following error message appears "You're unable to log in" it's about the security of the browser,(I don't know how I'll log in in a different browser since the option to do it it's in the application window, would anyone know how can I log in without getting this error?

I followed the instructions on this site(https://snapcraft.io/install/odrive-unofficial/arch) the installation was smooth just facing this login trouble. Thanks in advance and sorry for the long text.

**Comment by tbille** [comment]
@rp-web hi thanks for reporting this issue. This should be handled by the maintainer of the snap. 
If you go on the page: https://snapcraft.io/odrive-unofficial you should find the contact details and the site of the maintainer of this snap.

Thanks good luck for your issue :smile:
