### ISSUE TITLE
[Desktop] Display submitted, updated dates, changelog, expandable product images and more for every apps

### ISSUE THREAD

**Issue by KizunaH** [canonical-web-and-design/snapcraft.io#3004]
Snap Store.

- Display application submitted date to store
(This's optional but good to include.)

- Display application last updated date **(Important)**
(Currently this display only for several applications; idk why.)

- Display several old version numbers and released dates (additional: changelog)
(It helpful for users to know more about certain application and recent updates. See apple store apps changelog area)

- Suggest(force) developers to upload beta, dev, nightly version to store additional to stable. **(Important)**
(a UI enhancement for display often when they add an application for first time, push new updates or make any change related it or modify current procedure and UI contents then place notable areas for add these versions separately. there're some developers already doing that. eg: opera). Linux isn't windows or macos.

- Expandable product images
(Currently we cannot expand product images to see clearly and some are even unable to recognize well due small letters, icons under default size. Check google play store or windows store for that).

- Set minimum quality for upload product images.
(Some applications overview has very low quality images.)

- Changelog
(It'll be better if application maintainer able to publish as google play store etc or provide alternatively option add changelog site link)

**Comment by tbille** [comment]
Hey thanks for opening this very detailed issue.
There are a lot of things here. I would suggest to start those discussions on the [forum](https://forum.snapcraft.io/) itself that will be more active than the repository for the website.
I will close this issue for now.
