### ISSUE TITLE
[docs] Snapcraft -> Debug Snaps menu item points to docs/security-sandboxing 

### ISSUE THREAD

**Issue by alexmurray** [canonical-web-and-design/snapcraft.io#3006]
### Expected behaviour

When following the heading / left hand menu item for Debug Snaps under Snapcraft it should take me to the /docs/debug-snaps page but instead it links to docs/security-sandboxing

Also there doesn't appear to be any item linking to security-sandboxing

### Steps to reproduce the problem
Visit https://snapcraft.io/docs and select from the left hand menu 'Debug Snaps' under the 'Snapcraft' group

### Specs

- _URL:_ https://snapcraft.io/docs
- _Operating system:_ Ubuntu 20.04.1 LTS
- _Browser:_ Firefox

**Comment by degville** [comment]
thanks for flagging this, and you're right about the link confusion. I've corrected the debug link and added the Sandboxing security policy doc to the docs outline.
