### ISSUE TITLE
Support by-arch view in the Weekly active devices graph in the Metrics page

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [canonical-web-and-design/snapcraft.io#3015]
### Expected behaviour
There's an option to see how many users are using X architecture of the snap.

### Steps to reproduce the problem
1. Browse the snap's metrics page
1. Click the scroll-down bar of [By version] in the Weekly active devices section

### Specs

- _URL:_ https://snapcraft.io/_snap_name_/metrics
- _Operating system:_ Ubuntu 20.04 amd64
- _Browser:_ Mozilla Firefox 79.0

**Comment by tbille** [comment]
hey this is great and we should definitely jump back on it.
I will close this issue since it's a duplicate from #1680

We should bring this issue back to life since the API is giving us those metrics now.
