### ISSUE TITLE
Failed snap builds do not provide logs

### ISSUE THREAD

**Issue by kz6fittycent** [canonical-web-and-design/snapcraft.io#3017]
### Expected behaviour
If a build fails, a log is typically provided to trouble-shoot issues.

### Steps to reproduce the problem
Attempt manual build, build fails, no logs. 

### Specs

- _URL:_https://snapcraft.io/bashtop/builds
- _Operating system:_Solus 4.1
- _Browser:_Brave

![Screenshot from 2020-08-18 19-34-36](https://user-images.githubusercontent.com/14829816/90679125-58d14b00-e225-11ea-8fa0-d68cc8940032.png)

**Comment by cjwatson** [comment]
It's not generally true that failed builds don't provide logs.  However, certain kinds of internal outages in Launchpad can result in this sort of symptom.  We're working on the general case, but it's OK to just dispatch builds again when this happens.

**Comment by jkfran** [comment]
Hi @kz6fittycent , I am going to close this issue because it has happened due to an outage, manually triggering a new build should fix your issue.

Thank you!
