### ISSUE TITLE
Can't release edge to stable

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#3019]
### Expected behaviour

I have a snap where I'd like to promote edge to stable. Unfortunately it only selects some of the architectures. A picture paints a thousand words:

Before - current state:

![Screenshot from 2020-08-20 12-22-48](https://user-images.githubusercontent.com/1841272/90764204-e3768080-e2df-11ea-9786-f5f0e1682b94.png)

After, I selected edge, release to stable:

![Screenshot from 2020-08-20 12-21-10](https://user-images.githubusercontent.com/1841272/90764246-f12c0600-e2df-11ea-9f3a-c191d50df27b.png)

Note amd64 and arm64 don't get updated.

- _URL:_ https://snapcraft.io/dosbox-staging/releases
- _Operating system:_ Ubuntu 20.04
- _Browser:_ Chrome

**Comment by popey** [comment]
This has got a bit worse.
I have tried to release on the command line with the following:-

However, it's all gone wrong now, with 38 appearing in multiple architectures!

```
alan@robot:~$ snapcraft release dosbox-staging 46 stable,beta
Track    Arch    Channel    Version    Revision
latest   amd64   stable     v0.75.1    46
                 candidate  ↑          ↑
                 beta       v0.75.1    46
                 edge       v0.75.1    46
The 'stable' and 'beta' channels are now open.
alan@robot:~$ snapcraft release dosbox-staging 48 stable,beta
Track    Arch    Channel    Version    Revision
latest   arm64   stable     v0.75.1    48
                 candidate  ↑          ↑
                 beta       v0.75.1    48
                 edge       v0.75.1    48
The 'stable' and 'beta' channels are now open.
alan@robot:~$ snapcraft release dosbox-staging 47 stable,beta
Track    Arch    Channel    Version    Revision
latest   i386    stable     v0.75.1    47
                 candidate  ↑          ↑
                 beta       v0.75.1    47
                 edge       v0.75.1    47
The 'stable' and 'beta' channels are now open.
alan@robot:~$ snapcraft release dosbox-staging 38 stable,beta
Track    Arch    Channel    Version    Revision
latest   amd64   stable     v0.75.0    38
                 candidate  ↑          ↑
                 beta       v0.75.0    38
                 edge       v0.75.1    46
         arm64   stable     v0.75.0    38
                 candidate  ↑          ↑
                 beta       v0.75.0    38
                 edge       v0.75.1    48
         armhf   stable     v0.75.0    38
                 candidate  ↑          ↑
                 beta       v0.75.0    38
                 edge       v0.75.0    38
         i386    stable     v0.75.0    38
                 candidate  ↑          ↑
                 beta       v0.75.0    38
                 edge       v0.75.1    47
The 'stable' and 'beta' channels are now open.
```

![Screenshot from 2020-08-24 12-25-29](https://user-images.githubusercontent.com/1841272/91039796-1fbe1f80-e605-11ea-9cae-d48d2af3e3bb.png)

**Comment by popey** [comment]
Ok, weirdly build 38 thinks it's a multi-arch build, no idea why.

So I closed all channels and manually re-released 46/47/48 to stable for now.

**Comment by AnnSoMuller** [comment]
We are closing it.
if is does happen again, please reopen an issue.
Thanks!
