### ISSUE TITLE
Handle added/dropped architecture on launchpad on release/build UI

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/snapcraft.io#3024]
When an architecture is dropped or added on launchpad we should have a way to show this in the UI

For example Core20 doesn't support i386 but it is still appearing in the build UI as a failing job.

**Comment by nanu-c** [comment]
On `core18` the `gnome-3-34` is also not supported on `s390x`, `ppc64el` and `i386`...

```
Failed to install or refresh a snap: 'gnome-3-34-1804-sdk' does not exist or is not available on the desired channel 'latest/stable'. Use
```
