### ISSUE TITLE
Internal server error on build page.

### ISSUE THREAD

**Issue by keshavbhatt** [canonical-web-and-design/snapcraft.io#3026]
### Expected behaviour
Build page with option should come

### Steps to reproduce the problem
try to open build page of a snap

### Specs

- _URL:_ https://snapcraft.io/kdictionary/build
- _Operating system:_ Android phone
- _Browser:_ Chrome

**Comment by tbille** [comment]
Hey thanks for notifying the issue. This was due to a misconfiguration on our side. Reopen in case you are still facing this issue.

**Comment by keshavbhatt** [comment]
Thanks it is fixed now :)
