### ISSUE TITLE
Review the design of the https://snapcraft.io/about/listing page as the muted text seems to bee too small

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/snapcraft.io#3027]
![image.png](https://images.zenhubusercontent.com/5cb4608f97df763a9090bdec/7b493097-ab0a-42a4-9bbc-4f8692c66d9c)

**Comment by fitojb** [comment]
Yup, at first sight I thought “Title” was a placeholder label or something left out accidentally. Its design doesn’t scream, “I’m a heading!,” and the actual big heading text is too blatant and obtrusive for what it says. (and it’s the same size as an H1, which is confusing).

**Comment by long-chung** [comment]
Can you follow the style that has been set out on the automotive page
https://ubuntu.com/automotive
