### ISSUE TITLE
Language/framework logo titles look displaced from the images

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/snapcraft.io#3030]
On the homepage the text under the logos in the language/framework section look displaced from the logos. This is especially noticeable on smaller viewports.

My suggestion would be to centre the text.

See screenshots:

![Screenshot_20200827-191520](https://user-images.githubusercontent.com/501889/91536996-81380400-e90d-11ea-98f1-861f3228451a.png)

![Screenshot from 2020-08-28 09-03-47](https://user-images.githubusercontent.com/501889/91537004-839a5e00-e90d-11ea-9f08-d7867f7c8a72.png)

**Comment by RCMainak** [comment]
I would like to work on this issue.
