### ISSUE TITLE
New builds not being triggered

### ISSUE THREAD

**Issue by kz6fittycent** [canonical-web-and-design/snapcraft.io#3045]
### Expected behaviour
When new commit occurs in GH, build should trigger on snapcraft.io

### Steps to reproduce the problem
 - Used two different repos, added new code to each, no build triggered for either. 
 - Behavior spanning ~24 hours 
 
### Specs

- _URL:_https://snapcraft.io/bpytop/builds & https://snapcraft.io/openvas/builds
- _Operating system:_NA
- _Browser:_Brave

**Comment by solazio** [comment]
@kz6fittycent thank you for reporting this. 

I can see that on https://snapcraft.io/openvas/builds you have failed builds that roughly match the time of your commits, however I cannot tell if this was triggered automatically or manually. Please confirm.

For https://snapcraft.io/bpytop/builds I can see there are two commits which don't have any corespondent builds - at least in terms of time.

We will investigate and come back to you.

**Comment by jkfran** [comment]
Hello @kz6fittycent ,

Can you confirm if you are using GitHub webhooks using the old domain (build.snapcraft.io) in your repos?

Please update them if that the case, read the following blog article where we explain it:
https://snapcraft.io/blog/we-are-changing-the-way-you-build-snaps-from-github-repos

Let me know.

**Comment by kz6fittycent** [comment]
Here are the settings for `bpytop` (see screenshots). I've made no changes to the repos I'm having issues with. In fact, they were created after the changes for the build service occurred. I assume that's all automated now? Am I misunderstanding the documentation you provided? 

![Screenshot from 2020-09-04 09-57-08](https://user-images.githubusercontent.com/14829816/92253517-3847f880-ee95-11ea-8dd7-49f4f411bed4.png)
![Screenshot from 2020-09-04 09-57-01](https://user-images.githubusercontent.com/14829816/92253526-3a11bc00-ee95-11ea-922e-47ad7fc7b8ec.png)

**Comment by kz6fittycent** [comment]
I just triggered a manual build for `bpytop` and it seems to be running - at least the little wheels are turning ;)

**Comment by jkfran** [comment]
Hi @kz6fittycent ,

We are going to close the issue, thank you for reporting it!
