### ISSUE TITLE
GitKraken Crash on Manjaro

### ISSUE THREAD

**Issue by ADSG95** [canonical-web-and-design/snapcraft.io#3047]
### Steps to reproduce the problem
When you try to colone or open a repository, and you choose your local directory for the repository, the program closes 
unexpectedly. 
### Specs

- _URL:_https://snapcraft.io/install/gitkraken/manjaro
- _Operating system:_Manjaro KDE 20.0.3 Lysia
- _Browser:_Chromium

**Comment by tbille** [comment]
Hi,
Thanks for reporting this issue.
this is the repository for the website snapcraft.io. You can [contact the gitkraken](https://www.gitkraken.com/contact) team in case the issue comes from the snap.
In case you think it comes from snap then you can open an issue on [snapd repo](https://github.com/snapcore/snapd/) and explain your issue.

**Comment by ricardofdc** [comment]
I have the same problem!

**Comment by gusandrianos** [comment]
Same here, Manjaro stable gnome...

**Comment by alrabe** [comment]
same here

**Comment by alrabe** [comment]
Try this:
`sudo pacman -S gdk-pixbuf2
sudo mkdir -p /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0
sudo gdk-pixbuf-query-loaders > loaders.cache
sudo mv loaders.cache /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/
`

**Comment by 1madfitter** [comment]
> When starting Gitkraken from the terminal you can see some errors. One is about a broken loaders.cache.
> Don't know exactly what this is, but I solved it using the following commands:
> 
> `sudo pacman -S gdk-pixbuf2`
> `sudo mkdir -p /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0`
> `sudo gdk-pixbuf-query-loaders > loaders.cache`
> `sudo mv loaders.cache /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/`
> 
> I would like to reopen this, only to see if the snap team can do something about this or not, but I guess I have no rights to do so.

Thank you for this. I was about to get really upset.

**Comment by Samuel-ZDM** [comment]
@albertkol you are a god. I didn't know what else to do to fix this.

Thank you very much!

**Comment by JasonSweatt** [comment]
Thanks this saved me for the troubles, after building a new VM over the past weekend using Manjaro xfce latest version 21.0.6  
```
When starting Gitkraken from the terminal you can see some errors. One is about a broken loaders.cache.
Don't know exactly what this is, but I solved it using the following commands:

sudo pacman -S gdk-pixbuf2
sudo mkdir -p /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0
sudo gdk-pixbuf-query-loaders > loaders.cache
sudo mv loaders.cache /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/

I would like to reopen this, only to see if the snap team can do something about this or not, but I guess I have no rights to do so.
```

**Comment by TheBronx** [comment]
I downloaded the `tar.gz` package from their website and that one works perfectly fine.
The snap crashes whenever you try to browse the disk to open a repo.

Just don't use the snap, it is broken :(

**Comment by rogueco** [comment]
> 

Hero. I was starting to get upset. Thanks man.
