### ISSUE TITLE
Twilio Authy App Multiple Errors and Freeze in CentOS 8.

### ISSUE THREAD

**Issue by downystreet** [canonical-web-and-design/snapcraft.io#3052]
### Expected behaviour
When entering ./authy into the terminal the app should open and you should be able to enter your phone number into the boxes and proceed through to the next step in the app.
### Steps to reproduce the problem
When executing ./authy to launch the app it opens up normally with multiple errors in the command terminal. When you go to type your phone number into the box, it lets you type one number and then proceeds to freeze up making a force quit necessary.
### Specs
OS: Centos 8 
Authy Version: beta 1.8.3

Terminal readout using ./authy: 
Gtk-Message: 11:55:52.105: Failed to load module "pk-gtk-module"
Gtk-Message: 11:55:52.160: Failed to load module "pk-gtk-module"
TypeError: Cannot read property 'then' of undefined
    at Function.AutoUpdater.init (/snap/authy/5/resources/app.asar/js/background.js:63422:22)
    at Object.create (/snap/authy/5/resources/app.asar/js/background.js:56845:34)
    at App.WindowHelper.create (/snap/authy/5/resources/app.asar/js/background.js:13670:32)
    at App.emit (events.js:208:15)
[614881:0909/115557.264011:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
Killed

Terminal readout using ./authy --disable-gpu: 
Gtk-Message: 12:14:47.503: Failed to load module "pk-gtk-module"
Gtk-Message: 12:14:47.509: Failed to load module "pk-gtk-module"
TypeError: Cannot read property 'then' of undefined
    at Function.AutoUpdater.init (/snap/authy/5/resources/app.asar/js/background.js:63422:22)
    at Object.create (/snap/authy/5/resources/app.asar/js/background.js:56845:34)
    at App.WindowHelper.create (/snap/authy/5/resources/app.asar/js/background.js:13670:32)
    at App.emit (events.js:208:15)
(node:617348) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:617348) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:617251) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:617251) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

Running ./authy --disable-gpu solves the problem somewhat. I started authy with this and it looked like it was going to freeze like normal but as I was typing this report it magically started working and I was able to complete what I needed to do in the app.

**Comment by tbille** [comment]
Hi,
Thanks for reporting this issue. This is the repository for the site snapcraft.io
The error you are showing seems to come from the application. You can contact the maintainers directly, see Contact details: https://snapcraft.io/authy
Or if you think it comes from snaps then I would suggest raising this issue in the [forum](https://forum.snapcraft.io/) directly.
