### ISSUE TITLE
New snap builds fail to release

### ISSUE THREAD

**Issue by kz6fittycent** [canonical-web-and-design/snapcraft.io#3054]
### Expected behaviour
Newly built snaps fail to release

### Steps to reproduce the problem
trigger build - build is successful -fails to release
Site claims that the snap is in `devmode` : it is not. See: [https://github.com/kz6fittycent/ncdu-snap/blob/master/snapcraft.yaml](https://github.com/kz6fittycent/ncdu-snap/blob/master/snapcraft.yaml )

### Specs

- _URL:_ [https://snapcraft.io/ncdu/builds](https://snapcraft.io/ncdu/builds)
- _Operating system:_ N/A
- _Browser:_ Brave

**Comment by jkfran** [comment]
Hello @kz6fittycent 

It seems that for some reason your snap requires human approval, I can see the following output:
> "human review required due to 'allow-installation' constraint (bool)"
> https://launchpad.net/~build.snapcraft.io/+snap/7aca85b1ca1d061275d53264d6f8ed7a/+build/1114553

I will get back to you with more information.

**Comment by popey** [comment]
You should have received an email from the store telling you the revisions failed to release. This is why. If you haven't yet, you should request access to these interfaces on the snapcraft forum.

```
human review required due to 'allow-installation' constraint (bool) declaration-snap-v2_plugs_installation (ncdu, system-files)
human review required due to 'allow-installation' constraint (bool) declaration-snap-v2_plugs_installation (ncdu, personal-files)
```

**Comment by kz6fittycent** [comment]
I see. I never got the emails and I didn't know to look on Launchpad. I'll get that going on the forum. Thanks all. Closing this ticket.
