### ISSUE TITLE
How to launch stickynotes on Raspbian

### ISSUE THREAD

**Issue by cookiemonsterthesecond** [canonical-web-and-design/snapcraft.io#3055]
I've successfully installed stickynotes and a couple of other snaps on my Raspberry Pi4, but don't know how to launch the application from the command line. They don't show up anywhere on my list of apps on the desktop. Can anyone help please?

**Comment by tbille** [comment]
Hi there,
thank you for reporting this issue. This is the repository for the website snapcraft.io 
Could you ask your question on the forum directly: https://forum.snapcraft.io/ I am sure someone will be happy to help you :smile: 

Closing the issue.
