### ISSUE TITLE
Unable to see build summary for all snaps

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#3057]
### Expected behaviour

A useful feature of the "old" build.snapcraft.io site was a summary page which listed all my snaps, and indicated which ones failed to build. This enabled me to scan through the list, looking for potential issues, and solve them. It's useful as a one-page view of "how are my builds?" without needing to drill down on every single application.

This feature was never carried over to the new snapcraft.io/build implementation.

This is useful for people who have more than one snap. I appreciate I'm at the far end of the "has a lot of snaps" scale, but I'm not alone in having more than a couple. It would be useful to perhaps add a column to the "my snaps" page which lazy loads an icon (emoji?) indicating the build status, which, when clicked on, takes you directly to the build page.

**Comment by jkfran** [comment]
This was implemented in the `status` column on the listing page (`/snaps`)
