### ISSUE TITLE
KeepassXC information out of date

### ISSUE THREAD

**Issue by padraic7a** [canonical-web-and-design/snapcraft.io#3058]
### Expected behaviour
Link to usage tips should be correct

### Steps to reproduce the problem
1. Click on link in "For usage tips see: https://github.com/keepassxreboot/keepassxc/wiki/Snap-Tips"
2. Find that the page doesn't exist and that the wiki on the github site doesn't have a similar page

I googled around and found that there is a 'browser help script' for the snap linked to from here; https://keepassxc.org/download/#linux 
this should probably replace the current text.

**Comment by tbille** [comment]
hey @padraic7a ,
thanks for reporting this issue.

This repo is for the website snapcraft.io. For snaps related issues you can go directly in [the forum](https://forum.snapcraft.io/categories) or talk with the [developers directly](https://github.com/keepassxreboot/keepassxc)

Closing this issue.
