### ISSUE TITLE
Extra blank image on screenshot upload

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#3060]
### Expected behaviour
The [ + ] to be the last item

### Steps to reproduce the problem
Upload 3 images? Or just look at https://snapcraft.io/kakoune/listing in a narrower window

### Specs

- _URL:_
- _Operating system:_
- _Browser:_

**Comment by solazio** [comment]
@Lukewh thanks for highlighting this issue. For the moment we decide to keep the [ + ] always positioned after the last image uploaded, otherwise it doesn't really make sense on big screens when you see all of them on one row.

**Comment by Lukewh** [comment]
Makes sense. This:
![Screenshot from 2020-10-01 13-07-37](https://user-images.githubusercontent.com/479384/94807128-1c2d6d80-03e7-11eb-8868-1c63a246a78a.png)
just looks weird to me
