### ISSUE TITLE
VSCode Crashes after Installing

### ISSUE THREAD

**Issue by irevenko** [canonical-web-and-design/snapcraft.io#3064]
### Steps to reproduce the problem

```sudo snap install --classic code```
Open VSCode and press ```Open Folder``` Button

### Specs

- _Operating system:_ Fedora 32 (Workstation Edition) x86_64

**Comment by tbille** [comment]
hey @irevenko ,
thanks for reporting this issue.

This repo is for the website snapcraft.io. For snaps related issues you can go directly in [the forum](https://forum.snapcraft.io/categories).

Closing this issue.
