### ISSUE TITLE
Docs: how do snap pkgs handle shared dependencies?

### ISSUE THREAD

**Issue by geekley** [canonical-web-and-design/snapcraft.io#3068]
This [askubuntu post](https://askubuntu.com/questions/787149/how-do-snap-packages-handle-shared-dependencies) has some questions:
> The snap packaging format finally frees us from dependency hell by allowing each package to have its own copy of dependencies. I'm interested in the technical details in how it does this. How does it handle:
>- snaps depending on the version of a library already installed via deb packages for the current release?
>  Does it ignore the installed library?
>- different snaps specifying the same version of the same library? Does it do deduplication somehow?
>- updates to core libraries that are likely to be used by a lot of snaps? OpenSSL comes to mind as a huge pain point.

How are those things handled currently?
Are there deduplication strategies for the first 2 implemented already, or in a roadmap to be implemented in the future?
Can you add the answers to official docs, if possible (at least about whether or not it does deduplication)?

**Comment by tbille** [comment]
hi @geekley
For this kind of questions I suggest asking directly on the [forum](https://forum.snapcraft.io/).
The is the repo for the website :) 

Closing the issue.
