### ISSUE TITLE
Internal Server Error on Builds page

### ISSUE THREAD

**Issue by capruro** [canonical-web-and-design/snapcraft.io#3099]
### Expected behaviour
access build pages regularly

### Steps to reproduce the problem
After trigger a new build on tautulli snap, something went very bad: every time I now click on build tab I got Internal Server Error
https://snapcraft.io/tautulli/builds
I don't know if it's global issue, but more users experience the same. I don't have the problem on all of my snaps.

I posted on [snapcraft forum](https://forum.snapcraft.io/t/internal-server-error-on-builds-page-for-tautulli-snap/20358) as well: seems more users experience the same issue.

**Comment by tbille** [comment]
Hey @capruro thanks for reporting this bug.

It seems that we have an issue on one of our modules: `ZeroDivisionError: float division by zero` (classic :smile: ). It seems to come from here: https://github.com/canonical-web-and-design/canonicalwebteam.launchpad/blob/master/canonicalwebteam/launchpad/models.py#L128

Need to investigate a bit more with the response from the Launchpad API.

For internal contributors see [sentry issue](https://sentry.is.canonical.com/canonical/snapcraft-io/issues/11347/?query=is%3Aunresolved).

**Comment by jkfran** [comment]
This is now fixed after updating our Launchpad library with https://github.com/canonical-web-and-design/snapcraft.io/pull/3100.

Thank you!
