### ISSUE TITLE
[legal] Update Snap Store privacy notice

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/snapcraft.io#3114]
Based on [this brief](https://docs.google.com/document/d/1xZaVD4x85869-ljEVlzZzZIT7LAYpwf-ZIlhhX2c998/edit)

> Updates to https://snapcraft.io/ when new user first logs in: I can’t seem to replicate this, but the name of the agreement will need to be updated and an overall review of the display at that point (I recall it had the name of the agreement in two places and it wasn’t the same)

Wait for these to land to link [#8443](https://github.com/canonical-web-and-design/ubuntu.com/issues/8443) and [#8444](https://github.com/canonical-web-and-design/ubuntu.com/issues/8444)

**Comment by lilyvidenova** [comment]
From what it looks like to me, we need to rename the footer link from "Legal information" to "Terms of Service", pointing to https://ubuntu.com/legal/terms-and-policies/snap-store-terms 

I can't seem to figure out where the login links would be as s.io just uses your UbuntuOne account... @tbille am I missing something? 

The deliverables from the brief that apply to us:
![image](https://user-images.githubusercontent.com/17980375/96586525-05d54c00-12d9-11eb-85cb-9b0d529a73f6.png)

**Comment by solazio** [comment]
there is the /account/agreement page which has "Developer Terms and Conditions" and links to https://ubuntu.com/legal/developer-terms-and-conditions

is that supposed to become "Terms of Service" as well?

![image](https://user-images.githubusercontent.com/40214246/96691777-38d11b80-137d-11eb-80f3-a202c6c6bc3d.png)

**Comment by pmahnke** [comment]
@solazio I assume that the link to "Developer Terms and Conditions" needs to be changed to "Snap Store Terms of Service" and the heading as well from "Canonical Terms..." to "Snap Store Terms of Service and Privacy Notice"
