### ISSUE TITLE
The latest Vanilla Framework made selected link in header navigation bar look very ugly

### ISSUE THREAD

**Issue by fitojb** [canonical-web-and-design/snapcraft.io#3120]
Pure white doesn’t fit with the bar immediately below the main navigation, which is slightly blue. Besides, its stark contrast makes the hover animation too extreme.
What was wrong with just adding a colored line?

**Comment by tbille** [comment]
hey @fitojb

thanks for reporting this. Vanilla team is actually working on this https://github.com/canonical-web-and-design/vanilla-framework/issues/3364

We'll make the update as soon as it's ready :)

**Comment by fitojb** [comment]
Fixed in the new Vanilla!
