### ISSUE TITLE
The metrics popover labels are short truncated making them impossible to tell some appart

### ISSUE THREAD

**Issue by seb128** [canonical-web-and-design/snapcraft.io#3121]
Loading https://snapcraft.io/snap-store/metrics?active-devices=channel on firefox 81 on Ubuntu focal, the snap has some channels 'ubuntu-<serie>' but the popover legend is truncated after a few chars so it's impossible to tell them apart

The screenshot shows the issue (truncated to no display private information)

![snapstore](https://user-images.githubusercontent.com/10974330/96263717-9bb06480-0fc3-11eb-9e79-4cd74b1a489d.png)

**Comment by tbille** [comment]
Hi,
thanks for reporting this issue. We will update this soon. 

Closing this issue since duplicate https://github.com/canonical-web-and-design/snapcraft.io/issues/1848
