### ISSUE TITLE
snap builds fail if emoji in the snapcraft.yaml

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/snapcraft.io#3143]
### Expected behaviour

Snap build don't failt

### Steps to reproduce the problem

Make a snap. Add an emoji in the summary (or description)
Attach the snap to the automatic build
It fails, and doens't show up in the list of builds, I had to go on launchpad to find out the issue.
See: https://launchpad.net/~build.snapcraft.io/+snap/0b570829cbb30c7e12fc104a3fc69d2d

**Comment by jkfran** [comment]
I created the following ticket to see if we Launchpad could support emojis:
https://bugs.launchpad.net/launchpad/+bug/1920751

**Comment by cjwatson** [comment]
Thanks for reporting this.  We should have it fixed in Launchpad soon.

**Comment by cjwatson** [comment]
This should be fixed now.

**Comment by jkfran** [comment]
@cjwatson thank you!
