### ISSUE TITLE
Publisher views

### ISSUE THREAD

**Issue by spencerbygraves** [canonical-web-and-design/snapcraft.io#3154]

**Comment by lilyvidenova** [comment]
Just to mention it here too - we don't need visuals for these this cycle, the pages that will be built this cycle are the [Admin](https://app.zeplin.io/project/5f3170425822f41fc299a330/dashboard?seid=5f6b7586f1354f87cb6ba136) and [Viewer](https://app.zeplin.io/project/5f3170425822f41fc299a330/dashboard?seid=5f6b75fe14ccd74bab05e266) views.

**Comment by spencerbygraves** [comment]
@lilyvidenova ok, thanks 👍
