### ISSUE TITLE
Admin views

### ISSUE THREAD

**Issue by spencerbygraves** [canonical-web-and-design/snapcraft.io#3155]

**Comment by spencerbygraves** [comment]
@lilyvidenova designs added to [Zeplin](https://app.zeplin.io/project/5f3170425822f41fc299a330/dashboard?seid=5facf88c49a2ce0b2519a517).

**Comment by lilyvidenova** [comment]
These are great, just missing the manage users view

**Comment by spencerbygraves** [comment]
@lilyvidenova yes, sorry. I have one screen left to add in each view.
