### ISSUE TITLE
docs miss Scriptlet link in left menu

### ISSUE THREAD

**Issue by fcole90** [canonical-web-and-design/snapcraft.io#3172]
In the docs, there is no link (or at least not a visible one) to the scriptlet page https://snapcraft.io/docs/scriptlets

### Expected behaviour
To have a link in docs https://snapcraft.io/docs to such page

### Steps to reproduce the problem
Just go here https://snapcraft.io/docs and search the Scriptlet word

### Specs

- _URL:_ https://snapcraft.io/docs, https://snapcraft.io/docs/scriptlets
- _Operating system:_ NA
- _Browser:_ NA

**Comment by degville** [comment]
Unfortunately, we can't currently fit every page in the navigation. I have linked to _Scriptlets_ from the Adding parts and lifecycle doc, but adding adding _Scriptlets_ to the navigation is something we'll do when we hopefully move to a new docs structure.
