### ISSUE TITLE
Which fields were updated on release? 

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/snapcraft.io#3175]

**Comment by lilyvidenova** [comment]
I think the best way to highlight which fields were updated on release is to use the "tour" feature already available on s.io

[Zeplin](https://app.zeplin.io/project/5fabc5daea5f461efe934955/dashboard?seid=5fb697c5648312846b94ad1f)

**Comment by lilyvidenova** [comment]
@clagom @tbille - wanna take a look? :)

**Comment by tbille** [comment]
That's nice.

I think showing a modal with a diff would be enough. As an example of diff you can see discourse, here I can see rapidly what has changed from one to the other.

![image.png](https://images.zenhubusercontent.com/583afafbb9dc3c6220228d0c/8075b86c-e135-4479-8710-f5962cf21d6c)

I think a field comparison similar would be nice.

Changes of metadata don't happen often and we should make sure that the user understands that he is about to overwrite some potentially critical fields (description, icon etc.).  We could show the modal when the user presses release. With something like `You are about to overwrite those fields: x vs y etc. Are you sure you want to proceed?`

What do you think?

**Comment by lilyvidenova** [comment]
Hmmm, I don't think it would require a confirmation as it's information you have decided to change, thus a message informing you of that happening before you click on "Save" to release I think is enough.

The modal with changes - that could work, I was trying to highlight just what has changed and in the context where you could do something about it. I will wireframe the modal too and we can see what makes sense.

**Comment by clagom** [comment]
Let's explore both options, to discuss

**Comment by lilyvidenova** [comment]
[Wireframes](https://app.zeplin.io/project/5fabc5daea5f461efe934955/screen/5fbbcdee8f3c2a70484bfaa1/) of a similar pop-up with the changes side-by-side. 

There is an option with or without buttons (I'm really not sure how to word those properly so if we go with that option, I'd need a bit of help).

**Comment by clagom** [comment]
Left a couple of questions/comments for the follow up

**Comment by cristinadresch** [comment]
@lilyvidenova @tbille to discuss follow up options and then sync with other teams
