### ISSUE TITLE
Build Upload Metadata

### ISSUE THREAD

**Issue by cristinadresch** [canonical-web-and-design/snapcraft.io#3177]

**Comment by cristinadresch** [comment]
@tbille do you remember what is the status of this?

cc @AnnSoMuller

**Comment by steverydz** [comment]
@cristinadresch we have been waiting for the go ahead from Cristian. He got in touch with me today to say that there is something missing so I have made a ticket to do that next iteration: https://github.com/canonical-web-and-design/snapcraft.io/issues/3582

**Comment by cristinadresch** [comment]
nice thanks @steverydz and this ticket https://github.com/canonical-web-and-design/snapcraft.io/issues/3323 is it still required, do you know?

**Comment by steverydz** [comment]
No, I've closed it
