### ISSUE TITLE
snap install unifi edge on amd64

### ISSUE THREAD

**Issue by pricepe32** [canonical-web-and-design/snapcraft.io#3181]
### Expected behaviour
Need "snap install unifi --edge" to install on architecture (amd64)

Has anyone done this successfully or know of a compiler or cross compiler that can that can make the snapcraft.yaml amd64 friendly?  ;-)  

### Steps to reproduce the problem
snap install unifi --edge
error: snap "unifi" is not available on edge for this architecture (amd64) but exists on other
       architectures (arm64).

### Specs

- _URL:_https://snapcraft.io/install/unifi/rhel
- _Operating system:_RHEL8
- _Browser:_

**Comment by popey** [comment]
Hi. Thanks for the issue. Unfortunately this is the wrong place for it though. This repo deals with the website itself, not specific snaps. The snap you're after is built from configuration over at [this repo](https://github.com/hairychris/unifi-snap) so you can file an issue to discuss your requirements with the author [here](https://github.com/hairychris/unifi-snap/issues). Thanks again!

**Comment by pricepe32** [comment]
Thx guys!
