### ISSUE TITLE
Sketch links on snap listing page

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/snapcraft.io#3185]
There are a lot of links to different things on the snap listing page, maybe we could organise them in a better way?

**Comment by lilyvidenova** [comment]
[Options for links](https://app.zeplin.io/project/5fc79952c5a29d103fe58489/dashboard?seid=5fc799f0114bcb0e0b143e2a)

**Comment by lilyvidenova** [comment]
@clagom when you've got a minute to take a look, please :) 

Will show them at the advocacy/design sync today too

**Comment by clagom** [comment]
Cool, let's see what they say. Do you want to close this and open another issue for 'charmhub-like' layout exploration? Or keep working on here?

**Comment by lilyvidenova** [comment]
I've already uploaded that to Zeplin.

Alan and Sergio both like the chamhub-like option.

Btw, I'm working in [this Miro board](https://miro.com/app/board/o9J_lcq5cSk=/)

**Comment by clagom** [comment]
Never mind it popped in already :D
