### ISSUE TITLE
Wireframe proposal(s) 

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/snapcraft.io#3186]

**Comment by lilyvidenova** [comment]
Added [screens](https://app.zeplin.io/project/5fc79952c5a29d103fe58489/dashboard?seid=5fce122f4c650959c5a2e274) for editing the fields. 

@clagom - can you take a look? Also, as we spoke about the difference between wireframes and visual - should I leave my wireframes as they are to go into visual? Or should I re-do them using Vanilla?

**Comment by clagom** [comment]
(Looking), you can leave as they are and ask @cristinadresch to find some time for visual designers to work on it. Unless you want to start doing that, then sure you can vanillarise it if you want and get reviewed by visuals.

**Comment by clagom** [comment]
Thanks, LGTM

**Comment by lilyvidenova** [comment]
I'll leave them as they are - it'll be great if Cris can get someone to do the visuals
