### ISSUE TITLE
Snap failing to build 4/6 archs

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/snapcraft.io#3212]
Original issue: https://github.com/JackDandy/SickGear/issues/15

@jkfran Is it possible that there is an issue with Launchpad builds on our side?

**Comment by jkfran** [comment]
I replied to the issue https://github.com/JackDandy/SickGear/issues/15#issuecomment-732369471

Launchpad has been in maintenance recently. We need to ask if we can get this information for the API, check the banner that Launchpad is showing:
![image](https://user-images.githubusercontent.com/6353928/100005438-dbd3e580-2dc0-11eb-9721-780718c5b3e2.png)
