### ISSUE TITLE
Replace sass-lint with stylelint

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/snapcraft.io#3223]
The standard for all our projects is now stylelint so we should replace sass-lint

**Comment by anthonydillon** [comment]
A gotta I ran into this week is that react-components project requires the parent project to contain `node-sass` to compile. https://github.com/canonical-web-and-design/react-components/issues/327

**Comment by bartaz** [comment]
> A gotta I ran into this week is that react-components project requires the parent project to contain `node-sass` to compile. [canonical-web-and-design/react-components#327](https://github.com/canonical-web-and-design/react-components/issues/327)

I think linting doesn't have anything to do with node-sass. stylelint is used in place of sass-lint in most our projects for a while now.

**Comment by steverydz** [comment]
I've had the same issue working when I added react components to 360. Whether or not we use sass lint or stylelint shouldn't have any bearing on that. We use stylelint now on most if not all the websites.
