### ISSUE TITLE
Bad gateway

### ISSUE THREAD

**Issue by fiftin** [canonical-web-and-design/snapcraft.io#3224]
### Expected behaviour
View account page
### Steps to reproduce the problem
* Login to snapcraft.io
* Go to account page
![image](https://user-images.githubusercontent.com/914224/100329166-26d34000-2fef-11eb-9b2c-e38d8430f50d.png)
### Specs

- _URL:https://snapcraft.io/snaps
- _Operating system: MacOS
- _Browser: Chrome

**Comment by fiftin** [comment]
I don't know if this is related, but before got this error I:
1) Renamed username from **xxx** to **yyy** via login.ubuntu.com page.
2) Registered new user with username **xxx**.
3) Logged in to snapcraft.io as **xxx**.

**Comment by tbille** [comment]
hey @fiftin 
I think it might be the issue. Let me have a look to see what happened there.

**Comment by tbille** [comment]
@fiftin could you let us know if you still have the issue. Just to be sure if it's something that due to some outage?

If you still have the issue would you mind sharing your username so we can dig (you can mail me directly to toto@canonical.com if you don't want to put it publicly :) )

**Comment by fiftin** [comment]
@tbille Yes, problem hasn't gone away. Do you need any account details?

**Comment by tbille** [comment]
@fiftin just the username you set should be fine

**Comment by fiftin** [comment]
username: fiftin

**Comment by fiftin** [comment]
Hi @tbille, @cristinadresch  Any updates by issue?

**Comment by dehnert** [comment]
I'm also persistently seeing "Bad Gateway" when visiting https://snapcraft.io/snaps or https://snapcraft.io/account/details -- it's been something like a month since I first started seeing this. I'm "adehnert" on Launchpad.

**Comment by dehnert** [comment]
I'm still seeing this. AFAIK, this means my snap has packages with pending security updates that I'm not sure I can take...

**Comment by fiftin** [comment]
Me too.

**Comment by jkfran** [comment]
@roadmaster Do you any idea what could be the issue with these accounts? I have some logs for `/snaps` with the following response from `https://dashboard.snapcraft.io/dev/api/account`:
```
user-not-ready: Developer profile is missing the store username.
```

**Comment by jkfran** [comment]
@fiftin and @dehnert there is an issue on snapcraft.io with your accounts, it is something we need to fix on our side, until that happens you should be able to fix your accounts by setting a username on:
https://dashboard.snapcraft.io/dev/account/

Please let me know

**Comment by dehnert** [comment]
Huh. I tried logging in again, and it seemed to just work now. Going to  https://dashboard.snapcraft.io/dev/account/, I already seemed to have a username (adehnert) set. I'm not sure if y'all did something.

**Comment by fiftin** [comment]
Yes, It helped me! Thank you!

**Comment by fiftin** [comment]
@jkfran How I can change Full name of my Dev account?

Currently I have different data on:
- https://dashboard.snapcraft.io/dev/account/ (Denis Gukov / ansible-semaphore)
- https://snapcraft.io/account/details (Ansible Semaphore / fiftin)
- https://login.ubuntu.com/  (Ansible Semaphore / ansible-semaphore).

It is very very strange. I what to do Ansible Semaphore / ansible-semaphore everywhere .

**Comment by Roadmaster** [comment]
@fiftin :

1. go to https://login.ubuntu.com/
2. change your details as required (full name)
3. save
4. go to https://dashboard.snapcraft.io/
5. logout
6. login
7. go to https://dashboard.snapcraft.io/dev/account/
8. change details again
9. save

Let me know if it works.

**Comment by dehnert** [comment]
> Huh. I tried logging in again, and it seemed to just work now. Going to https://dashboard.snapcraft.io/dev/account/, I already seemed to have a username (adehnert) set. I'm not sure if y'all did something.

Oh, interesting. https://launchpad.net/~adehnert lists two email addresses for me. It appears that when I use one of them (the second one on that page right now) in the login field, I get the "Bad gateway" error, https://dashboard.snapcraft.io/dev/account/ doesn't list a username, and filling in "adehnert" tells me the username needs to be unique. When I use the other email address to log in, everything seems to work fine, and https://dashboard.snapcraft.io/dev/account/ tells me my username is "adehnert". I guess the Launchpad model is presumably that one account can have several email addresses, and the Snap Store model associates each account with one email address, but uses the Launchpad username as the Snap username, and consequently explodes?

**Comment by fiftin** [comment]
> @fiftin :
> 
> 
> 
> 1. go to https://login.ubuntu.com/
> 
> 2. change your details as required (full name)
> 
> 3. save
> 
> 4. go to https://dashboard.snapcraft.io/
> 
> 5. logout
> 
> 6. login
> 
> 7. go to https://dashboard.snapcraft.io/dev/account/
> 
> 8. change details again
> 
> 9. save
> 
> 
> 
> Let me know if it works.

Yes, it works, thank you!
