### ISSUE TITLE
Can not subscribe to blog posts

### ISSUE THREAD

**Issue by fiftin** [canonical-web-and-design/snapcraft.io#3225]
### Expected behaviour
Checkbox "Blog posts delivered" is up.

### Steps to reproduce the problem
* Go to account settings
* Check the box "Blog posts delivered"
* Click "Save email preferences"
* No effect
### Specs

- _URL:https://snapcraft.io/account/details
- _Operating system:MacOS
- _Browser:Chrome
![image](https://user-images.githubusercontent.com/914224/100337290-01e3ca80-2ff9-11eb-84d4-b7361e24e843.png)

**Comment by tbille** [comment]
@fiftin I wonder if this is relevant to this too: https://github.com/canonical-web-and-design/snapcraft.io/issues/3224

**Comment by jkfran** [comment]
Hi @fiftin we believe this could be related to the other issue we solved with your account. Please reopen if it needs investigation.
