### ISSUE TITLE
Snap App icon in the embedded iframe is too large 

### ISSUE THREAD

**Issue by keshavbhatt** [canonical-web-and-design/snapcraft.io#3232]
The app icon inside the embedded iframe (code peovided by publicize section) is too big especially for mobile devices. 
example : http://www.ktechpit.com/ubuntu/currency-converter-for-linux-desktop/

How to reproduce : open the given example link on any mobile device (I tried it on Samsung's s7 edge) notice the app icon size in embedded iframe in the post. I have noticed this in other embedded iframes too. It would ve nice to have icon of decent size to keep the frame more readable on devices with small form factors. 

Thanks

**Comment by tbille** [comment]
Hey, thanks for reporting this issue. We are checking what happened here. We'll let you know when this is fixed.

**Comment by keshavbhatt** [comment]
![](https://i.imgur.com/WqtzPCA.jpg) see the icon of app inside iframe.

**Comment by solazio** [comment]
@keshavbhatt thanks for reporting this issue. We fixed it in this PR https://github.com/canonical-web-and-design/snapcraft.io/pull/3247
Closing...
