### ISSUE TITLE
Missing style sheet

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#3246]
### Expected behaviour

Embedded cards should look nice, but the stylesheet is missing so they don't
This was reported on the [forum](https://forum.snapcraft.io/t/embeddable-cards-lacking-style-css-url-returning-404/21416).
This CSS file is missing. https://snapcraft.io/static/css/styles-embedded.css

### Steps to reproduce the problem

As a publisher, go to the publicise tab, to get an embedded card code.
Note the page looks okay, but the card is unstyled (Times New Roman font for example).

![Publicise DOSBox-X](https://user-images.githubusercontent.com/1841272/100860584-99796b00-3488-11eb-9c32-791956918e22.png)

### Specs

- _URL:_ https://snapcraft.io/dosbox-x/publicise/cards
- _Operating system:_ Ubuntu
- _Browser:_ Chrome

**Comment by solazio** [comment]
This was fixed in https://github.com/canonical-web-and-design/snapcraft.io/pull/3247
Thanks for reporting it. Closing
