### ISSUE TITLE
"Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data" when requesting new build

### ISSUE THREAD

**Issue by OddBloke** [canonical-web-and-design/snapcraft.io#3276]
### Expected behaviour

New build is queued, no error is shown.

### Steps to reproduce the problem

1. Navigate to https://snapcraft.io/jenkins-job-linter/builds/1209143 as my user
2. Click "Trigger new build"

### Specs

- _URL:_ https://snapcraft.io/jenkins-job-linter/builds/1209143
- _Operating system:_ Ubuntu
- _Browser:_ Firefox

**Comment by solazio** [comment]
Thank you for reporting this @OddBloke. You were getting the error because it is not possible to trigger a single new build (for only one architecture). Basically the `Trigger new build` button was not supposed to be visible on that view.

I've put in a PR to fix the issue by removing the button.
