### ISSUE TITLE
Search doesn't query developer name

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#328]
https://snapcraft.io/search?q=jetbrains

This only shows 8 results, omitting (for example) https://snapcraft.io/kotlin

The results returned have the term "jetbrains" in the app description. However, all of the apps (including those omitted from results) are from the same developer - "Jetbrains". So it looks like we're not searching in the developer field, only the name and description of the snap. 

It would be super useful for us to be able to see all snaps from a particular developer.

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/11JP2Qzf_a1qe9U7ipaY03_Vd_0fyePnOWy1MsiZ3MnY/edit#heading=h.etqx5nr2fybh): “Search results should include every public snap that matches all of the non-greylisted search terms. A snap _matches_ a search term if that term is present (case-insensitively) in the snap title, publisher name, category name, or description. Test case: Searching for ‘jetbrains ultimate’ should return Jetbrains’ IDEA Ultimate.”

**Comment by solazio** [comment]
This seems to work fine now. It shows 15 results and `kotlin` is included, closing this issue. Please reopen if you think is not fixed.

![image.png](https://images.zenhubusercontent.com/5cb4608f97df763a9090bdec/d3d2be5d-0559-43f7-b6a0-493078df9efa)
