### ISSUE TITLE
RSS feed for blog

### ISSUE THREAD

**Issue by binkley** [canonical-web-and-design/snapcraft.io#3294]
### Expected behaviour

The nice Snapcraft blog should include an RSS feed.

### Steps to reproduce the problem

Examine the page source of a blog post: No meta tags for RSS or feeds.

Also, submit the blog URL to a feed reader: Reader unable to subscribe.

**Comment by tbille** [comment]
there is actually a RSS feed http://snapcraft.io/blog/feed
but good catch the meta tag is missing. Adding it now :smile:
