### ISSUE TITLE
Null snap issue with launchpad API

### ISSUE THREAD

**Issue by jkfran** [canonical-web-and-design/snapcraft.io#3320]
Issue reported by @popey on Mattermost:

"I am getting Internal Server Error at https://snapcraft.io/null/builds"

Looks like we can fix the issue by quoting the snap name on our launchpad module.

https://api.launchpad.net/devel/+snaps?ws.op=findByStoreName&owner=%2F~build.snapcraft.io&store_name=%27null%27
instead of
https://api.launchpad.net/devel/+snaps?ws.op=findByStoreName&owner=%2F~build.snapcraft.io&store_name=null

**Comment by jkfran** [comment]
Hey @popey 

Your null snap should be working now (Until next `null` issue)

**Comment by popey** [comment]
Excellent! Thank you
