### ISSUE TITLE
When adding an asciinema video to a snap, it doesn't show on the listing page

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/snapcraft.io#3359]
I have added an asciinema video to the following snap: https://snapcraft.io/teststeve1

The video is: https://asciinema.org/a/325730

When I go to the listing page, the video is not there.

**Comment by tbille** [comment]
To check if the info endpoint provides the data. Otherwise open a bug on store

**Comment by steverydz** [comment]
Bug reported here: https://bugs.launchpad.net/snapstore-server/+bug/1913759
