### ISSUE TITLE
Connecting Icon theme and gtk theme through 'snap connect' does not work

### ISSUE THREAD

**Issue by asif-hoda** [canonical-web-and-design/snapcraft.io#3380]
I installed the Whitesur gtk snap theme for my snap apps so that i can integrate my ubuntu into one theme. But after i connected the gtk3 theme and icon theme to all apps using the command given in the readme. But its only working for the snap store, apps like gimp are not accepting the theme.
Steps to reproduce:
1. Run this command to install the theme ```sudo snap install whitesur gtk theme```
2. then connect the theme to all apps using ```for i in $(snap connections | grep gtk-common-themes:gtk-3-themes | awk '{print $2}'); do sudo snap connect $i whitesur-gtk-theme:gtk-3-themes; done```
3. then connect the icon theme to all apps using ```for i in $(snap connections | grep gtk-common-themes:icon-themes | awk '{print $2}'); do sudo snap connect $i whitesur-gtk-theme:icon-themes; done```
4. Will not work for any apps except snap store.

![Screenshot from 2021-01-30 19-49-59](https://user-images.githubusercontent.com/47708014/106358902-07c99500-6335-11eb-9681-99fef7e2ed49.png)

As in the screenshot, the gimp icon did not update to the icon theme's icon. I did restart.

![Screenshot from 2021-01-30 19-50-25](https://user-images.githubusercontent.com/47708014/106358967-55de9880-6335-11eb-803f-065c57e43632.png)

In this screenshot the gimp system theme was supposed to change but it looks just like the default system theme. Please adress this issue.

OS : Ubuntu 20.04
Browser : Google Chrome
Processor : Intel 4200U
Graphics Card : Nvidia GT 740M

**Comment by tbille** [comment]
Hey thanks for reporting this issue. This is the repository for snapcraft.io website. For this type of issue I recommand opening a topic on the forum: https://forum.snapcraft.io/ 

Thanks,
Closing the issue.
