### ISSUE TITLE
snap store web UI missing published data

### ISSUE THREAD

**Issue by hellsworth** [canonical-web-and-design/snapcraft.io#3399]
### Expected behaviour
The published field in snapcraft.io/<package> should accurately display when the package was published to the channel.
![Screenshot from 2021-02-03 08-33-01](https://user-images.githubusercontent.com/12970280/106771160-e9e18600-65fb-11eb-97d9-e8d8f26a00ef.png)

### Steps to reproduce the problem

Go to https://snapcraft.io/libreoffice (or any other application). Click the drop down to expand the version box next to the big green install button and see that the Published field is empty except a comma.

### Specs

- _URL:_ https://snapcraft.io/libreoffice
- _Operating system:_ 20.10
- _Browser:_ Firefox (deb) version 85.0+build1-0ubuntu0.20.10.1

**Comment by jkfran** [comment]
Hi @hellsworth ,

We believe this was a cache issue and seems to be now solved, could you confirm? Try to hard refresh.

Thank you.

**Comment by jkfran** [comment]
Please reopen the issue if it is still happening.

**Comment by hellsworth** [comment]
Yep it's all fixed and thanks again!
