### ISSUE TITLE
We page not showing published date of snaps

### ISSUE THREAD

**Issue by alculete** [canonical-web-and-design/snapcraft.io#3402]
### Expected behaviour
Show published date of snaps
### Steps to reproduce the problem
open any snap, click on channels, snap published date not shown
### Specs

- _URL: https://snapcraft.io_
- _Operating system: Ubuntu 20.04.2 LTS x86_64_ 
- _Browser: Mozilla Firefox 85.0_

**Comment by jkfran** [comment]
Hi @alculete 

Could you please check if you are still having this issue? We believe your browser cached the wrong version of the JS code but it should by fine now.

Related: https://github.com/canonical-web-and-design/snapcraft.io/issues/3399

**Comment by alculete** [comment]
It is getting the dates now. Thank you.
