### ISSUE TITLE
Release UI: history table for a channel doesn't switch with track switch

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/snapcraft.io#3417]
### Expected behaviour
History table updates to the channel for the current track.

### Steps to reproduce the problem
1. Visit the release UI for a snap with tracks, e.g. https://snapcraft.io/maas/releases
2. Click on the :clock1: for a given channel, e.g. 2.9/edge amd64
3. Note the history table shows up with the history of that channel
4. Click the track dropdown and select a different track, e.g. 2.8

The bug is that the history table continues to show 2.9/edge amd64, and instead should switch to show 2.8/edge amd64

![image](https://user-images.githubusercontent.com/246192/108999211-e6d93300-7699-11eb-9fe5-4d509f0f4c9e.png)

### Specs

- _URL:_ https://snapcraft.io/maas/releases
- _Operating system:_ Ubuntu 20.04 LTS
- _Browser:_ Firefox 85.0.1

**Comment by tbille** [comment]
I managed to reproduce the issue. It seems that the state of the expanded table is not updated when changing track on the dropdown but the rest is.

If you need a workaround in the meantime @sparkiegeek you can click back on the :clock1: when you are on the selected track that you are looking at to refresh the history of releases.
