### ISSUE TITLE
No youtube embedded thumbnail on app listing page

### ISSUE THREAD

**Issue by keshavbhatt** [canonical-web-and-design/snapcraft.io#3441]
There is a video embedding feature in app listing page in snapcraft store, which is somehow bugged and doesn't shows video's thumbnail (see the screenshot attached)
![](https://i.imgur.com/ei5BoU1.jpg)

**Comment by steverydz** [comment]
Thanks for reporting this issue. So we can debug this, can you confirm whether or not set a thumbnail for video when you uploaded it to YouTube?

**Comment by keshavbhatt** [comment]
There use to be a thumbnail before. I noticed it is replaced with this new video not found image few days back.

**Comment by steverydz** [comment]
Thanks. We'll look into a more reliable way to fetch those images.
