### ISSUE TITLE
AMD snap package not building

### ISSUE THREAD

**Issue by johanneswilm** [canonical-web-and-design/snapcraft.io#3470]
Hey, for the fiduswriter snap package I have tried building a package on the snapcraft store. This worked until recently, but since yesterday, the AMD built process seems to get stuck. Under https://snapcraft.io/fiduswriter/builds/1340646 I just see "In progress" and no other output and it has been like that since yesterday. I tried rebuilding once, and the result was the same. All other packages (except i386) are building fine. It looks like I can only redo the packaging process for all platforms, so I don't want to kill your servers by doing that five times just because that one platform doesn't build. Is there anything I can do or is this a known issue?

**Comment by jkfran** [comment]
Hello @johanneswilm 

I can see that architecture is now released, I think the cause might have been a long queue for this architecture in the Launchpad builders (https://launchpad.net/builders), it is working fine with my snaps. Please reopen this issue if it happens again to you so we can investigate.
