### ISSUE TITLE
XAUTHORITY environment value is not a clean path

### ISSUE THREAD

**Issue by TCPMeta** [canonical-web-and-design/snapcraft.io#3472]
Just installed snap on my Raspberry Pi 4 and installed a couple of things such as the snap store and cool-retro-term and I get the following error.

2021/03/21 14:45:56.169863 cmd_run.go:573: WARNING: XAUTHORITY environment value is not a clean path: "/system/home/pi/.Xauthority"
cannot create user data directory: /home/pi/snap/cool-retro-term/154: Not a directory

The directory does exist and it seems it doesn't like the .Xauthority file.

**Comment by tbille** [comment]
Hi there,
thanks for reporting this issue. This repository tracks the development of the site snapcraft.io
I would suggest to go directly on the forum: https://forum.snapcraft.io to report this problem :)

Closing the issue.
