### ISSUE TITLE
We should have a different state for publicise pages if a snap is not published

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/snapcraft.io#3473]
- We should have a different state for publicise pages if a snap is not published
- The `/embedded` and `/badges.svg` endpoints should return 404 if the snap is not published

![image.png](https://images.zenhubusercontent.com/5cb4608f97df763a9090bdec/d4848a19-f696-4b43-a65e-5b4f3e46f2ad)

**Comment by danielmutis** [comment]
We could disable the embeddable cards item in the side navigation until they publish the snap. That's the only section they shouldn't be able to access until they publish it.

**Comment by Lukewh** [comment]
We have state if the snap is not set to public. We should probably update the messaging and check to ensure there is also a release:
![image.png](https://images.zenhubusercontent.com/59316f3551aa2c3057803f4b/4a689791-dbf2-45e9-8848-6e1d04c55349)I'm not sure this is relevant

**Comment by AnnSoMuller** [comment]
I agree with @Lukewh and then update the message while keeping consistency with the same state :)
