### ISSUE TITLE
Bad Gateway in category search

### ISSUE THREAD

**Issue by prowsu** [canonical-web-and-design/snapcraft.io#3480]
### Expected behaviour
View all available programs in Development category
### Steps to reproduce the problem
Try to browse an URL
### Specs

- _URL:_ https://snapcraft.io/search?category=development
- _Operating system:_ Ubuntu 20.04.2 x64
- _Browser:_ Google Chrome 89.0.4389.114

**Comment by tbille** [comment]
Hi, thanks for reporting this issue. It seems we had some issues yesterday but the site should be back online.
Closing the issue, if you see any other issues feel free to reopen.
