### ISSUE TITLE
Disneyland....

### ISSUE THREAD

**Issue by PaulinaParangerHr** [canonical-web-and-design/snapcraft.io#3487]
>  

- [ ] @`......***#` Expected behaviour

### Specs

- _URL:_
- _Operating system:_
- _Browser:_

**Comment by PaulinaParangerHr** [comment]
Gin

**Comment by tbille** [comment]
@PaulinaParangerHr I am more a rum person

**Comment by jkfran** [comment]
![](https://i.imgur.com/PX1olhY.gif)
