### ISSUE TITLE
The world map uses too much space

### ISSUE THREAD

**Issue by fitojb** [canonical-web-and-design/snapcraft.io#3489]
I suggest to replace it with a country pie chart, like Google Fonts once did back when it displayed country download statistics.

**Comment by danielmutis** [comment]
@fitojb Thanks for submitting this issue. Would you mind providing us with some more specific detail on which map do you mean and some rationale of why you think it's too big? Thanks.

**Comment by fitojb** [comment]
@danielmutis It’s just that I don’t think most snaps are geographically diversified enough that the map is interesting; in most cases, the US gets the highlight. And since the color code doesn’t (publicly) give specific stats on any snap deployments per country, I find the map uninteresting in most of the cases. That’s why I suggested replacing it with a pie chart — at least that gives you a notion of a proportion of installs per country, as opposed to the map.

**Comment by AnnSoMuller** [comment]
Thanks for the feedback, We'll take that into account while working on the enhancements of that page :)
Closing it for now
