### ISSUE TITLE
Global nav goes over admin navigation

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/snapcraft.io#3494]
# To reproduce 

- Go on /admin
- On the global nav, press `Products v`
![globaloopsi.gif](https://images.zenhubusercontent.com/583afafbb9dc3c6220228d0c/0d20eb7a-d6bd-4a19-90aa-8afadfe9718d)
- Enjoy

**Comment by steverydz** [comment]
Fixed in https://github.com/canonical-web-and-design/snapcraft.io/pull/3501
