### ISSUE TITLE
Excluded territories

### ISSUE THREAD

**Issue by SongBase** [canonical-web-and-design/snapcraft.io#3502]
My application, audovia-classic, is in the store with "Islamic Republic of Iran" as one of the excluded territories.
However, the map shows two active users here.
The application uses Java which is subject to US export controls so it is important that the "excluded territories" feature works.
I would be grateful if you would look into this.

**Comment by Roadmaster** [comment]
Hello there,

We had a detailed look at our data and we have an explanation for this.

What you see in the map are "active install" metrics. These are devices that have the snap installed, and report to the store periodically checking for updates. Metrics report on how many devices are seen per country over a 7-day sliding window.

We looked at the detailed data and indeed there are one or two devices reporting from Iran. This means when they hit the store for updates, they do so from an IP address that our geolocalization mechanism identifies as originating in Iran, so in that sense the metrics reporting is accurate and the devices are indeed in Iran.

Note, crucially, that this is reporting on devices that have the snap installed, not new installations as they happen. The explanation for what you're seeing is that those devices installed the snap *while in another unrestricted country* and then moved to Iran. The country restriction check applies only at install or refresh time, but if a device obtains the software and then moves to a restricted territory, the store and snapd don't actively disable or remove the snap from the device.

 The fact that the devices report as being in Iran confirms this theory; the service that reports refresh metrics is the same that processes install and refresh requests, so if it's correctly identifying the country, it stands to reason that it wouldn't have allowed the install to happen while the devices were there. Further, if an audovia-classic update becomes available, it will NOT be offered to these devices while in that country.

Let me know if the above explains the situation to your satisfaction.

- Daniel

**Comment by SongBase** [comment]
Hi Roadmaster,
Thank you very much for your comprehensive explanation.  This has cleared the matter up for me and, no doubt, for other developers.
I will be happy for you to close this call.

**Comment by tbille** [comment]
Closing this issue. Thanks for the answer @Roadmaster
