### ISSUE TITLE
Admin pages: manage members should use the user Account ID and not email for edition

### ISSUE THREAD

**Issue by nessita** [canonical-web-and-design/snapcraft.io#3516]
### Expected behaviour

When managing members in the new web UI, performing actions on existing users should not fail with `
store-users-multiple-matches` (`There is more than one user for the given email, please retry sending the account ID to disambiguate.`).

The backend should store the account ID associated with each store user (in a hidden field for example) and use that to hit the `/users` endpoint, to avoid getting the `store-users-multiple-matches` when editing existing store users.

### Steps to reproduce the problem

Attempt to edit the roles for a user with an email address that is not unique in the system, upon submission, the user is presented with an error `There is more than one user for the given email, please retry sending the account ID to disambiguate.` which is very puzzling.

This issue will become more and more common with the inclusion of new identity providers. For example, in staging, you could login to the snap store services with either U1 SSO prod or staging, effectively allowing two users with the same email address to coexist (and be active) in the system.

**Comment by steverydz** [comment]
This should be fixed now as the account ID is always submitted when changes are made. Please reopen if this isn't the case.
