### ISSUE TITLE
Admin pages: invites screen looks incomplete when no invites are available

### ISSUE THREAD

**Issue by nessita** [canonical-web-and-design/snapcraft.io#3517]
### Expected behaviour

There is clear message stating that there are no invites in a state that is actionable by the user (no revoked and no pending invites).

See for example in this image, it feels like the UI has not completed the loading of the content:

![Screenshot_2021-04-28 Manage invites in Foo Bar Baz Zaraza Foo Bar Baz Zaraza Snapcraft](https://user-images.githubusercontent.com/124304/116455366-5bb22000-a837-11eb-836f-e7b19dabec1d.png)

### Steps to reproduce the problem

Browse the manage invites page for a store that has no pending nor revoked invites.

**Comment by steverydz** [comment]
@danielmutis do you have any suggestions for this?
