### ISSUE TITLE
Admin pages: trying to add a user that already has a role in a store returns multiple errors

### ISSUE THREAD

**Issue by nessita** [canonical-web-and-design/snapcraft.io#3518]
### Expected behaviour

The user gets redirected to the manage members page and, ideally, the row for the given email gets highlighted.

### Steps to reproduce the problem

Try to invite a user to a store that already has a role in it. What I get is:

![Screenshot_2021-04-28 Manage invites in Foo Bar Baz Zaraza Foo Bar Baz Zaraza Snapcraft(1)](https://user-images.githubusercontent.com/124304/116455921-032f5280-a838-11eb-8c1c-65f4d8d91a1f.png)

As you can see, I got 3 errors with the same message and I was left in the manage invites screen.

**Comment by steverydz** [comment]
This should be fixed now.
