### ISSUE TITLE
Published field inconsistency - yesterday vs date

### ISSUE THREAD

**Issue by hellsworth** [canonical-web-and-design/snapcraft.io#3543]
### Expected behaviour

The "Published" field of a snap (snapcraft.io/glimpse-editor for example) should either say "Yesterday" or the date which in this case is May 11. For some reason I see both.

### Steps to reproduce the problem

Go to snapcraft.io/glimpse-editor and expand the released drop-down menu and see that "yesterday" is listed for the beta channel and "May 11" for the edge channel (see attached screenshot). Yesterday is May 11 and both were built yesterday.

![yesterday-is-may-11](https://user-images.githubusercontent.com/12970280/118012240-13eac880-b30e-11eb-8fa4-cb579b6479ce.png)

**Comment by anthonydillon** [comment]
@knotuteye are you working on this issue? Do you need a hand or pair on it?
