### ISSUE TITLE
Releases revision table reverts back to old state after it's been saved.

### ISSUE THREAD

**Issue by bjornt** [canonical-web-and-design/snapcraft.io#3571]
### Expected behaviour

When I go to the Releases tabs and promote some revisions to
some channels, when I press "Save", I would expect the table to
show the new state.

Instead  it shows the state before I made the changes. I have to
reload the page to show the new state.

### Steps to reproduce the problem

Got to https://snapcraft.io/maas/releases

Switch to the 3.0 track

Promote 3.0/edge to 3.0/beta

Click save.

The table has now reverted back and show the old revisions in 3.0/beta.

### Specs

- _URL:_ https://snapcraft.io/maas/releases
- _Operating system:_ Ubuntu 21.04
- _Browser:_ Firefox 88.0.1+build1-0ubuntu0.21.04.2

**Comment by tonyespy** [comment]
I can confirm this behavior still exists. I just released `20/edge` edgexfoundry snaps (version 2.0.0-1) to `20/beta`, and as in the original description, the UI reverts to showing the old versions after clicking `Save`. Reloading the page also causes the page to revert to `latest`, so in this case I had to re-select the `20` track before I could see the correct snaps listed.

**Comment by jkfran** [comment]
Hello, I can't reproduce it, could it be because you are not a collaborator?

@tonyespy I can see that this comment is from 20 July however you started to be a collaborator on 8 September.

**Comment by bjornt** [comment]
No, the problem is not that I'm not a collaborator. The release does happen. It just won't show up until I reload.

**Comment by bjornt** [comment]
@jkfran how did you try to reproduce it? Did you do it on a non-default track?
