### ISSUE TITLE
https://snapcraft.io/snaps doesn't show "Snap installs" graphs

### ISSUE THREAD

**Issue by RSATom** [canonical-web-and-design/snapcraft.io#3574]
### Expected behavior
Graphs should be visible

### Steps to reproduce the problem

Just open https://snapcraft.io/snaps

### Specs

- URL: https://snapcraft.io/snaps
- Operating system: Ubuntu 20.10
- Browser: Firefox 89.0 (64-bit)

![image](https://user-images.githubusercontent.com/1049634/120894037-8d8d8200-c640-11eb-93f8-db4191e05658.png)

**Comment by jkfran** [comment]
Hello @RSATom ,

by having a look a the issue I managed to reproduce it one time, looks like the issue is happening from time to time when the metrics endpoint takes a while to respond. Could you confirm if it is a permanent issue for you?

**Comment by RSATom** [comment]
@jkfran I see this issue almost always (for some months already), except very rare case when I go to details for some snap right after open https://snapcraft.io/snaps page. In that case I am able to see graphs for couple snaps with low amount of installs before browser switches to clicked link. Also, it's possible issue is related to amount of snaps in list - I have something about 15 snaps.

**Comment by RSATom** [comment]
@jkfran also I see following in JS console: 
![image](https://user-images.githubusercontent.com/1049634/120998308-2c85bb80-c7b2-11eb-9b30-7ddfaaf13bc4.png)
But don't sure if it's related...

**Comment by RSATom** [comment]
@jkfran FYI graphs now working fine (don't sure what was changed), so I'm closing this issue...
