### ISSUE TITLE
Musescore 3.6.2 ARM64 built as development build

### ISSUE THREAD

**Issue by JoshuaPettus** [canonical-web-and-design/snapcraft.io#3580]
I apologize in advance if this isn't the right place to report an issue with a specific snap, and if so, if someone could direct me to the correct place.  I'm afraid I couldn't find clear instructions for this situation.

--------------------------------------------------------------

Upon installing the arm64 Raspbian snap of musescore I found it was compiled as 3.6.2 (the current version) but as a dev build.  This makes it so it doesn't integrate with Musescore.com among other things.

To compile correctly as stable, you must modify the CMakeList.txt file and change MUSESCORE_BUILD_CONFIG from 'dev" to "release"

If someone is willing to rebuild the snap.

Unfortunately I do not know about the other architectures.

Thank you!

**Comment by jkfran** [comment]
Hello @JoshuaPettus ,

I am afraid this is not the right place. It will be better to contact the developer directly. This is the link that I found to report issues to them:
https://musescore.org/en/project/issues/musescore

**Comment by JoshuaPettus** [comment]
They don't make the snap packages either.  The only officially distributed build for linux is their .appimage, which no one has yet made a release for raspberry pi armhf or arm64.  This was done by someone with canonical.

**Comment by jkfran** [comment]
> They don't make the snap packages either. Or any other specific distribution for that matter. The only officially distributed build for linux is their .appimage, which no one has yet made a release for raspberry pi armhf or arm64. This was done by someone with canonical.

Let me ask around then, thank you for reporting.

**Comment by JoshuaPettus** [comment]
I really appreciate it.  Thank you!

**Comment by jkfran** [comment]
Apparently, the maintainer doesn't have a lot of time to maintain the snap:
https://forum.snapcraft.io/t/call-for-help-maintenance-of-the-musescore-snap/22236

Feel free to contact him or report the issue on the repo mentioned in that thread.

**Comment by JoshuaPettus** [comment]
Awesome, Thanks again!

I'll report it and hope for the best :)
