### ISSUE TITLE
fix(docs/security-sandboxing): wrong line breaking

### ISSUE THREAD

**Issue by jjangga0214** [canonical-web-and-design/snapcraft.io#3590]
Line breaking is mis-placed.

![Screenshot from 2021-06-29 12-42-25](https://user-images.githubusercontent.com/28584151/123734087-a4d62d00-d8d7-11eb-9f02-8cca2e4db4b1.png)

### Specs

- _URL:_ https://snapcraft.io/docs/security-sandboxing
- _Operating system:_ Ubuntu 20.04
- _Browser:_ firefox

**Comment by jkfran** [comment]
Thank you for reporting!
