### ISSUE TITLE
Feature request: in-snap review dialogue

### ISSUE THREAD

**Issue by CaptainDario** [canonical-web-and-design/snapcraft.io#3594]
It would be awesome if the Snapstore could provide an in-snap / in-app rating dialogue like it exist on all the other major AppStores.
For example on iOS:
![grafik](https://user-images.githubusercontent.com/51273483/124436361-27e30180-dd76-11eb-89b3-f3d377f05ce7.png)

Could such a feature be added to the SnapStore?

Edit: As I have basically no idea how the snap store works, maybe this is the wrong repo to ask about this feature. If that is the case I would be happy to be pointed in the right direction!

**Comment by danielmutis** [comment]
@CaptainDario thanks for submitting this issue. Currently we don't have reviews in the snap store as a feature, so having this pop-up wouldn't make sense. I will raise this feature request with product management, although it's unlikely to happen in the near future.

**Comment by CaptainDario** [comment]
@danielmutis the web version does not allow for reviews, however the ["snap store" snap](https://snapcraft.io/snap-store) does, or is it also not possible to add it to that?
