### ISSUE TITLE
Not all verified publishers showing as verified

### ISSUE THREAD

**Issue by cristinadresch** [canonical-web-and-design/snapcraft.io#3600]
### Not all ticks appearing

**current behaviour:**

In some cases, e.g. canonical, the account is verified but the tick isn't showing up in the /iot page, but it does show if you click through into snap details. In the example below you can see one of the snaps has the tick but the other doesnt, so it's not consistent within the page either.

![Screenshot 2021-07-07 at 10.43.48.png](https://images.zenhubusercontent.com/5c73e557b33938548e4df8a3/3f9fda5e-a62b-49d6-92d8-76623e0954a8)

![Screenshot 2021-07-07 at 10.43.42.png](https://images.zenhubusercontent.com/5c73e557b33938548e4df8a3/754c09bc-18a0-47a8-aa7b-394de559e01c)

**Comment by steverydz** [comment]
Fixed by https://github.com/canonical-web-and-design/snapcraft.io/pull/3599
