### ISSUE TITLE
Snap Store - Error un re-running automated review

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/snapcraft.io#3606]
From Emilia:
"I am getting an error while trying to re-run the automated review here https://dashboard.snapcraft.io/snaps/deliver-co/revisions/18/

I am adding a comment and then hitting "Run the automated review again" and I am getting: 

Server Error

An error occurred which prevented the page you requested from loading. If this problem continues, please consider reporting this problem by sending an e-mail to webmaster@canonical.com

Sentry ID: 672ed5d54aa2481aaf8ee0cd9101f2fc

I tried this 3 times"

**Comment by jkfran** [comment]
I am afraid we don't maintain dashboard.snapcraft.io. I created the following issue on Launchpad for that team:
https://bugs.launchpad.net/snapstore-server/+bug/1936382

I hope it helps.
