### ISSUE TITLE
Un-Register a snap name automatically if not used within 3 months

### ISSUE THREAD

**Issue by keshavbhatt** [canonical-web-and-design/snapcraft.io#3608]
### Expected behaviour
The registered snap name should have a expiration duration. On windows-store developer dashboard a developer can reserve a name for a max of 3 months. They have to publish with the reserved name within 3 months, I think it would be nice to have that in the snapcraft account dashboard too. This will prevent the abuse of name reservation process.

### Steps to reproduce the problem
* Reserve a name in the accounts section of snapcraft.io,
* The name is reserved for forever.

There is no way to give away the name without making a forum post. A release button with immediate release of name (making it available for others) with Auto release in 3 months or any other duration of choice will be very appreciative.

**Comment by cristinadresch** [comment]
@jkfran can we check if we have the API available for this?

**Comment by jkfran** [comment]
Hi @keshavbhatt,

I reported the issue in the right place https://bugs.launchpad.net/snapstore-server/+bug/1938511 , please follow the status there

This repository is only about the web UI. Thank you.
