### ISSUE TITLE
sudo snap install returns an error

### ISSUE THREAD

**Issue by CyberBlueCodes** [canonical-web-and-design/snapcraft.io#3610]
### Expected behaviour
when installing anything using the snap install command it happens like this:
         sudo snap install core
         error: cannot communicate with server: Post http://localhost/v2/snaps/core: dial unix /run/snapd.socket: connect: no such file or directory

### Steps to reproduce the problem
use this command
      sudo snap install core
### Specs

os: debian 10 on android UserLand vncserver
android ver: 5.1 lollipop
architecture: armv7 of android

**Comment by CyberBlueCodes** [comment]
dude is this repo even alive

**Comment by anthonydillon** [comment]
@CyberBlueCodes sorry for the delay on replying to your issue. This is in fact the issue list for the website itself. But happy to try and help.

I would suggest trying:
```
service snapd start
sudo systemctl start snapd.service
sudo snap install core
```
