### ISSUE TITLE
Add a packages section on Git/Github clients.

### ISSUE THREAD

**Issue by Spencerx** [canonical-web-and-design/snapcraft.io#3620]
### Expected behaviour
General issue
When I create a package offline I expect to see it online as a executable binary for a offline setting, probably on firewalled and metered networks.

### Steps to reproduce the problem
Get github support for pure Linux binary packages you see support for specific tools such as .Net, Docker, Node JS, Maven and Ruby. So when you contribute to open source you should have lesser or greater pains to kick out of your workflows when you want to use a browser to a URL with your package to be. Some of us still write java code for example.

### Specs
Subject to development environment, the usual GNU tool chain or any dev environment.
- _URL:_
- _Operating system:_
- Fedora, OpenSUSE and Ubuntu betas.
- _Browser:_
- Chrome, Firefox, Opera and Safari

**Comment by jkfran** [comment]
Hi, this is a repository for the website of snapcraft.io. I don't recognise your issue as part of it, please reopen with more information if I am wrong.
