### ISSUE TITLE
Use more rubust icon naming hash to avoid icon collisions

### ISSUE THREAD

**Issue by ogra1** [canonical-web-and-design/snapcraft.io#3622]
### Expected behaviour

seeing the uploaded icon on the snapcraft.io page of a snap

### Steps to reproduce the problem

 - create new snap (https://snapcraft.io/opennds in this case)
 - upload
 - add icon and description on the listing page
 - save 
 - go to public snapcraft.io page and observe a green cube instead of the uploaded icon file

<img src=https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_120,h_120/https://dashboard.snapcraft.io/site_media/appmedia/2021/08/logo.png>
 
while on the snapcraft.io/\<snapname\>/listing page and in various previews the correct logo is shown:

<img src=https://dashboard.snapcraft.io/site_media/appmedia/2021/08/logo.png>

### Specs

- _URL:_ https://snapcraft.io/opennds
- _Operating system:_ Ubuntu 20.04
- _Browser:_ Firefox

**Comment by hatched** [comment]
I took a quick look into this and although I don't know how the icon path is determined I believe this is a naming collision issue. A charm icon path is simply `<year>/<month>/<icon>.png` so if two people have labeled their icons `icon.png` in the same month then the first will win. 

@ogra1 updated his icon to a different name however it wasn't represented in the UI at the time this issue was created so it's possible we need to wait for a cache timeout.

**Comment by hatched** [comment]
After the timeout the icon path name change did indeed resolve this issue. So the real issue here is to use more robust naming for charm icons.

**Comment by jkfran** [comment]
I tried to reproduce it and the name collision theory didn't apply.

Just to be clear we are not doing generating the image URL on our side. It's done on the API side but before reporting the issue to them when I tried to upload the same image name on different snaps then I get a hash on the URL meaning that it is working fine.

1. Uploaded image called `test222.png` to snap [test-snap-fran](https://snapcraft.io/test-snap-fran)
    Image URL: `https://dashboard.snapcraft.io/site_media/appmedia/2021/08/test222.png`
2. Uploaded a different image called `test222.png` to snap [test-snap-amd64](https://snapcraft.io/test-snap-amd64)
    Image URL: `https://dashboard.snapcraft.io/site_media/appmedia/2021/08/test222_dt8pe8d.png`

It was working fine. I tried as well deleting the image between step 1 and 2 but it generated a new hash on the image name as well so I don't know how to reproduce it.

**Comment by hatched** [comment]
I can see now that other icons that were called 'logo' also have a hash suffix if there would be a collision....odd. I would still propose a more robust naming system in any event. Relying on a date and then a hash only if there is a collision is needlessly complex.

**Comment by jkfran** [comment]
Yeah, I don't know why they decided to do it this way.

I reported the issue on the API side, maybe they can find an explanation:
https://bugs.launchpad.net/snapstore-server/+bug/1939718

I will close the issue here.
