### ISSUE TITLE
Possible translation bug

### ISSUE THREAD

**Issue by RhFortuna** [canonical-web-and-design/snapcraft.io#3630]
I don't know if this is the right place to report this bug, sorry if not.

My system is pt_BR (Portuguese Brazil), but there is no word "directório" in my language. I don't even know if this exists in Portuguese from Portugal after the 1990 Orthographic Agreement. When I change the system language to English, none of this happens, everything works fine. I could not upgrade the Chromium with the system in pt_BR.

```
rhfor@rhfor-PC:~$ snap 
2021/08/17 18:47:09.107430 main.go:176: description of prepare-image's "<target-dir>" is lowercase in locale "pt_BR": "o directório de destino"
O comando snap permite instalar, configurar, atualizar e remover snaps.
Os Snaps são pacotes que funcionam em muitas distribuições Linux diferentes,
permitindo a entrega e operação seguras das aplicações e utilitários mais recentes.

Uso: snap <command> [<options>...]

Os comandos geralmente usados podem ser classificados da seguinte forma:

      Noções Básicas: find, info, install, remove, list
             ...mais: refresh, revert, switch, disable, enable, create-cohort
[...]
```

When I try to use tab in "snap refre":
```
rhfor@rhfor-PC:~$ snap refre2021/08/17 18:52:11.800599 main.go:176: description of prepare-image's "<target-dir>" is lowercase in locale "pt_BR": "o directório de destino"
sh 
2021/08/17 18:52:17.483284 main.go:176: description of prepare-image's "<target-dir>" is lowercase in locale "pt_BR": "o directório de destino"
Todos os snaps atualizados.
```

- _Operating system:_Xubuntu 20.04

Snap Version: 
```
snap    2.51.3
snapd   2.51.3
series  16
ubuntu  20.04
kernel  5.11.0-27-generic
```

**Comment by jkfran** [comment]
Hi @RhFortuna 

I am afraid this is not the right place to report this issue. I think the right place will be on the snapd repository, this should be the right place:
https://bugs.launchpad.net/snapd/+filebug

Thank you!
