### ISSUE TITLE
Drag-And-Drop Releases on Touch Screen Device

### ISSUE THREAD

**Issue by arossbell** [canonical-web-and-design/snapcraft.io#3632]
A problem was reported by a customer where a mobile touch screen device (Android) browser is unable to drag-and-drop in the releases selection portal (see attached customer provided screenshot).
Instead of the expected drag-and-drop for selections, the customer was only able to scroll.

![image](https://user-images.githubusercontent.com/48603952/130097154-94780614-36c3-4d1c-87a9-e8fa6f1aec7b.png)

**Comment by arossbell** [comment]
Hi web team!
@JordanMG13 will be monitoring this issue as well as the customer case from here on.
Thank you!

**Comment by JordanMG13** [comment]
Just checking in as to the status of this issue

**Comment by anasereijo** [comment]
Hi @JordanMG13,

We are currently implementing a new design to the release UI tab.
Part of this work was to make it possible to release revisions by clicking as well as drag and drop. 
Small screens will be a read-only view - we included a notification to inform the user to switch to tablet/desktop to make edits.

Hopefully, it should be all live in the upcoming weeks.

Feel free to reach out if you have any questions.

Thank you
