### ISSUE TITLE
Website link for instructions does not contain the correct content.

### ISSUE THREAD

**Issue by duwivom** [canonical-web-and-design/snapcraft.io#3635]
### Expected behaviour
Instructions for installing the snap daemon.
### Steps to reproduce the problem
Visit https://snapcraft.io/docs/installing-snapd
![image](https://user-images.githubusercontent.com/11086699/130449565-6bc5c738-eeae-41e3-98e9-d883d6d6f5e0.png)

### Specs

- _URL:_
- _Operating system:_
- _Browser:_

**Comment by jkfran** [comment]
Hi @duwivom ,

We fixed this issue, thank you for reporting it.
