### ISSUE TITLE
Game Prince of Persia 

### ISSUE THREAD

**Issue by HenriqueZ78** [canonical-web-and-design/snapcraft.io#3644]
### Specs

- _URL:_
- _Operating system:_Zorin OS 15.3

I can't download the game "Prince of Persia" on Zorin OS 15.3 and even on the current version of the system (version 16) this problem persists. I was also unable to install via the terminal.

Can someone help me? I really like this game and would like to download this game.

![f16cdb6427801e7e4552a6dbccf3b07f29956a39_2_1380x776](https://user-images.githubusercontent.com/89706979/131229042-67fd5125-97e7-49a5-9fc9-e1548d1f9165.jpeg)
![fec69a9eded07f91afc3678cf07e270eb3f2693f_2_1380x776](https://user-images.githubusercontent.com/89706979/131229043-01568d96-4302-4837-90e5-48d4dfa133b9.png)

- _Browser:_

**Comment by fitojb** [comment]
I’m afraid you’re asking on the wrong place. This is a bug tracker for the snapcraft.io website itself.

**Comment by jkfran** [comment]
Hi @HenriqueZ78 

As it was mentioned in the previous comment this is not the right place for this kind of issues. Could you please report the issue here:
https://github.com/snapcrafters/sdlpop/issues/new

Thank you!
