### ISSUE TITLE
Warning: unknown entries in snap.yaml: 'links' lint-snap-v2_unknown_field

### ISSUE THREAD

**Issue by fiftin** [canonical-web-and-design/snapcraft.io#3645]
### Expected behaviour

Create new build without warnings.

### Steps to reproduce the problem

Push changes to snapcraft.yaml repository.

### Specs

- _URL:_ snapcraft.io/semaphore
- _Operating system:_
- _Browser:_

**Comment by AnnSoMuller** [comment]
This is followed already and the team takes care of it.
You can follow the discussion [here](https://forum.snapcraft.io/t/pushing-snap-overwrites-manual-store-listing-data/26482/3)
Thanks!
