### ISSUE TITLE
Pushing snap overwrites manual store listing data

### ISSUE THREAD

**Issue by galgalesh** [canonical-web-and-design/snapcraft.io#3675]
For more info: https://forum.snapcraft.io/t/pushing-snap-overwrites-manual-store-listing-data/26482

A massive amount of snaps are automatically switched from “manually filled in listing” to “get listing data from snapcraft.yaml”, without any user interaction. This breaks the model laid out here: https://snapcraft.io/blog/better-snap-metadata-handling-coming-your-way-soon

This is a big deal. A ton of snaps in the store now have a one-line placeholder listing instead of the carefully crafted listing that we put so much effort into. The snap store attracts a lot of traffic and right now, a lot of high-quality snaps look like they’re hardly maintained. Search in the store is broken, SEO is broken, and the snaps look amateurish.

Some affected snaps:

*  https://snapcraft.io/signal-desktop
*    https://snapcraft.io/arduino

@keshavnrj has the same issue with a bunch of their snaps, and other publishers are affected too such as:

 *   https://snapcraft.io/jpg2pdf

This has been happening since at least 3 September 2021.

**Comment by galgalesh** [comment]
Note: in the case of signal-desktop, this has always been updated by the snapcraft build system. I haven't pushed anything to the store manually.

**Comment by AnnSoMuller** [comment]
Hi @galgalesh 
Thanks for reporting that issue!
Our team is working on it!

**Comment by anthonydillon** [comment]
@Roadmaster would you like to track this issue here or do you have a bug on your end which would be better update on this fix?

**Comment by jgneff** [comment]
Note that even when you want the metadata in the `snapcraft.yaml` file to overwrite the manually-entered data, it seems to be pulling the wrong field for the Snap title. See [my comment here](https://github.com/canonical-web-and-design/snapcraft.io/issues/1709#issuecomment-914517605).

I had to disable the *"Update metadata on release"* setting for the store to show the correct title.

**Comment by Roadmaster** [comment]
> even when you want the metadata in the `snapcraft.yaml` file to overwrite the manually-entered data, it seems to be pulling the wrong field for the Snap title. 

That sounds like a distinct problem/issue, @jgneff can I trouble you to please file that separately with information about what the problem is and (if possible) how to reproduce it?

**Comment by galgalesh** [comment]
@Roadmaster That issue has been filed two years ago: https://github.com/canonical-web-and-design/snapcraft.io/issues/1709

I also asked for guidance on where the code is hosted which handles this, but didn't get any response, so the community also can't help fix this issue.
