### ISSUE TITLE
Wireframe I - Progressive releases

### ISSUE THREAD

**Issue by cristinadresch** [canonical-web-and-design/snapcraft.io#3678]

**Comment by anasereijo** [comment]
[Miro](https://miro.com/app/board/o9J_lEiTPxU=/)
[Zeplin](https://miro.com/app/board/o9J_lEiTPxU=/)

**Comment by clagom** [comment]
Great work @danielmutis @anasereijo, from the benchmark to the proposal and the document for the validation with users
