### ISSUE TITLE
Manual store listing updates no longer viewable on live site

### ISSUE THREAD

**Issue by JackDandy** [canonical-web-and-design/snapcraft.io#3687]
### Expected behaviour  
  
To be able to restore a listing after the recent metadata (UMoR) "feature" wiped out carefully crafted manual snap listings descriptions.  
  
The text.. `Updates to this information will appear immediately on the snap listing page.` is no longer true.  
  
### Steps to reproduce the problem  
  
1) Manually edit a listing `Description` field
2) Click `Save`

Outcome: Saved edits are not displayed on the live snap listing page, they are only viewable as `Preview`.  
Expected: Saved manual listing edits to appear immediately on the live snap listing page, as before.

**Comment by steverydz** [comment]
Thanks for filing this issue. We will look into this.

**Comment by steverydz** [comment]
This doesn't appear to be an issue anymore so I will close this issue. If you are still having problems please reopen the issue.
