### ISSUE TITLE
Internal server error when searching for git repo

### ISSUE THREAD

**Issue by malachibazar** [canonical-web-and-design/snapcraft.io#3694]
### Expected behavior
When I search for a git repo in the build menu, it should show the results of matching repos

### Steps to reproduce the problem
1. Attach my Github account and give access to an organization.
2. Search for a git repo

### Specs

- _URL:_ https://snapcraft.io/resplendent-data-narwhal/builds
- _Operating system:_ Pop!_OS 21.04
- _Browser:_ Firefox

**Comment by jkfran** [comment]
Hi @malachibazar did you ever attach the snap to the repo https://github.com/This-Is-Hip-Hop-Borneo/Spotify?
