### ISSUE TITLE
Wireframe III - Progressive releases

### ISSUE THREAD

**Issue by cristinadresch** [canonical-web-and-design/snapcraft.io#3710]

**Comment by danielmutis** [comment]
Wireframe with the preferred option are on the "Final" page of this [Figma file. ](https://www.figma.com/file/vO6I8GQTXnywFZuTaFRFgk/Progressive-Releases?node-id=168%3A18)

**Comment by anasereijo** [comment]
> Can we also upload to Zeplin please @danielmutis @anasereijo

@clagom sure, here it goes: [zeplin link](https://zpl.io/bzOxknM)
