### ISSUE TITLE
Make the nav/header full width for the brand store

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/snapcraft.io#3721]

**Comment by steverydz** [comment]
@anasereijo @AnnSoMuller is this something you think we should do still?

**Comment by AnnSoMuller** [comment]
that doesn't ring a bell! What did you mean here? ^^

**Comment by steverydz** [comment]
@AnnSoMuller currently the global site header/nav is the same width in the brand store as it is on the rest of the site. I think it was Long that suggested we should make it full width for the brand store only. I'm not sure that this is necessary but wanted another opinion before I closed it.
