### ISSUE TITLE
https://snapcraft.io/first-snap/ros/linux/package

### ISSUE THREAD

**Issue by GAN-Canonical** [canonical-web-and-design/snapcraft.io#3732]
### Expected behaviour
snapcraft.yaml needs to be updated 
### Steps to reproduce the problem
Needs to be updated to this; https://forum.snapcraft.io/t/ros-applications/7822 
### Specs

- _URL:_https://snapcraft.io/first-snap/ros/linux/package
- _Operating system:_
- _Browser:_

**Comment by GAN-Canonical** [comment]
@cristinadresch @anthonydillon this is just a simple copy doc change - please, could I get some visibility of when this could be done?

**Comment by jkfran** [comment]
Hi @GAN-Canonical I just created a PR for it https://github.com/canonical-web-and-design/snapcraft.io/pull/3760

**Comment by anthonydillon** [comment]
Thanks @jkfran and @steverydz
