### ISSUE TITLE
Selected navigation item is not full colored

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/snapcraft.io#3754]
![image](https://user-images.githubusercontent.com/2707508/140066273-610cfd57-fd58-4fee-85af-f0a91a6dd9a1.png)

Notice there is line of pixel not colored at the bottom of the selected area.

**Comment by cristinadresch** [comment]
![Screenshot 2021-11-18 at 06.25.26.png](https://images.zenhubusercontent.com/5c73e557b33938548e4df8a3/b7edb75a-f4d4-4c2e-a4de-f7019d124b68)

To follow the same line from juju.is

**Comment by Lukewh** [comment]
![image.png](https://images.zenhubusercontent.com/59316f3551aa2c3057803f4b/e33c73ed-a3f6-4c0f-8397-394485b9357f)

Looks to be ok now, closing.
