### ISSUE TITLE
"Related Blog Posts" section can appear incorrectly on similarly named snaps

### ISSUE THREAD

**Issue by MrCarroll** [canonical-web-and-design/snapcraft.io#3762]
### Expected behaviour
The "Related Blog Posts" section on a snap listing page shouldn't appear on unrelated applications with similar names.
### Steps to reproduce the problem
Visit snapcraft.io/weka
Observe the "Related Blog Posts" section related to `wekan`, not `weka`
### Specs

- _URL:_ snapcraft.io/weka
- _Operating system:_ Windows 11
- _Browser:_ Firefox 94

**Comment by anasereijo** [comment]
@jkfran is this something you can help with?

**Comment by anasereijo** [comment]
@cristinadresch @jkfran found this issue on the Next Iteration pipeline but it's not assigned to any epic. Is this something @jkfran will work on next iteration or should we move back to Icebox/Triage?
