### ISSUE TITLE
"service status" link leads to an error page on non-Firefox browsers

### ISSUE THREAD

**Issue by Roadmaster** [canonical-web-and-design/snapcraft.io#3789]
### Expected behaviour
Going to https://snapcraft.io and clicking on "service status" at the very bottom of the page should lead to the https://status.snapcraft.io page.

I've seen that on some browsers, status.snapcraft.io instead shows  "We have encountered a problem while executing your request. Please contact support for assistance. ".

It seems to be related with the _ga query parameter sent from snapcraft.io - if that is removed, then things work well on every browser I tried.

### Steps to reproduce the problem
1. Go to  https://snapcraft.io using one of the affected browsers.
2. Click on "service status" at the very bottom of the page
3. should lead to the https://status.snapcraft.io page, not to the error mentioned above.

### Specs

- _URL:_ https://snapcraft.io
- _Operating system:_ tested on Ubuntu 20.04 and iOS 14.8.1
- _Browser:_ On Ubuntu: Chrome 95.0.4638.69 (Official Build) (64-bit) (affected). On iOS: Safari (affected).

Not affected: On Ubuntu: Firefox 94.0

**Comment by steverydz** [comment]
@Roadmaster is this still happening? I can't replicate it

**Comment by Roadmaster** [comment]
Yep, still happening on both affected browsers/platforms I mentioned in the original report. Let me know if you'd like to do a screen-sharing session so I can show you.

**Comment by Lukewh** [comment]
This has been resolved on the google analytics side :+1:
