### ISSUE TITLE
JS Error on /admin

### ISSUE THREAD

**Issue by jkfran** [canonical-web-and-design/snapcraft.io#3833]
Console error reported by @nottrobin :
```
TypeError: t[1] is undefined
    qa App.js:39
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    Redux 6
    qa brandStoreSlice.ts:38
    jr Redux
    qa App.js:25
    Dl React
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    A scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
    53 scheduler.production.min.js:12
    Webpack 10
instrument.js:109:45
```

**Comment by steverydz** [comment]
@nottrobin a couple of questions

- which store were you trying to see?
- was you able to see anything in the browser or was it just an error in the console?

**Comment by jkfran** [comment]
I am not @nottrobin but I can answer :P

> which store were you trying to see?

He couldn't chose any store, it was on `/admin` before the redirection happen.

> was you able to see anything in the browser or was it just an error in the console?

Blank screen with just the header of snapcraft.io.

**Comment by steverydz** [comment]
Ah ok - I can't see him in any of the stores so I guess that's it, but he should have been redirected to the "No stores" page in that case? I'll take a look

**Comment by nottrobin** [comment]
@steverydz I also see the "My stores" in the top right dropdown, which I don't think I should be if I have no stores right?

**Comment by steverydz** [comment]
@nottrobin as it is that should be there with a page that tells you there are no stores. I don't recall there actually being a design for this.

@AnnSoMuller do you have any thoughts on what the user should see if they are not in any stores?

**Comment by AnnSoMuller** [comment]
I think that would make sense to don't have the "My Stores" in the dropdown.

**Comment by Lukewh** [comment]
Fixed as part of https://github.com/canonical-web-and-design/snapcraft.io/pull/4040
