### ISSUE TITLE
openSUSE Tumbleweed installation guide does not work

### ISSUE THREAD

**Issue by Flexmaen** [canonical-web-and-design/snapcraft.io#3835]
### Expected behaviour
Steps in the HowTo should work. I can remember getting this to work on Tumbleweed recently, so this error must be rather new and this HowTo also has worked before on openSUSE Tumbleweed.

### Steps to reproduce the problem
I did use the steps of the URL mentioned below and used the command
`zypper addrepo --refresh https://download.opensuse.org/repositories/system:/snappy/openSUSE_Tumbleweed snappy`
(replacing openSUSE_Leap_15.2 with openSUSE_Tumbleweed as the guide suggests)

But when executing the next command (`zypper --gpg-auto-import-keys refresh`) i'll get some message that meta data is missing. Also the next steps won't work then.

### Specs

- _URL:_https://snapcraft.io/install/snap-store/opensuse#install
- _Operating system:_OpenSUSE Tumbleweed
- _Browser:_Vivaldi

**Comment by bboozzoo** [comment]
Thanks for reporting this. However, this is an issue tracked for the design/presentation bits of snapcraft.io. If you'd like to report a problem related to snapd on openSUSE, please open a topic at https://forum.snapcraft.io and include the relevant console output.

FWIW, I'm already using openSUSE on one of my devices. I've removed the repository I had and added it again using the instructions, things seem to work as expected, so when opening a topic please include the zypper console output.

**Comment by jkfran** [comment]
I am going to close the issue, please open a topic at forum.snapcraft.io if needed. Thank you.
