### ISSUE TITLE
"My Stores" redirect loop between old dashboard and snapcraft.io

### ISSUE THREAD

**Issue by nessita** [canonical-web-and-design/snapcraft.io#3854]
For the brand store admin pages migration, there will be a set of redirects from the old dashboard to snapcraft.io.

In particular, the current store list from dashboard will redirect to the "My stores" in dashboard. The problem is that, if the user has only publisher/reviewer access to stores, snapcraft.io would say:

```
No stores

Currently this section can only show stores if you are a viewer or an admin. If you are a publisher or reviewer you will find your stores on the dashboard.
```

I believe that the My Stores in snapcraft.io page should be extended so if the user has NOT any admin/viewer role in any store, a more specific message is shown, for example:

* If the user has a publisher role in any store, links to register a snap name directly in that store can be offered
* If the user has reviewer role in any store, links to the reviewer pages in the old dashboard can be offered. These are:
   * for staging data, https://dashboard.staging.snapcraft.io/stores/<store-id>/reviews/
   * for production, https://dashboard.snapcraft.io/stores/<store-id>/reviews/

This way we can safely redirect from dashboard to snapcraft.io without causing a redirect loop.

**Comment by anthonydillon** [comment]
@steverydz points seem a little low for a task with an investigation.
