### ISSUE TITLE
Review error messages on brand store invites

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/snapcraft.io#3876]
Natalia sent an email asking to review some screenshots of brand store invites error messages. She said the following:

> This is a follow up regarding the migration of the new brand store admin pages from SCA to the new storefront.
As part of that work, we needed to define a way to provide an "accept store invite" page that looks like the new site but it's served from SCA (until we can work on providing an API for it and being able to send emails pointing to the right brand store admin front). Steve provided that mock a few weeks ago (thanks!) and I have worked on using it from SCA (honoring the feature flag we have in place to redirect or not to the new pages).
So, after that intro, I need some further help from AnnSo and/or Ana with respect to a few screens that would display known errors when trying to accept an invite. I'm attaching those errors to seek feedback and assistance with the wording (and style if necessary).
I took the liberty of adding the email of the logged in user since that value is usually key to understand why accepting an invite may not be working (most likely caused by email mismatch between the email that was invited and the email from the logged in user).
Let me know your thoughts and I will adjust my work accordingly.

#### Screenshots to review:

**Already accepted**
![already-accepted.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/05f7246e-9195-43bd-8350-253aa9e5e15e)

**Revoked**
![revoked.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/32eb2344-a409-4297-b43a-bc19cd6781df)

**User email mismatch**
![user-email-mismatch.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/329735bd-df70-482f-8276-229c388102ca)

**No errors**
![no-errors.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/4b6f7d2d-1a3f-48f9-b19b-a177051cd853)

**Expired**
![expired.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/db0641ec-35c3-4c53-ab3e-1cab66edc42f)

**To do:**

- [ ] Review wording

- [x] Review styling

- [ ] Are there any actions needed on each of those messages?

- [x] Review severity levels according to [Vanilla documentation](https://vanillaframework.io/docs/patterns/notification)

- [ ] Reply to Natalia's email with the feedback

**Comment by AnnSoMuller** [comment]
- Already accepted:
Use the "warning" instead of the error ![Screenshot 2022-02-22 at 09.41.44.png](https://images.zenhubusercontent.com/606c1e6c5aab87d8cd196107/3d8cf8de-1d33-4f41-b07e-d80084968826)
- Revoked: ok
@steverydz is that an option to request a new invite?
if yes, we'll add the action "request a new invite"
- User email mismatch: ok
@steverydz is that an option to have a link to register a new e-mail address?
if yes, we'll add the action: "register a new e-mail"
- No errors: ok
- Expired: ok
If that is an option to request a new invite, we'll add the action "request a new invite"

**Comment by steverydz** [comment]
@AnnSoMuller 

> is that an option to request a new invite?
I don't believe so. If you're on that page you should have come directly from an invite

> is that an option to have a link to register a new e-mail address?
As far as I'm aware you would have to contact the administrator to request a new invite

**Comment by cristinadresch** [comment]
@AnnSoMuller @anasereijo should this be sent to natalia now? or what are the next steps?

**Comment by AnnSoMuller** [comment]
@cristinadresch I'll reply to Natalia then
Thanks @steverydz !
