### ISSUE TITLE
Closed channel arrows are ambiguous in the developer dashboard

### ISSUE THREAD

**Issue by diddledani** [canonical-web-and-design/snapcraft.io#3891]
### Expected behaviour

The developer dashboard is ambiguous when a channel has no active releases. Make the arrows have more obvious meaning.

### Steps to reproduce the problem
1. Login to dashboard: snapcraft.io -> developer dashboard
2. Navigate to Micropolis
3. Try to figure out whether candidate is actually stable, or whether it is actually edge. The arrows mean nothing because they're not tying anything. An Up arrow merely indicates a direction of travel, which could be interpreted as meaning either:
    a. the releases with arrows are forwarding TO stable
    b. the releases with arrows are forwarded FROM edge

The on-hover state is not helpful, because many people interact with their devices without a mouse these days. Relying on an on-hover state to indicate the knowledge that should be evident by a glyph then the glyph is wrong.

### Specs

Irrelevant. This is a design choice that is simply confusing and wrong.

- _URL:_
- _Operating system:_
- _Browser:_

### Screenshot
![image](https://user-images.githubusercontent.com/147548/155326803-cbfdecae-e9bd-402e-a782-35ab05a61d14.png)

**Comment by anasereijo** [comment]
Hi @diddledani, thanks for reporting this.

We are currently implementing some design improvements to this table and that is actually one of the things we are changing. Should be live soon.

Thank you
