### ISSUE TITLE
[UX] review options for ascii "starred" chars

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/snapcraft.io#3920]
go through the options for ascii star developer and provide feedback/recommendations

[copydoc](https://docs.google.com/document/d/1Q7ChjpcHyVifo30-QwUC3eAPJFwqRP6r-otJqrrh6xA/edit#)

**Comment by Lukewh** [comment]
Talked to the team and wider team and this is not required – UX have done their part, it's up to store/snapd/Gustavo to decide based on the information provided :+1:
