### ISSUE TITLE
Pagination previous and next buttons are visually off

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/snapcraft.io#3929]
Pagination has visual buy in prev next buttons
![Screenshot 2022-03-24 at 13.42.28.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/dc54b22c-a7af-4b70-b212-5bdf5283b634)

https://snapcraft.io/blog

**Comment by bartaz** [comment]
May be related to Vanilla 3.0 upgrade. I think we changed the name of the icon used in these buttons (from "contextual menu" to "chevron", or something along that lines).
