### ISSUE TITLE
Store admin pages: options for publishers and reviewers need fixing

### ISSUE THREAD

**Issue by nessita** [canonical-web-and-design/snapcraft.io#3940]
### Expected behaviour

The admin page for brand stores where a user has a non-admin role has clear and correct links to "manage your snaps" and to "perform reviews"

### Steps to reproduce the problem

Being logged in with a user that has no admin permission on a store but that has reviewer and publisher permissions, navigate to "My Stores". In there, choose the store where the user has both permissions. You'll see something like this:

![Screenshot 2022-03-30 at 08-53-19 Snapcraft - Snaps are universal Linux packages](https://user-images.githubusercontent.com/124304/160835971-91203c1a-4d79-4353-a2b0-7b71fed64cad.png)

What needs fixing is:

* The publisher actions should be both "register a snap on the Snap store" *and* "manage your snaps on the dashboard".
* The link for "manage your snaps on the dashboard" is broken, should be `https://<dashboard-url-prod-or-staging>/stores/snaps/`
* The reviewer action should read something like the following: "Review the snaps in this store on the dashboard" and the link should be constructed as follows: `https://<dashboard-url-prod-or-staging>/stores/<store-id>/reviews/`

**Comment by jkfran** [comment]
Hi @nessita , we did the changes requested here and they are in production now. Let us know if everything is working as expected.

**Comment by nessita** [comment]
Hey @jkfran thank you for working on this. It looks very good, I would only suggest that the link [register a snap name on the Snap store](https://staging-api.snapcraft.io/snaps) send the user to the actual register name page, which I understand is located in the `/register-snap` path.

As an extra bonus point, it would be ideal if the redirect to register a name would pre-select the right store in the register name store dropdown.

Thanks again!
