### ISSUE TITLE
Missing Screenshot of Applications

### ISSUE THREAD

**Issue by abhigyanghosh30** [canonical-web-and-design/snapcraft.io#3943]
### Expected behaviour

A full-sized screenshot should be visible on the carousel when clicking on the screenshot thumbnails but they are missing on a lot of applications. On clicking they open up a blank overlay.

### Steps to reproduce the problem

Click on the thumbnail to view a full-sized screenshot of the application. Some of them work, some do not. Some applications have a few screenshots working such as NextCloud's first and last screenshots are not working but the second one is. These assets do not seem to be missing. A similar issue has been raised [here](https://github.com/canonical-web-and-design/ubuntu.com/issues/11434) which depends on these screenshots.

### Specs

- _URL:_ [M.A.R.S.](https://snapcraft.io/marsshooter), [LXD](https://snapcraft.io/lxd), [NextCloud](https://snapcraft.io/nextcloud)
- _Operating system:_ Manjaro 
- _Browser:_ Chrome
![Screenshot from 2022-04-03 12-04-38](https://user-images.githubusercontent.com/30973042/161415190-a8b61b8a-687d-4982-8b40-46ccf3aa03fd.png)
![Screenshot from 2022-04-03 11-59-41](https://user-images.githubusercontent.com/30973042/161415196-02e66a61-86f5-4b09-987a-037a75908434.png)

**Comment by Lukewh** [comment]
Started a discussion with the store team to dig-in. From my bit of testing, it seems like the service that returns the images sometimes returns an empty document with an incorrect mime-type

**Comment by Lukewh** [comment]
This should be resolved there was a caching issue on the backend
