### ISSUE TITLE
Progressive releases truncate revision numbers if many architectures

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/snapcraft.io#3950]
![progressive_releases_table_cell](https://user-images.githubusercontent.com/501889/161761738-41b171b3-f879-44aa-8139-9b32c64122a5.jpg)

**Comment by anasereijo** [comment]
I think it's okay to truncate 'Progressive release'. There's is also the tooltip with more info and also the expandable cell.
Unless @spencerbygraves has a better suggestion in terms of Visual Design?


Design of [tooltip](https://app.zeplin.io/project/61b3231e21194c4a48005226/screen/61b34d612ccfb73da6480a00):
<img width="817" alt="Screenshot 2022-04-11 at 09 37 22" src="https://user-images.githubusercontent.com/36884067/162697905-8f8d77ac-f9a7-4b94-bd4c-51d0916f2cc8.png">
