### ISSUE TITLE
Bad Gateway when trying to update screenshots

### ISSUE THREAD

**Issue by Mailaender** [canonical-web-and-design/snapcraft.io#3962]
### Expected behaviour
Added/Changed screenshots

### Steps to reproduce the problem
* Add Image
* Save

### Specs

- _URL:_ https://snapcraft.io/openchrom/listing
- _Operating system:_ @openSUSE Leap 15.3
- _Browser:_ Chrome 100.0.4896.127

**Comment by Mailaender** [comment]
Still

> Bad Gateway
> Please try again later

**Comment by Lukewh** [comment]
@Mailaender would you mind sharing the image you're trying to upload so I can try to reproduce? I wonder if we're returning an incorrect error.

**Comment by jkfran** [comment]
@Roadmaster could you have a look at this 500 response we are getting from the dashboard API with this image:
```
{"error_list": [{"message": "UnidentifiedImageError: cannot identify image file <InMemoryUploadedFile: test.png (image/png)>", "code": "internal-server-error"}]}
```

**Comment by Mailaender** [comment]
This is a screenshot taken from Ubuntu that I opened in Gimp 2.10.12 to cut off the task bar.

**Comment by Mailaender** [comment]
I unticked everything and now your backend doesn't seem to crash:

![image](https://user-images.githubusercontent.com/756669/164702436-e9936eb6-cc3d-4a09-a1b4-bde0bb602884.png)

Sorry for German locale.

**Comment by Lukewh** [comment]
Thanks, @Mailaender – glad the image got uploaded, and thanks so much for the report, it will help us improve things for the future :)!
