### ISSUE TITLE
Ubuntu-sdk-ide Crash

### ISSUE THREAD

**Issue by aliencolors** [canonical-web-and-design/snapcraft.io#3981]
### Steps to reproduce the problem
run install from website 
try to launch 
### Specs
ubuntu 22/ ubuntu 16/ ubuntu 18 - VM's and real machines 
- _URL:_
- _Operating system:_ ubuntu 22/ ubuntu 16/ ubuntu 18
- _Browser:_ firefox

(process:3437): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
Running  "/snap/ubuntu-sdk-ide/3/bin/usdk-target"

(qtcreator:3437): GdkPixbuf-WARNING **: Cannot open pixbuf loader module file '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
The container backend returned an unknown error status.
This is a bug and should never happen, please contact the developers.

**Comment by jkfran** [comment]
This is the snapcraft.io website repository. Please report the issue to the publisher https://bugs.launchpad.net/~ubuntu-sdk-team
