### ISSUE TITLE
Cannot access snap pages, results in Internal Server error

### ISSUE THREAD

**Issue by jagdeva** [canonical-web-and-design/snapcraft.io#3992]
Cannot access "My published snaps" but cannot get to the snap info screens, clicking on the snaps results in below error:

Internal Server Error
Please try again later
You can check the service status at [status.snapcraft.io](https://status.snapcraft.io/).

If the problem persists please check the Snapcraft [forum](https://forum.snapcraft.io/) or [report an issue](https://github.com/canonical-web-and-design/snapcraft.io/issues/new).

**Comment by jmgiaever** [comment]
Same. The status page says everything is OK.

**Comment by jkfran** [comment]
Thank you for reporting this issue. The API started misbehaving, and we deployed a temporary fix with https://github.com/canonical-web-and-design/snapcraft.io/pull/3996 . The problem with the API is fixed as well.
