### ISSUE TITLE
cant get store listing

### ISSUE THREAD

**Issue by noharvey** [canonical-web-and-design/snapcraft.io#3994]
Internal Server Error
Please try again later
You can check the service status at [status.snapcraft.io](https://status.snapcraft.io/).

If the problem persists please check the Snapcraft [forum](https://forum.snapcraft.io/) or [report an issue](https://github.com/canonical-web-and-design/snapcraft.io/issues/new).

### Expected behaviour
store listing

### Steps to reproduce the problem
none
### Specs

- _URL:_ https://snapcraft.io/interactive-strength-studio/listing
- _Operating system:_ none
- _Browser:_ chrome

**Comment by jkfran** [comment]
Thank you for reporting this issue. The API started misbehaving, and we deployed a temporary fix with https://github.com/canonical-web-and-design/snapcraft.io/pull/3996 . The problem with the API is fixed as well.
