### ISSUE TITLE
docs search returns no results

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/snapcraft.io#3997]
### Expected behaviour

Search results should be returned.

### Steps to reproduce the problem

Go to [https://snapcraft.io/docs/search](https://snapcraft.io/docs/search) and search for something.

Eg: [https://snapcraft.io/docs/search?q=snap](https://snapcraft.io/docs/search?q=snap) returns:

![image](https://user-images.githubusercontent.com/7047542/168055444-81a9d694-e1ae-4ca7-aa83-ec0ee260bc62.png)

**Comment by jkfran** [comment]
We upgraded a dependency that is not ready to be upgraded on https://github.com/canonical-web-and-design/snapcraft.io/pull/3982/. Fixed with https://github.com/canonical-web-and-design/snapcraft.io/pull/3998
