### ISSUE TITLE
wrong link to status page

### ISSUE THREAD

**Issue by johanneswilm** [canonical-web-and-design/snapcraft.io#4003]
On https://snapcraft.io/login there is a message "bad gateway". So the server seems to be down. There is a link below the "bad gateway" message that leads to https://status.snapcraft.io/?_ga=2.13671479.149556458.1652861835-1437377229.1643485272 But that site seems to be gone. The link should probably go to https://status.snapcraft.io/ .

**Comment by jkfran** [comment]
@Roadmaster Do you know why status.snapcraft.io doesn't work when query strings are present? It should ignore it.

If that's not possible maybe we can disable the Google Analytics cross-domain tracking but I don't see an option. @caldav, do you know if it is possible to disable this tracking status.snapcraft.io?

**Comment by caldav** [comment]
@jkfran you are correct, the cross domain tracking snapcraft.io applies to itself (to cross-track subdomains) is the cause here. Fix pending review in tag manager.

**Comment by caldav** [comment]
Deployed.
