### ISSUE TITLE
Unable to add hyperlinks on store listing 

### ISSUE THREAD

**Issue by GAN-Canonical** [canonical-web-and-design/snapcraft.io#4035]
Hi team, 

Please, take  https://snapcraft.io/ubuntu-frame  as an example: 

![image](https://user-images.githubusercontent.com/78618068/174644713-136a33e4-99ff-44cd-a295-cb5458814589.png)

As you can see, using [text](Url) doesn't work. 

But, when you are editing the listing page online (using your snapcraft account) you can see the hyperlink in the preview mode:
![image](https://user-images.githubusercontent.com/78618068/174645266-bb1f26d0-9cf7-4e60-9b9f-6f1082d48ff8.png)

- So - hyperlinks work in the preview but not in the final store listing. Looks like the functionality is half there.

**Comment by steverydz** [comment]
Thanks for reporting this. We auto link any URLs in the description but we do not allow markdown or HTML links. There is a bug in the preview and we'll have a fix out for it shortly.
