### ISSUE TITLE
Add tests for date time conversion

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#4045]
General testing that the output is as expected, but specifically for daylight saving time etc. ensure that the date shows correctly during these cross-over periods.

@jkfran can you help Kevin with getting Python tests sorted?

Follow up to https://github.com/canonical-web-and-design/snapcraft.io/issues/3543

**Comment by jkfran** [comment]
Hi @knotuteye , 

I think we can add the tests here:
https://github.com/canonical-web-and-design/snapcraft.io/blob/9d390386f668c330a194d1cf98f1b2671cc89a3a/tests/store/tests_public_logic.py#L317-L327

The test should fail before your PR https://github.com/canonical-web-and-design/snapcraft.io/pull/4046 and pass now after this change.
