### ISSUE TITLE
Publisher pages heading doesn't work well with long snap titles

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/snapcraft.io#459]
<img width="1015" alt="screen shot 2018-03-27 at 13 17 30" src="https://user-images.githubusercontent.com/83575/37964311-4d581ed2-31c1-11e8-868d-465ee8853cb0.png">

**Comment by lyubomir-popov** [comment]
@bartaz could you provide markup for the above? can't access that page in my account

**Comment by lyubomir-popov** [comment]
@bartaz never mind found it in the header template

**Comment by Lukewh** [comment]
This is no longer an issue since we upgraded to Vanilla 2.0
