### ISSUE TITLE
Add ability for parametric Snap search with filters (plugs, such as `removable-media` and so on)

### ISSUE THREAD

**Issue by N0rbert** [canonical-web-and-design/snapcraft.io#642]
This is feature request.

[SnapCraft store](https://snapcraft.io/store) have a lot applications, but it does not support search Snaps by parameters.

It would be great if you add parametric search with filters. 
For example to filter all snaps with `removable-media` plug in published YAML-manifest. 
Checkboxes for other plugs will be useful too.

**Comment by matthewpaulthomas** [comment]
@N0rbert Can you give one or two examples of how searching for the `removable-media` plug (or any other) would be useful? Thanks.

**Comment by N0rbert** [comment]
I think that many newbies will think that Snap is ready for real world applications. But currently there is a small amount of Snaps which can access external media. Well known VLC is [an exception](https://askubuntu.com/q/1034030/66509). 

Many Snaps can access home folder, but not external file-systems. I think it is expected that Snap-packaged application can access files from anywhere. But currently we do not have mechanism to search such Snaps. 
And we can be surprised that for example Eclipse-snap does not [have access to external storage](https://askubuntu.com/a/1040348/66509). So this feature request will help to sort them out.

**Comment by matthewpaulthomas** [comment]
@N0rbert Thanks for the reply. To make progress on this we need to expand a little on the “help to sort them out” part.

If someone installs the Eclipse snap, then discovers that they can’t access files on external storage, they probably won’t know that this is because the snap isn’t requesting that interface. (They might not even know what a “snap interface” is yet.) And even if they do, a search function for that interface wouldn’t make any difference to whether Eclipse can access the interface.

I guess maybe it could help if there were two Eclipse snaps, one requesting the interface and one not, to help choose which one to install. Is that what you had in mind? Or something else?

**Comment by N0rbert** [comment]
I mean that we have big zoo of Snaps. Some of them can access only home-folder, but others have access to removable-media. I think that users will be happy to know which snaps have which plugs. Otherwise Snaps will be perceived as useless toys for sandbox.

**Comment by matthewpaulthomas** [comment]
Hmm, I think we actually have three separate issues here.

First: Maybe some snaps request access only to `home`, and the publisher didn’t know or remember that they should have requested `removable-media` too. If publishers often make this mistake, we might decide that it’s a design issue with the interfaces. We could fix it by changing the `home` interface to allow access to removable media as well. To argue that, we would need to compile a list of snaps that have made this mistake. I will ask the Snap Store team about this.

Second: Eclipse is not actually a case where the publisher has made this mistake. [The Eclipse snap uses classic confinement](https://uappexplorer.com/snap/ubuntu/eclipse), so it should have access to removable media. If that doesn’t work for you, please [report a bug on snapd](https://bugs.launchpad.net/snapd).

Third: The original issue of allowing search by interfaces. That feature would help us compile our list of snaps that mistakenly omit the `removable-media` interface. But that is interesting only to snapd developers, not to general users. Most people would not know that searching for that interface was a useful thing to do. (And even if they knew, they probably wouldn’t remember.) So we would still need more examples of how that kind of search would be useful to people in general.

**Comment by N0rbert** [comment]
Eclipse snap works as expected, the problem was *Welcome screen*. I'm sorry for this.

But it would be great if you propose fixes according to first and third sentences.

**Comment by jkfran** [comment]
Could be related with https://github.com/canonical-web-and-design/snapcraft.io/issues/643
