### ISSUE TITLE
Operating system names not capitalised appropriately

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/snapcraft.io#898]
1\. Go to the “Metrics” page for a snap you publish or collaborate on.
2\. Set the “Weekly active devices” graph to group “by OS”, then hover over the chart.
3\. Open the public page for the same snap.
4\. Look at the “Users by distribution” chart.

![snap os versions publisher](https://user-images.githubusercontent.com/19801137/42733497-0192c258-882a-11e8-8f55-f45e7a92c286.png) ![snap os versions user](https://user-images.githubusercontent.com/19801137/42733498-04be5d3e-882a-11e8-9833-9957f3e633b6.png)

What you see:
2\. “ubuntu 17.10”, “linuxmint 18.3“, “fedora 28”, “elementary 0.4.1”, etc.
4\. “ubuntu 17.10”, “linuxmint”, “fedora”, “elementary”, etc.

What you should see:
2\. “Ubuntu 17.10”, “Linux Mint 18.3”, “Fedora 28”, “elementary OS 0.4.1”, etc.
4\. “Ubuntu 17.10”, “Linux Mint”, “Fedora”, “elementary OS”, etc.

This can’t be done just by capitalizing the first letter: that wouldn’t work for elementary OS, Zorin OS, KDE neon, etc. Either the names should be stored correctly in the first place, or snapcraft.io needs some sort of table to map the reported names to the correctly-capitalised names.

[This is a sequel to #630.]

**Comment by Lukewh** [comment]
They're also formatted differently between the metrics page and the details page logarithmic chart

**Comment by solazio** [comment]
@Lukewh looks like if we want to fix this, we need a list with the correct capitalization of OS's and then map any other lists we use to use our list content. What are your thoughts?

**Comment by Lukewh** [comment]
@solazio what I'd do:
- [ ] ask the store team for a list of OSes in the DB
- [ ] reduce to a set of OSes without the version numbers
- [ ] find the correct capitalization for those OSes - the most manual part, one rule can't work for all
- [ ] create the map (probably in python) `{"myos": "My OS"...}`
- [ ] map the new names on the appropriate endpoints with a string replace (we want to preserve the OS version in some places)
- [ ] success
