### ISSUE TITLE
Changing title of the snap fails with: Item 6 in the array did not validate: This field is required.

### ISSUE THREAD

**Issue by jibel** [canonical-web-and-design/snapcraft.io#951]
### Expected behaviour
I'm trying to update the title of this snap https://snapcraft.io/account/snaps/sweethome3d-homedesign/listing to "Sweet Home 3D" and it fails with this error:

Item 6 in the array did not validate: This field is required.

It used to work. Besides each time I update the snap, the logo and the title are reset in the store.

### Steps to reproduce the problem
Go to https://snapcraft.io/account/snaps/sweethome3d-homedesign/listing , update the title and save the page.

### Specs

- _Operating system:_ Ubuntu 18.10
- _Browser:_ Chrome Beta 68.0.3440.75-1

**Comment by Lukewh** [comment]
Thanks for the report @jibel. We'll look into the 'Item 6 in the array did not validate' issue as this is new to us.

The issue with metadata being reset on snap update is a known issue and is being looked at by the store API team, I'll hopefully be able to update you on progress later this week.

**Comment by Lukewh** [comment]
This appears to have been fixed so closing this issue.

Please reopen it if the issue isn't resolved.

**Comment by jibel** [comment]
This is not fixed and still reproducible on this page https://snapcraft.io/account/snaps/sweethome3d-homedesign/listing by changing the title to "Sweet Home 3D" and saving the changes.

Meanwhile could you update the title until this issue is fixed?

**Comment by jibel** [comment]
Any news on this topic?
I just verified and the bug still exists and it makes the package information not look very nice and professional.

**Comment by Lukewh** [comment]
@jibel sorry you're still experiencing this bug. We're still looking in to it but as the issue is only affecting a small number of users it's hard to track down, please bear with us :)

**Comment by tg123** [comment]
Same issue here:
![Listing-details-for-sshpiperd](https://user-images.githubusercontent.com/170430/60251657-cc740400-987d-11e9-938e-b24c3025b0ae.gif)

snapcraft.yaml
<https://github.com/tg123/sshpiper/blob/master/sshpiperd/snap/snapcraft.yaml>

build/push locally

**Comment by jibel** [comment]
@Lukewh Since I can reproduce reliable, how can I help you?

**Comment by Lukewh** [comment]
@jibel if possible could you add me as a collaborator on your snap (you can remove me again at any point) by visiting https://dashboard.snapcraft.io/snaps/sweethome3d-homedesign/collaboration/ and adding luke.wesley-holley@canonical.com... This way I can do some more in-depth logging locally with a snap that is known to be experiencing this issue.

**Comment by jibel** [comment]
On 28/06/2019 11:14, Luke Wesley-Holley wrote:
> @jibel <https://github.com/jibel> if possible could you add me as a 
> collaborator on your snap (you can remove me again at any point) by 
> visiting 
> https://dashboard.snapcraft.io/snaps/sweethome3d-homedesign/collaboration/ 
> and adding luke.wesley-holley@canonical.com 
> <mailto:luke.wesley-holley@canonical.com>... This way I can do some more 
> in-depth logging locally with a snap that is known to be experiencing 
> this issue.
> 

Done. Let me know if you need anything else.


-- 
Jean-Baptiste Lallement
Canonical Services Ltd.
IRC: jibel

**Comment by Lukewh** [comment]
@jibel 	@tg123 	you should now both be able to save you snaps. @jibel I've updated yours already. Please revoke my collaborators access, it was very useful thanks :)!

**Comment by jibel** [comment]
I confirm that updating the title and the icon is now working. Thank you so much!
