### ISSUE TITLE
All RSS feed items say “The post … appeared first on Snapcraft Blog”

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/snapcraft.io#969]
1\. Load https://snapcraft.io/blog/feed in your RSS viewer of choice. (Or, y’know, look at it raw, I won’t judge.)
2\. Read the description of each item.

What you see: Every single item ends with the paragraph `<p>The post <a rel="nofollow" href="`…`">`…`</a> appeared first on <a rel="nofollow" href="https://snapcraft.io/blog">Snapcraft Blog</a>.</p>`

What you should see: No such paragraph. It’s redundant.

**Comment by Lukewh** [comment]
This seems to have been fixed at some point. Closing
