### ISSUE TITLE
Featuring most recent blog posts on front page

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/snapcraft.io#978]
The front page of snapcraft.io could better illustrate the activity around the platform. For example, we just launched Opera as a snap but you wouldn't know without clicking the blog tab.

Can we please feature the N most recent blog posts on the front page?

/cc @jamiebennett

**Comment by lilyvidenova** [comment]
I think this is a great idea, I've followed a pattern similar to ubuntu.com but using the large cards we have in s.io/blog 👍 
![image](https://user-images.githubusercontent.com/17980375/96892915-0d842480-1482-11eb-8f31-2dc546348078.png)

@clagom mind taking a look?

**Comment by clagom** [comment]
I think it's a good idea, not sure about the position on the page though, I think we need to dig a bit in Crazy Egg/GA to see the performance of the page CC @tbille

**Comment by anthonydillon** [comment]
Works well on ubuntu.com as the second strip.

**Comment by spencerbygraves** [comment]
Looks fine to me if we're happy with the position.

**Comment by spencerbygraves** [comment]
@lilyvidenova do you think the images are important, or could we save some vertical space as on ubuntu.com?

**Comment by lilyvidenova** [comment]
I personally prefer if we can keep the images as they really add to the appeal and quick understanding of what the blog post will be about.

**Comment by clagom** [comment]
Before implementing this can we run or see some analytics for the position? @tbille @lilyvidenova I would be careful in pushing down some content if it's performing well. Maybe involve also advocacy team on this. CC @cristinadresch

**Comment by lilyvidenova** [comment]
We can either put the blogs in the proposed position or after the FSF - I believe above FSF would be a better position as the blogs' strip isn't as long as the FSF one and people will be able to see both when scrolling down. Looking at the confetti and scrollmap, there isn't really much reason to put anything further down the page as it will not be seen anyway. I will chat to advocacy too. :) 

![image](https://user-images.githubusercontent.com/17980375/97284286-c8247600-1838-11eb-987b-215ca1eed39b.png)
![image](https://user-images.githubusercontent.com/17980375/97284437-f30eca00-1838-11eb-8a67-5cd1114c79c8.png)

**Comment by igorljubuncic** [comment]
The links to latest blog activity looks like a good idea (including the preview thumbnails).

The only problem I see is that the preview would be very similar to snaps you may like preview section, which could cause visual confusion/blindness. Since we already using on the Ubuntu page, the three-blog section makes sense, including its layout.

Then perhaps it might be worth redesigning the store search bar and the snaps you may like section.

Another option:

Snaps from publishers and blog post side by side in two columns?

E.g.:

Menubar
======================
Store search & snaps
======================
publishers | blog links
publishers | blog links
======================
rest of the page

What do you think?

**Comment by lilyvidenova** [comment]
Hmmm in my opinion the thumbnails for blogs and the cards for snaps look sufficiently different, and, more importantly, in most cases people will not see them both at the same time as the blogs will be just beyond the page fold. 

What do you think about the positioning on the page? After the publishers and before FSF?

**Comment by igorljubuncic** [comment]
I found them somewhat similar (primarily because the cards are white on darker bg). Between the two, I'd put after the publishers.

**Comment by lilyvidenova** [comment]
@clagom - I propose we build this (or maybe A/B test @cristinadresch - with or without the blogs strip to see if it affects the number of clicks on snaps, if it does then we can think of a way to redesign the featured snaps carousel or the blogs strip to be less similar)

**Comment by clagom** [comment]
Sounds good @lilyvidenova, also about the A/B test.

**Comment by cristinadresch** [comment]
@lilyvidenova when you create the AB test issue let me know and we can go through some numbers together, it would be useful [to use this](https://www.optimizely.com/uk/sample-size-calculator/) to work out how long we'll need to run it for

**Comment by lilyvidenova** [comment]
@cristinadresch just saw your comment - here is the issue https://github.com/canonical-web-and-design/snapcraft.io/issues/3158
