### ISSUE TITLE
Test snaps clutter search results

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/snapcraft.io#979]
1\. [Search the directory for “snapd”](https://snapcraft.io/search?category=&q=snapd).
What happens: ~51 results, of which ~45 are test snaps.
What should happen: The results contain few if any test snaps.

2\. [Search the directory for “dbus”](https://snapcraft.io/search?category=&q=dbus).
What happens: ~13 results, of which ~8 are test snaps.
What should happen: The results contain few if any test snaps.

Some possible solutions (not mutually exclusive):

- Do not display snaps in search results unless they have a stable release.

- Use channel, age, and revision count to guess whether a snap is a test [[suggested by @Greggless in snapcraft-design#512](https://github.com/CanonicalLtd/snapcraft-design/issues/512#issuecomment-409849326)]. (Drawback: False positives would be hard to notice, could discourage publishers if they didn’t notice, and could confuse them if they did notice.)

- Prohibit test snaps, implement reporting of illegitimate snaps ([snapcraft-design#476](https://github.com/CanonicalLtd/snapcraft-design/issues/476)), and let the moderation take effect for a few months.

**Comment by therealjuan** [comment]
Not in the upcoming cycle

**Comment by matthewpaulthomas** [comment]
I didn’t report this about any particular cycle. In the past year, the issue has grown:
- 95 results for “snapd”, of which ~84 are test snaps
- 14 results for “dbus”, of which 9 are test snaps

Unfortunately, [this has since been used as a way of discounting snaps](https://michal.parusinski.me/snaps-flatpaks-appimages-which-one-is-ahead.html): “There is a huge number of Playground applications on Snapcraft.io, who serve no end-user purpose. Those applications are a result of developers learning about Snaps. Let me give some examples. If one searches on [Snap store](https://snapcraft.io/store) the keyword _Hello_ one finds nearly 300 ‘Hello’ applications. Alternatively, if one searches for _Test_ one finds at least 100 ‘Test’ applications. There might be more applications on that kind.”

**Comment by Lukewh** [comment]
Unfortunately there's only a certain amount of "automated" filtering we can do. The store team have modified the search criteria to push down "test-" snaps but if you search for snapd, you will inevitably get some "test-" snaps as the snapd team use them for genuine tests.

**Comment by matthewpaulthomas** [comment]
I agree that automated filtering would be the worst solution of the three I mentioned.

Unfortunately users, and reviewers comparing snaps with other formats, don’t care whether snapd developers have an excellent reason for putting junk in the store. A fourth approach, for that problem in particular, would be for snapd developers to have a separate store for testing — “sampledata.snapcraft.io” or similar.

That would address only the “test” snaps, though, not the “hello” ones, which seem to be the result of a misguided tutorial.
